### ISSUE TITLE
in V01.00.02 : 52 cell methods are unset 

### ISSUE THREAD

**Issue by senesis** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#103]
This apply for these variables :
    6hrPlev for hus
    6hrPlev for wap4
       Eday for ta500
        Efx for clayFrac
        Efx for mrsofc
        Efx for rootd
        Efx for sandFrac
        Efx for siltFrac
       Emon for hcont300
        Eyr for cLitterLut
        Eyr for cProductLut
        Eyr for cSoilLut
        Eyr for cVegLut
        Eyr for fracLut
         fx for volcello
     IfxAnt for areacellg
     IfxGre for areacellg
        Ofx for areacello
        Ofx for cpocean
        Ofx for masscello
        Ofx for rhozero
       Omon for fbddtalk
       Omon for fbddtdic
       Omon for fbddtdife
       Omon for fbddtdin
       Omon for fbddtdip
       Omon for fbddtdisi
       Omon for fddtalk
       Omon for fddtdic
       Omon for fddtdife
       Omon for fddtdin
       Omon for fddtdip
       Omon for fddtdisi
       Omon for intdic
       Omon for intdoc
       Omon for intparag
       Omon for intpbfe
       Omon for intpbn
       Omon for intpbp
       Omon for intpbsi
       Omon for intpcalcite
       Omon for intpn2
       Omon for intpoc
       Omon for intpp
       Omon for intppcalc
       Omon for intppdiat
       Omon for intppdiaz
       Omon for intppmisc
       Omon for intppnitrate
       Omon for intpppico
       Omon for mlotstmax

**Comment by martinjuckes** [comment]
fixed
