### ISSUE TITLE
SIMIP variables in DCPP data request

### ISSUE THREAD

**Issue by DougSmithMO** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#104]
I think there is still a problem with SIMIP variables listed in the DCPP data request. Specifically, the DCPP spreadsheet http://clipc-services.ceda.ac.uk/dreq/data/tabs02/cmvme_DCPP_dcppA-hindcast_3_3.xlsx contains many variables in the SImon tab that are not requested by DCPP but are requested by SIMIP. I think these variables should only be in this spreadsheet: http://clipc-services.ceda.ac.uk/dreq/tabs03/expt_SIMIP_DCPP_3_3.html

**Comment by martinjuckes** [comment]
This was an error affecting SIMIP variables in several areas. There is a corrected list in 01.00.03, which will be released soon.

**Comment by martinjuckes** [comment]
01.00.03 did not get this right .. further problems addressed in 01.00.04
