### ISSUE TITLE
Oyr rsdoabsorb error:

### ISSUE THREAD

**Issue by jkettleb** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#105]
According to http://clipc-services.ceda.ac.uk/dreq/u/b2f82090-fbed-11e5-8f03-5404a60d96b5.html Oyr radoasorb is a single layer field.  Should this be model level (our local ocean modeller thinks it should be).  If it is model level then what is the difference between Eyr and Oyr versions of radoabsorb?

**Comment by martinjuckes** [comment]
Checking with Paul Durack.

**Comment by jkettleb** [comment]
What was the outcome of discussions with Paul?

**Comment by durack1** [comment]
@jkettleb @martinjuckes folks this isn't an `OMIP` variable it's a `FAFMIP` variable so we should be pinging Jonathan Gregory to query these

**Comment by durack1** [comment]
@martinjuckes if you ping me in issues (using @durack1) I should respond a fair bit quicker..

**Comment by durack1** [comment]
@JonathanGregory pinging you here!

**Comment by JonathanGregory** [comment]
rsdoabsorb is a variable which Steve Griffies proposed to be included. It's mentioned in K6.12 and Table L1 of the OMIP paper (Griffies et al., 2016) and Table 3 of the FAFMIP paper (Gregory et al., 2016). It should be 3D, as indicated by XYZ in Steve's table. Jonathan

**Comment by durack1** [comment]
@martinjuckes for reference http://www.geosci-model-dev.net/9/3231/2016/gmd-9-3231-2016.pdf#page=51

**Comment by martinjuckes** [comment]
@durack1 : please correct https://docs.google.com/spreadsheets/d/1M7KeHm1ZaSKClgf5O0L1-LZgWJJqaVlVTQ44jnZiT4A/edit#gid=1278664108 (sheet Oyr, row 7) to include olevel as a coordinate (or delete this row if you don't want the variable requested by OMIP) .. the FAFMIP tables already show it as a 3 dimensional variable, but the error in the above sheet makes the OMIP version look different.

**Comment by durack1** [comment]
@martinjuckes that is now updated, see https://goo.gl/Rhrcwp.

Please close this issue
