### ISSUE TITLE
mrsos spatial structure is not consistent in Emon and in 6hrPlevPt

### ISSUE THREAD

**Issue by senesis** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#106]
It should be [XY-na] {:sdepth1} like in the three other tables requesting this variable (3hr, Lmon, day)

**Comment by martinjuckes** [comment]
Fixed .. but still need to align cell_methods: spatial component of cell_methods is missing in 6hrLevPt. (area: mean where land).  Fixed by redirecting str-d45 to str-183

**Comment by martinjuckes** [comment]
fixed
