### ISSUE TITLE
v01.00.03: possible duplication (orog in fx and Efx)

### ISSUE THREAD

**Issue by matthew-mizielinski** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#112]
The variable `orog` appears in both the fx and Efx tables. In Efx orog has a time dimension, but its frequency is set to fx.

**Comment by martinjuckes** [comment]
Fixed, but see https://github.com/cmip6dr/CMIP6_DataRequest_VariableDefinitions/issues/146
