### ISSUE TITLE
v01.00.03: duplicate entries for instantaneous 6hrly ta, ua, va in 6hrPlev/6hrPlevPt

### ISSUE THREAD

**Issue by matthew-mizielinski** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#113]
miptables 6hrPlev and 6hrPlevPt appear to have near-identical entries for variables ta, ua, and va, but with subtly different temporal/spatial structures.

**Comment by martinjuckes** [comment]
Redundant structure, str-a067, will be removed, along with redundant variables.
