### ISSUE TITLE
Number of pressure levels for [uv]-tendency orographic/nonorographic gravity wave drag

### ISSUE THREAD

**Issue by jonseddon** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#115]
Hi,

In earlier versions of the data request, in table Emon the variables [uv]tend[n]ogw were defined on both 19 and 23 pressure levels. This has now been rationalised to 19 levels, apart from utendnogw  which is defined on 23 levels. Should this variable also be on 19 levels?

Thanks,

Jon

**Comment by martinjuckes** [comment]
Yes, it should be 19 .. fixed in 01.00.04.
