### ISSUE TITLE
thetaot, thetaot300, thetaot700 and thetaot2000 have wrong units and realm

### ISSUE THREAD

**Issue by TimGraham1982** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#117]
All of the above variables currently have units of K. All other ocean variables have units of degC so this seems quite inconsistent.

Also thetaot300, thetaot700 and thetaot2000 have the realm set to atmos instead of ocean.

**Comment by martinjuckes** [comment]
Realms fixed. 

As an atmospheric scientist, I find the idea of expressing potential temperature in degC rather odd. I'll get a 2nd opinion on this.

**Comment by durack1** [comment]
The OMIP/ocean data request specifies units of "degrees_C" for all temperature variables, see physics: https://goo.gl/Rhrcwp

@taylor13 @JonathanGregory

**Comment by martinjuckes** [comment]
Potential temperature considered as temperature in this context .... change to "degC" implemented
