### ISSUE TITLE
move ocean fixed from fx to Ofx table

### ISSUE THREAD

**Issue by taylor13** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#118]
@durack1 @martinjuckes  thkcello and volcello should be moved from fx to Ofx   

cf. http://cmip-pcmdi.llnl.gov/cmip5/docs/standard_output.xls
(in physics sheet
Short URL: https://goo.gl/Rhrcwp

**Comment by durack1** [comment]
@martinjuckes is the most appropriate action for me to add the variables `thkcello` and `volcello` into the physics sheet (https://goo.gl/Rhrcwp) in the `Ofx` tab? How do we get them removed from the `fx` tab/table/sheet?

**Comment by martinjuckes** [comment]
Done (01.00.06)

**Comment by durack1** [comment]
@StephenGriffies, the `thkcello` and `volcello` have been added to the `Ofx` sheet as noted above, can you please take a peek (https://goo.gl/Rhrcwp) to make sure the details/comments are correct?

**Comment by StephenGriffies** [comment]
@durack1 thkcello and volcello look good.
