### ISSUE TITLE
realms wrong

### ISSUE THREAD

**Issue by taylor13** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#122]
For consistency with CMIP5 and the CMIP6 CV at PCMDI, all instances of "seaice" should be written "seaIce" and all instances of "landice" should be written "landIce".

**Comment by martinjuckes** [comment]
The modeling_realm settings are already consistent with this. There is a different usage in CF ... but I don't think we are going to harmonise the two at this stage.

**Comment by taylor13** [comment]
I was looking at one of your spread sheet renderings which has a column "modeling_realm" with all lower case entries for seaIce and landIce.  When Denis extracts the information from your database, the correct capitalization is obtained, so I guess it's just a problem in the generation of the spreadsheets (which makes this a much lower priority issue).
thanks,
Karl

**Comment by martinjuckes** [comment]
Bug fixed now
