### ISSUE TITLE
6 CMORvars having no 'modeling_realm' associated

### ISSUE THREAD

**Issue by mpmoine** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#123]
Hi Martin,

This maybe rather a CMOR3-Tables issue, but that crept in the DataRequest: `'modeling_realm'` is missing to 6 CMOR variables (in DR 01.00.03):

> * label: hursminCrop  - Table: Emon  - Description: 
> * label: hursminCrop  - Table: Eday  - Description: 
> * label: uas  - Table: E3hr  - Description: Near surface eastward wind component
> * label: vegFrac  - Table: Eyr  - Description: 
> * label: areacella  - Table: Efx  - Description: Atmosphere Grid-Cell Area
> * label: vas  - Table: E3hr  - Description: Near surface northward wind component

Regards,
Marie-Pierre.

**Comment by martinjuckes** [comment]
fixed in 01.00.07
