### ISSUE TITLE
Lack of naming convention for zg ?

### ISSUE THREAD

**Issue by mpmoine** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#124]
Hi Martin,

It seems that there is a lack of naming convention/rules for `zg` variable. 

For instance:
- zg required on `plev27` is named `zg27` in tables CMIP6_6hrPlevPt, CMIP6_E1hr and CMIP6_Emon
- zg required on `plev7h` is named `zg7h` in tables CMIP6_6hrPlevPt
- zg required on `plev8` is named `zg` (why not` zg8`?) in CMIP6_day
- zg required on `plev19` is named `zg`  (why not` zg19`?) in tables CMIP6_Amon and CMIP6_Eday
- zg required on `plev39` is named `zg`  (why not` zg39`?) in tables CMIP6_AERmonZ and CMIP6_EdayZ
- `zg10` means  "Geopotential Height at 10 hPa" (2D field) but `zg27` for instance, means  "Geopotential Height" on plev27 (3D field)

It sounds confusing for the users and non standard that:
- sometimes the trailing number stands for the number of pressure levels, other times for the value of a single level in hPa
- sometimes the number of pressure levels is set as suffix, sometimes not.

What do you think?

Regards,
Marie-Pierre.

**Comment by martinjuckes** [comment]
True, but probably an issue to deal with in CMIP7. Some approached which worked for smaller collections of variables become confusing as the numbers increase, but it is hard to be clear and concise with so many variables.

**Comment by martinjuckes** [comment]
Moved to https://github.com/cmip6dr/cmip7_forward_look/issues/3   .. can't tackle this for CMIP6, unfortunately.

**Comment by mpmoine** [comment]
Thank you for taking my issue into consideration and for your reply. I understand it is hard to move things at this stage for CMIP6.
Regards,
Marie-Pierre.
