### ISSUE TITLE
v01.00.04: prhmax issue with cell_methods

### ISSUE THREAD

**Issue by matthew-mizielinski** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#125]
variable `prhmax` in Eday has had its cell methods changed from `area: mean time: mean within hours time: maximum over hours` to `time: mean` in v01.00.04. As this is the "Daily maximum precipitation rate" I suspect the new cell_methods are in error. I think this is down to the assignment of stid str-013 rather than str-x212 as in the 6hrPlev and Emon entries.

I also note that the 6hrPlev and Emon entries also have "Daily" in the variable title. Should the title be cut down to "Maximum hourly precipitation rate" to avoid confusion?

**Comment by martinjuckes** [comment]
The cell methods error has disappeared.  I've change the title as you suggested.
