### ISSUE TITLE
v01.00.04: Variables in 6hrPlev with no pressure level dimension

### ISSUE THREAD

**Issue by matthew-mizielinski** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#126]
In the update from v01.00.03 to v01.00.04 the variables `ta`, `ua` and `va` in table 6hrPlev have lost their pressure level coordinate (previously this was plev3).

**Comment by martinjuckes** [comment]
These are now in 6hrPlevPt (instantaneous fields)
