### ISSUE TITLE
v01.00.04: modeling_realm of frozen & liquid water content of soil layers 

### ISSUE THREAD

**Issue by matthew-mizielinski** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#128]
The modeling_realm of `mrsfl` and `mrsll` in Emon has changed from land to atmos, which is now inconsistent with the equivalent entries in Eday. Given that these variables are frozen and liquid water content of soil layers this looks like a error

**Comment by martinjuckes** [comment]
Fixed
