### ISSUE TITLE
v01.00.04: SIday/siconc has modeling_realm aerosol

### ISSUE THREAD

**Issue by matthew-mizielinski** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#130]
http://clipc-services.ceda.ac.uk/dreq/u/d243b4a4-4a9f-11e6-b84e-ac72891c3257.html 

I'd expect its provenance to point back to SImon as well.

**Comment by martinjuckes** [comment]
realm fixed, provenance to do

**Comment by martinjuckes** [comment]
done
