### ISSUE TITLE
v01.00.04: Omon / dmso & dmsos

### ISSUE THREAD

**Issue by matthew-mizielinski** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#131]
In the Omon table variables `dmso` and `dmsos` appear to be the same quantity with different stids. Emon contains a 3d version of `dmso` (from C4MIP), which could be merged into the Omon counterpart if appropriate.

**Comment by martinjuckes** [comment]
Will be fixed in 01.00.06 ..
