### ISSUE TITLE
orog and orogIs

### ISSUE THREAD

**Issue by martinjuckes** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#132]
Hello Karl,

With reference to item 1 of https://github.com/cmip6dr/CMIP6_DataRequest_VariableDefinitions/issues/120 

orogIs/LImon is the same as orog/ImonAnt etc, but on a different grid. ISMIP6 have a number of variables which they require both on the ice sheet grids and on the global grids to support different analyses. It would be possible, in principle, to create the LImon version from the data on the ice sheet grids, but as the latter are already interpolated data there would be inevitable accumulation of errors due to the double interpolation.  The LImon version is masked by ice sheet. There are other variables in this category which also occur in LImon without such masking, and hence we have appended "Is" to the masked versions to preserve unique variable names. The omission of an unmasked monthly "orog" is an error: if a model has evolving orography, the global orographic field should be monthly, not fixed.  

There are two ways we could fix this:
 1. Include a monthly orography in LImon for use when there ice fields with time varying orography;
 2. Include a masked "where not ice shelf" orography in "fx" for use when ice fields have time varying orography.

I can see (1) being inconvenient for people wanting to analyse the 99% of the globe which has fixed orography, but (2) would need a new area type (there is a "ice_free_land" area type, but not an "ice_shelf_free_land") and may be error prone in cells which are part ice shelf and part ice free land.

**Comment by taylor13** [comment]
thanks for thinking about this.  

currently the various "orog" fields appear in the following tables:

fx:  orog -- surface altitude (all surfaces); freq. = fx; cell_methods = area:mean; dims = lon, lat; realm = atmos

Efx: orog -- surface altitude (all surfaces); freq. = fx; cell_methods = time:mean; dims = lon, lat, time; realm = land

ImonAnt, ImonGre: orog -- surface altitude (all surfaces); freq. = mon; cell_methods = area time:mean where ice_shelf; dims = x, y, time; realm = land

LImon: orogis -- surface altitude (all surfaces); freq. = mon; cell_methods = area time:mean where ice_shelf; dims = lon, lat, time; realm = landice

For the global domain:
For fixed ice sheets (and fixed ice shelves), I think fx: orog is sufficient.
For time-varying ice sheets (and ice shelves), I think Efx:orog is sufficient but should be moved to table Eyr and have cell_methods = area:mean time:mean and freq = "yr"

I guess the ice-sheet modelers want the height of the ice_shelf, but I would only ask for:
ImonAnt, ImonGre: orog (but I think it should be named "orogis" and realm = landice)

I don't think we need LImon: orogis.  Hardly anyone wants to know what the ice-shelf surface altitude is, and if they do, they can get if from the Ant or Gre tables.

Question:  does "is" stand for ice-sheet or ice-shelf?  I've assumed here it stands for "ice-shelf".

**Comment by martinjuckes** [comment]
I'll add a time varying global orography ... but, for consistency with the ISMIP6 request I think it would be better as a monthly field. 

ISMIP6 have requested the LImon orogis field. I believe that they have two sets of analysis packages -- one to look at data on the specified ice sheet grids, and a 2nd to look at the interaction with the global circulation on the atmospheric data grid. For the latter, they want to know the height of the ice sheet in each grid cell.  "Is" should stand for "ice sheet" -- there is an error in the cell_methods string which I'll fix. 

For the time varying global orography, we need to make sure that it is always requested, as an option -- so that it should always be provided instead of the fixed orography if the model has time varying ice sheet heights. I could do this by adding it to the "fx" variable group.
