### ISSUE TITLE
v01.00.04 variables affected to atmos realm that should go in land realm

### ISSUE THREAD

**Issue by SebastienDenvil** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#133]
Dear Martin,

IPSL's internal review of the data request identified that the following CMOR variables are affected the wrong realm. They have the atmos realm and we think they should go in the land realm. Let us know if you have any questions or if you need more details.

regards

rivi
rivo
wilt
wtd
cpnz
qgwr
rootdsl
rzwc
sandFrac
slthick
tcs
tgs
tsnl
tws
fldcapacity
ksat
mrfsofr
mrlqso
mrrob
mrsll
mrsow
netAtmosLandCO2Flux
nudgincsm
nudgincswe
potet
evspsblpot
ec
es
esn
et
eow
drivw
dslw
dsn
dsw
dtes
dtesn
cw
sw
albc
albsn
ares
cLAND
cnc
cw
dcw
dfr
dgw
dmlt
dslw
drivw
dsn
dsw
dtes
dtesn
ec
eow
es
esn

**Comment by martinjuckes** [comment]
Fixed for 01.00.05
