### ISSUE TITLE
v01.00.04 variables affected to atmos realm that should go in ocean realm

### ISSUE THREAD

**Issue by SebastienDenvil** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#134]
Dear Martin,

IPSL's internal review of the data request identified that the following CMOR variables are affected the wrong realm. They have the atmos realm and we think they should go in the ocean realm. Let us know if you have any questions or if you need more details.

regards

thetaot
thetaot2000
thetaot300
thetatot700
sltbasin
sltnorth
sltnortha
t20d

**Comment by martinjuckes** [comment]
Thanks, fixed in 01.00.05
