### ISSUE TITLE
v01.00.04 variables affected to aerosol realm that should go in atmos realm

### ISSUE THREAD

**Issue by SebastienDenvil** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#135]
Dear Martin,

IPSL's internal review of the data request identified that the following CMOR variables are affected the wrong realm. They have the aerosol realm and we think they should go in the atmos realm. Let us know if you have any questions or if you need more details.

regards

ua10 (inconsistent definitions : 10 m or 10 hPa)
ccn (Note that this looks the same as conccn in atmos)
cdnc

**Comment by martinjuckes** [comment]
ua10 is now ua at 10hPa, the 10m wind is uas.
ccn and conccn: I have not received any confirmation, but ccn has CF standard name number_concentration_of_cloud_condensation_nuclei_at_stp_in_air which includes, in its definition "The ability of a particle to act as a condensation nucleus is determined by its size, chemical composition, and morphology". This, I think, makes it clear that cnn refers to a potentially smaller set of aerosols than concccn.
cdnc: realm fixed.
