### ISSUE TITLE
CFsubhrOff not requested in CMIP6

### ISSUE THREAD

**Issue by alejandrobodas** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#136]
The mip table CFsubhrOff appears in the CMIP6 request. They were part of the CMIP5 request, but they are not required in CMIP6 because the request was simplified and we only ask for the full domain 3-hourly diagnostics (mip table E3hrPt).

**Comment by martinjuckes** [comment]
Removed in 01.00.11
