### ISSUE TITLE
 v01.00.04 variables affected to atmos realm that should go in atmosChem realm

### ISSUE THREAD

**Issue by SebastienDenvil** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#137]
Dear Martin,

IPSL's internal review of the data request identified that the following CMOR variables are affected the wrong realm. They have the atmos realm and we think they should go in the atmosChem realm. Let us know if you have any questions or if you need more details.

regards

oxloss
oxprod
vmrox
flashrate

**Comment by martinjuckes** [comment]
Done (01.00.06)
