### ISSUE TITLE
Order of cell_methods components.

### ISSUE THREAD

**Issue by martinjuckes** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#14]
The CF Convention states that "If more than one cell method is to be indicated, they should be arranged in the order they were applied. The left-most operation is assumed to have been applied first." The data request contains many examples of quantities averaged over a grid cell and over time. In the CMIP5 request these were labelled with `time` first in `cell_methods`, e.g. `time: mean area: mean where ice_free_sea over sea`. If interpreted strictly, this means that a temporal mean should be taken first, followed by a spatial mean over sea. In practise, because `ice_free_sea` is generally specified as a fraction rather than as a spatial field within the grid cell, the spatial mean has to be done first. For clarity, I would like to change the order to specify spatial means first.  
There is a related discussion on the treatment of weighted time means in the CF Trac site: 
http://cf-trac.llnl.gov/trac/ticket/152

**Comment by martinjuckes** [comment]
There is a related discussion on the

**Comment by taylor13** [comment]
I can say that there was no thought given to ordering of these in CMIP5, and I agree that the argument to reverse their order is a good one.  This should have no affect on CMOR (or any other software I know of), so inconsistency between CMIP5 and CMIP6 ordering shouldn't cause any problems I can think of.
