### ISSUE TITLE
AERday single level pressure variables have no pressure coordinate

### ISSUE THREAD

**Issue by jkettleb** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#141]
Variables ua10, zg10, zg100, zg500, zg1000 in AERday are dimensioned 'longitude latitude time'.  For consistency with other tables (e.g. 6hrPlev) should these be dimensioned 'longitude latitude pXXX time' where pXXX is a scalar coordinate for the pressure level?

**Comment by martinjuckes** [comment]
Fixed
