### ISSUE TITLE
wrong mip table zg500

### ISSUE THREAD

**Issue by jkettleb** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#142]
Should zg500 be in table 6hrPlev rather than 6hrLev?

http://clipc-services.ceda.ac.uk/dreq/u/6eaa0a74-05a7-11e7-88ed-5404a60d96b5.html

**Comment by taylor13** [comment]
Yes.  I agree.  See #120

**Comment by martinjuckes** [comment]
Fixed
