### ISSUE TITLE
siconc in wrong table

### ISSUE THREAD

**Issue by taylor13** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#143]
The siconc is, I presume, what we called "sic" in CMIP5.  In any case, it doesn't belong in the AERmon table.  It should be moved back to the SImon table (which was called OImon table in CMIP5).  Also, as we've discussed it should have units of %.

**Comment by taylor13** [comment]
Also note this issue which indicates that The SImon table in Feb. included siconc: https://github.com/PCMDI/cmip6-cmor-tables/issues/37

**Comment by martinjuckes** [comment]
Fixed in 01.00.06
