### ISSUE TITLE
"mon" should be "monClim" for some amon variables

### ISSUE THREAD

**Issue by taylor13** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#147]
Hi Martin,

As you know, there are a few variables in the amon table that for some models will be reported monthly and for other models they are reported as climatological monthly mean values (e.g., o3 and o3Clim get stored as "o3", but can either be monthly mean or climatology).  In the CMIP6 table both have frequency = "mon", but in CMIP5 one was frequency mon and the other monClim.  The "Clim" variables should have frequency "monClim".

Alternatively, we could eliminate "monClim" as an allowed frequency in CMIP6 (since the bounds attribute tells us the variable is stored as  a climatology), but this would perhaps hide the information from some users (because frequency is a global attribute, but bounds is a variable attribute).  What should we do?

Fixing this should be high priority because *how* we fix it has important implications for CMOR, which is starting to be used.

thanks,
Karl

**Comment by martinjuckes** [comment]
Sorry ... this got caught between the objective of having a single frequency for each table and the opposing objective of not having too many tables. I think we need to keep "monClim" for clarity (I'll add it back in for the relevant variables), and it is too late to introduce a new table for these variables, so we need to drop the objective of having a single value of the frequency in each table.

**Comment by martinjuckes** [comment]
Fixed in 01.00.06
