### ISSUE TITLE
Dimensions for jpdftaureicemodis and jpdftaureliqmodis

### ISSUE THREAD

**Issue by jonseddon** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#151]
Hi,

In the data request and the mapping tables for jpdftaureicemodis and jpdftaureliqmodis the dimensions contain "effectRadIc|tau". The vertical bar in the dimensions is stopping CMOR from loading this table. We've not seen the vertical bar before. Is this meant to be here, or should it be a space? If it should, then we will have a look at getting CMOR ready to handle this.

Thanks,

Jon

**Comment by martinjuckes** [comment]
Sorry, I'll change this to a space.

**Comment by martinjuckes** [comment]
fixed in 01.00.07
