### ISSUE TITLE
Odec msftmyz

### ISSUE THREAD

**Issue by martinjuckes** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#156]
@durack1 Hello Paul,
The definition of msftmyz in Odec says that only the y-coordinate version msftyyz should be provided if he model is on a regulat grid, but msftyyz is not included in Odec.  Should msftyyz be added?

**Comment by durack1** [comment]
@martinjuckes good question, I might also poll @jonathangregory for this one - Jonathan, do you recall a reason this variable was not specified?

I believe this is probably just an oversight and I can include the additional variable.. @martinjuckes please keep this open until the change has been made.. I'll await any additional commentary from Jonathan before making the amendment

**Comment by JonathanGregory** [comment]
Yes, I think msftyyz should be included in Odec. I see that both thetaoga and bigthetaoga are included, which is fine since they are likewise alternatives (depending on what the prognostic ocean temperature is), but in that case shouldn't bigthetao be included, since thetao is there? @durack1

**Comment by durack1** [comment]
@JonathanGregory thanks for chiming in, I'll add in both `msftyyz` and `bigthetao` as you suggest, the `Odec` sheet was a relatively late inclusion from Helene (Hewitt) so I am glad that we're reviewing this now..

@JonathanGregory there is also another issue #164 that could do with your chime in too.. You have most likely thought about the naming conventions at least as much as others.. And it would be good to clarify the name of `msftyyz` before adding it to the `Odec` sheet

**Comment by martinjuckes** [comment]
Resolved ..

**Comment by durack1** [comment]
@martinjuckes @JonathanGregory @StephenGriffies `bigthetao` has now been added to the sheet, and following #164 I have renamed `msftmyz` to `msftmz` and added the new variable `msftyz` - see `Odec` sheet in https://goo.gl/Rhrcwp

**Comment by durack1** [comment]
@StephenGriffies, it seems the `msftmrho` and `msftyrho` may also be needed?

**Comment by StephenGriffies** [comment]
@durack1 I am unsure what is the action. msftmrho is in Omon as variable 46 and msftyrho is 48.

**Comment by durack1** [comment]
@StephenGriffies sorry I should have been more clear. This issue was about the `Odec` variables and for this temporal allocation we only have `msftmz` (Odec, A-Z26) and `msftyz` (Odec, A-Z27), so there is no `*rho` outputs requested for this time domain.

@taylor13 pinging you here

**Comment by StephenGriffies** [comment]
I support adding the corresponding *rho output for the Odec.  Doing so would be of great use for monitoring spin ups.  And most people only focus on the long-term overturning, so having decadal means will be of great help.  

Thanks again for spotting these issues.

**Comment by durack1** [comment]
@StephenGriffies thanks, these are now found in the revised google sheet https://goo.gl/Rhrcwp (Odec)
