### ISSUE TITLE
Some experiment labels do not match CMIP6_CV experiment names

### ISSUE THREAD

**Issue by mpmoine** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#157]
Dear Martin,

_(on DR v01.00.05)_

Unless I missed some information somewhere, oustide the Experiment collection, it seems that there are some experiment labels that do not match the CMIP6_CV experiment names (source: https://github.com/WCRP-CMIP/CMIP6_CVs)
For instance:
- `Forced-Atmos-Land` instead of `highresSST-present`
- `Forced-Atmos-Land-2050` instead of `highresSST-future`

Others seems to miss in the experiment collection, e.g., `highresSST-4co2`.

Regards,
Marie-Pierre.

**Comment by martinjuckes** [comment]
Fixed in 01.00.12
