### ISSUE TITLE
clean radiation fluxes

### ISSUE THREAD

**Issue by MartineMichou** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#160]
Dear colleague,

In the Data request 01.00.06 I have the following questions:

- what is the difference, if any, between the rsutna and rsutca
variables, and between the rstunacs and rsutcsca variables?

- if the answer to the first question is "there is no difference", then
please amend the naming of the rlutca rlutcsca variables according to
the naming chosen for the short wave fluxes.

Regards, Martine Michou

**Comment by martinjuckes** [comment]
It looks as though they are the same, also, "rsutcc" is probably the same as "rsutnacs". I will check with the MIPs that proposed them.

**Comment by martinjuckes** [comment]
Confirmed as:
rsut: TOA Outgoing Shortwave Radiation
rsutcs: TOA Outgoing Clear-Sky Shortwave Radiation
rsutca: TOA Outgoing Clean-Air Shortwave Radiation
rsutcsca: TOA Outgoing Clear-Sky, Clean-Air Shortwave Radiation
