### ISSUE TITLE
CMOR variable sithick {SImon} missing from version 01.00.06 of the data request

### ISSUE THREAD

**Issue by ehogan** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#161]
The CMOR variable `sithick {SImon}`, which was available in version 01.00.05 of the data request, is now missing from version 01.00.06 of the data request, see http://clipc-services.ceda.ac.uk/dreq/u/591321f8-9e49-11e5-803c-0d0b866b59f3.html.

**Comment by martinjuckes** [comment]
Fixed
