### ISSUE TITLE
dimensions for zonal means missing longitude

### ISSUE THREAD

**Issue by jonseddon** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#163]
Hi,

longitude isn't in the dimensions of the zonal mean variables. Issue #67 had longitude added to the cell_methods but after talking to @jkettleb we think that longitude should be in the dimensions too. The CF Standard says that the name in a cell method should be a dimension or scalar.

Thanks,

Jon

**Comment by martinjuckes** [comment]
The CF standard says that 'name can be a dimension of the variable, a scalar coordinate variable, a valid standard name, or the word "area"'  ... in this case we have a valid standard name, which is OK.

**Comment by jonseddon** [comment]
Sorry, I hadn't read that fully, or understood the section of the standard regarding cell methods where there are no coordinates. We're happy that everything is correct.

**Comment by jkettleb** [comment]
Apologies from me too.  I had not digested the paragraph in CF in section 7.3.4 that begins:

> Second, for a few special dimensions, this convention allows one to indicate (without explicitly defining the coordinates) that the method applies to the domain covering the entire permitted range of those dimensions.
