### ISSUE TITLE
hfgeou present in Omon without a time dimension, and could rather be soleley in Ofx

### ISSUE THREAD

**Issue by senesis** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#167]
hfgeou is present both in Omon and Ofx. Maybe in order to cope with models having a time varying hfgeou? In that case, it should have a time dimension in Omon. 

For NEMO, hfgeou is a fixed field. How are we supposed to cope with the fact that hfgeou is also required in Omon ? I mean : is there an attribute, readable through the Dreq API, that indicate a possible choice between the two tables ?

**Comment by martinjuckes** [comment]
This should be indicated by a varChoiceLinkC record .. but not yet implemented .. you only need to produce the one which is relevant to your model.

**Comment by martinjuckes** [comment]
Moved to https://github.com/cmip6dr/Request/issues/61
