### ISSUE TITLE
clhcalipso required in E3hrPt table on single level, but don't know which one

### ISSUE THREAD

**Issue by mpmoine** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#168]
Dear Martin,

`cid` is `[remarks] __unset__ []` for clhcalipso in table `E3hrPt`, thus we don't know the value of the single pressure level it is required on.

_(issue raised on DR 01.00.07)_

Regards,
Marie-Pierre.

**Comment by martinjuckes** [comment]
Fixed in 01.00.08 (should be as for CFmon: p220).

**Comment by mpmoine** [comment]
Thanks !
