### ISSUE TITLE
Some C4MIP-related variables of PMIP can be removed from Emon

### ISSUE THREAD

**Issue by jypeter** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#169]
@martinjuckes The following variables were requested by PMIP because we needed a subset of C4MIP (mostly priority 1 variables of C4MIP), but **they can now be removed from Emon** because they are not in the latest version of the C4MIP DR (variables have been removed or renamed)

- pcp (probably removed because we can use **pr** from _Amon_)
- fDeforest
- lateralCtransfer
- fNdepox
- fNdepred
- fBNFsymb
- fBNFasymb

**Comment by martinjuckes** [comment]
Done in 01.00.08
