### ISSUE TITLE
Update the "description" column of Emon for some C4MIP variables

### ISSUE THREAD

**Issue by jypeter** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#170]
@martinjuckes when we look at the **description** column of [CMIP6_MIP_tables.xlsx](http://proj.badc.rl.ac.uk/svn/exarch/CMIP6dreq/tags/latest/dreqPy/docs/CMIP6_MIP_tables.xlsx) (01.00.07 and earlier), we have several variables that have the following description: _as specified by C4MIP_

This has been inherited from the original [PMIP Data Request](https://pmip4.lsce.ipsl.fr/lib/exe/fetch.php/database:cmip6datarequestcompilationtemplate_20141218_pmip_v150228_final.xls), where we copied some priority 1 variables from C4MIP

I have compared this with the latest C4MIP DR supplied by Chris Jones and we need 2 types of changes so that the global DR correctly matches the C4MIP DR (for this specific problem)

In the end, there should be no more _as specified by C4MIP_ in the Emon panel

## Remove the variable

Some variables can be completely removed, as specified by #169

## No content in the description column

Remove _as specified by C4MIP_ from **description** for:

- c14Veg
- c14Litter
- c14Soil
- c13Veg
- c13Litter
- c13Soil
- c13Land
- rac14
- rhc13
- dissi14c
- fNup
- fNnetmin
- vegHeightGrass
- vegHeightShrub
- vegHeightCrop
- fNleach
- fN2O
- vegHeight
- vegHeightTree
- c14Land
- wetlandCH4
- gppc14
- rhc14
- netAtmosLandC14Flux
- gppc13
- rac13
- netAtmosLandC13Flux
- fNgas
- fg14co2

## Updated content

Replace _as specified by C4MIP_ in **description** with the correct text (that I have copied from the C4MIP DR)

- **mrlso**: the mass (summed over all all layers) of liquid water.
- **mrsol**: in each soil layer, the mass of water in all phases, including ice.  Reported as "missing" for grid cells occupied entirely by "sea"
- **mrsfl**: in each soil layer, the mass of water in ice phase.  Reported as "missing" for grid cells occupied entirely by "sea"
- **nLitter**: Report missing data over ocean grid cells. For fractional land report value averaged over the land fraction
- **nProduct**: Report missing data over ocean grid cells. For fractional land report value averaged over the land fraction.
- **nLand**: Report missing data over ocean grid cells. For fractional land report value averaged over the land fraction.
- **mrtws**: Mass of water in all phases and in all components including soil, canopy, vegetation, ice sheets, rivers and ground water.
- **treeFracNdlDcd**: This is the fraction of the entire grid cell  that is covered by needleleaf deciduous trees.
- **treeFracBdlEvg**: This is the fraction of the entire grid cell  that is covered by broadleaf evergreen trees.
- **treeFracBdlDcd**: This is the fraction of the entire grid cell  that is covered by broadleaf deciduous trees.
- **grassFracC3**: Fraction of entire grid cell covered by C3 grass.
- **grassFracC4**: Fraction of entire grid cell covered by C4 grass.
- **netAtmosLandCO2Flux**: This flux should be reproducible by differencing the sum of all carbon pools (cVeg, cLitter, cSoil, and cProducts or equivalently cLand) from one time step to the next, except in the case of lateral transfer of carbon due to harvest, riverine transport of dissolved organic and/or inorganic carbon, or any other process (in which case the lateral_carbon_transfer_over_land term, see below, will be zero data).
- **mrsll**: in each soil layer, the mass of water in liquid phase.  Reported as "missing" for grid cells occupied entirely by "sea"
- **vegFrac**: fraction of grid cell that is covered by vegetation.This SHOULD be the sum of tree, grass, crop and shrub fractions.
- **treeFracNdlEvg**: This is the fraction of the entire grid cell  that is covered by needleleaf evergreen trees.
- **cLand**: Report missing data over ocean grid cells. For fractional land report value averaged over the land fraction.
- **wetlandFrac**: Report only one year if specified fraction is used, or time series if values are determined dynamically.
- **nVeg**: Report missing data over ocean grid cells. For fractional land report value averaged over the land fraction.
- **nSoil**: Report missing data over ocean grid cells. For fractional land report value averaged over the land fraction.

**Comment by martinjuckes** [comment]
OK, except the the "fractions" are in fact percentages. done in 01.00.08
