### ISSUE TITLE
v01.00.08 dbze crept into some variable dimensions

### ISSUE THREAD

**Issue by jkettleb** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#173]
I think an extra dimension of 'dbze' has crept into some variables.  e.g. AerMon va.

This may be because of:

http://clipc-services.ceda.ac.uk/dreq/u/f7e94ce4-562c-11e6-a2a4-ac72891c3257.html

which has a `dbze` dim?

There may be other cases of this - not just those mentioned here.

**Comment by martinjuckes** [comment]
Fixed in 01.00.09 ... a software editing error
