### ISSUE TITLE
"na-A" spatialShape and information contained in "dids"

### ISSUE THREAD

**Issue by mpmoine** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#177]
@martinjuckes 
Dear Martin,

_(on DR 01.00.08)_ 

Inspecting spatialShape for the variables requested at sites ("S-A",  "na-A", "S-na", "S-AH"), I discovered  that `dids` hosts information about the spatial dimensions `site` in `na-A` case. 

This sounds to be an exception since -correct me if I am wrong- `dimids` usually contains all the information about spatial dimensions and `dids` contains the information about "other" dimensions (e.g. `spectband`).

Up to now, we use only `dimids` information to get the spatial dimensions, could you tell me if we have to add an exception for this cas in our process? Is there other similar cases?

Regards,
Marie-Pierre.

**Comment by martinjuckes** [comment]
This was an error: dimids and dimensions should have the same information. dimids is supposed to be the reference, dimensions is there for backwards compatibility. I believe it is now resolved.
