### ISSUE TITLE
missing "title", "coords", and/or "odim"

### ISSUE THREAD

**Issue by taylor13** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#178]
When Denis imports your latest DREQ database he finds a few variables that don't include "coords", "title", and/or "odim".  Before these elements were always present (although they might not have been defined).  He has had to revise his "translation" code that creates the CMOR tables from your database to accommodate this new exception.

Did you mean to omit these 3?  If so, why?

**Comment by martinjuckes** [comment]
Yes, this was intended. There was a short explanation in the email that went of with release 01.00.09:

> There is a change in this version in the way in which some optional attributes are handled which may cause problems for some software. The "odims" attribute of the "structure" records has always been flagged as optional, but has always been present in every record, with a empty string when no value was needed. This has now been made more consistent with the intended data model by omitting the attribute when there is no value. Statements of the form:
>     if item.odims == '':
>       pass
> need to be replaced with:
>    if item.__dict__.get( 'odims', '' ) == '':
>        pass
> or:
>    if 'odims' in item.__dict__:
>       pass
>  
> Making such a change may be inconvenient to some, but I hope that the cleaner use of the data model will be beneficial in the long run
