### ISSUE TITLE
0.100.10 6hrPlevPt pfull27 requested on pressure levels

### ISSUE THREAD

**Issue by jkettleb** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#181]
I think pfull27 in 6hrPlevPt has been requested on plev27.  Should this be pressure on model levels (and in table 6hrLevPt)?

**Comment by jkettleb** [comment]
I've just noticed this is a priority 3 HiResMIP requested diagnostic - so (for MO) is not high priority.

**Comment by martinjuckes** [comment]
I think this is part of a group of variables originally requested on model levels and then moved to pressure levels --- we should have removed pfull from the request at that stage. I'll take it out now.

**Comment by martinjuckes** [comment]
Removed.

**Comment by senesis** [comment]
Also, there is a comment somewhere by Karl Taylor stating that pfull is not requested for models using sigma or hybrid (pressure based) coordinates
