### ISSUE TITLE
Introduction of siconco in v01.00.10

### ISSUE THREAD

**Issue by matthew-mizielinski** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#182]
Martin,

I've just noticed the introduction of `siconco` in [v01.00.10](https://www.earthsystemcog.org/projects/wip/drq_release_01_00_10) of the data request to go alongside `siconc`. Could we have some expanded guidance added to the release notes to indicate when to use each?

As noted in #33, for HadGEM3 and UKESM1 we produce the sea ice concentration from the CICE sea-ice model on the tripolar ORCA ocean grids, but a few of our sea-ice variables are computed by the JULES land surface model, which uses the lat-lon grid used by the atmosphere model. We would therefore need to produce sea ice concentrations from JULES on the atmosphere grid in order to allow time-averaging of these variables. I guess that data on the ocean grid should go in `siconco` and data on the atmosphere in `siconc`, but the cell_methods and cell_measures of these two suggest the opposite (`siconco` relating to the atmosphere grid). Is this the correct interpretation?

This potentially raises a CMOR issue. Some variables, e.g. `SImon`/`sialb`, have cell_methods of the form `area: time: mean where sea_ice (comment: mask=siconc)`, so would the cell_methods validation within CMOR/PrePARE need to be flexible enough to allow `siconc` to be substituted with `siconco` as appropriate?

Thanks for raising this issue and looking at bringing in a parallel siconc variable -- we've been trying to work out how to use the grid_label components of the DRS to distinguish between the two siconc fields we will need to produce.

M

**Comment by jkettleb** [comment]
Could the `cell_methods` be simply `area: time:  mean where sea_ice`?  I know this looses a bit of information - but saves the complication of having to get the correct, model dependent, variable name into the `comment`.

**Comment by martinjuckes** [comment]
I'm sorry that we haven't got further with this. There are a number of sea ice variables which could be either on the ocean or the atmospheric grid ... in such cases the cell_measures attribute also needs to be adjusted. My problem is that I don't have a list of the variables affected, and making dual options for all sea-ice variable seems like overkill. The best solution may be to put in additional CMOR variables, e.g. there is a "sisali" which should be on the atmospheric grid with cell_measures areacella and siconc in the cell_methods string: I could add a CMORvar record with label "sisalio", cell_measures areacello and siconco in the cell_methods string, and the same `var` record (and hence the variable name `sisali` in the data file).  Can you give a list of variables affected?  (I'm afraid sialb has been dropped -- at Karl's request)

**Comment by matthew-mizielinski** [comment]
Apologies for the slow reply, I only found this when digging through old tickets.

`siu` and `siv` are two examples of CMOR variables in version 01.00.15 of the data request that have cell_methods of `area: time: mean where sea_ice (comment: mask=siconc)` but are going to be produced by HadGEM3 family models on the ocean grid, for which `mask=siconco` would be a more accurate description.

One solution I can think of is for CMOR3 to accept any string in the comment field and then modelling groups to sort this out themselves if they want to. Alternatively an additional global attribute could be added, but I think time may be against us here with many groups already processing data.

@jkettleb's simplification may be the easiest solution for now and we can look at this in more detail for CMIP7. Scientist analysing sea ice data will hopefully get some understanding of the weighting of sea ice variables from the SIMIP paper.

**Comment by martinjuckes** [comment]
Discussion continued in https://github.com/cmip6dr/CMIP6_DataRequest_VariableDefinitions/issues/245
