### ISSUE TITLE
`mmrdust` dimensions in two different tables

### ISSUE THREAD

**Issue by matthew-mizielinski** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#183]
The variable [mmrdust](http://clipc-services.ceda.ac.uk/dreq/u/dcecb293537e640a0bfc8f88a92967fe.html) appears in two tables with different dimensions;
 * AERmon: global field on atmospheric levels (requested by AerChemMIP, CFMIP, GeoMIP, RFMIP)
 * Emon: global field on a single level (requested by PMIP)

Is the latter intended to be a vertical integral, a specific model level, or a near surface field? Or is it intended to only be produced by models with a 2d aerosol model? I guess this is a question for the PMIP leads if this is not an error.

M

**Comment by StephanieWoodward** [comment]
I have confirmation from a PMIP lead that the Emon request can be deleted.  What is wanted is the global field on all levels, as already specified in the AERmon request.

**Comment by martinjuckes** [comment]
Thanks, I'll make these changes for 01.00.11
