### ISSUE TITLE
"mrro" and "snw" should be in "Eday" table and not "day" table

### ISSUE THREAD

**Issue by svalcke** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#184]
Hi,
I think "mrro" and "snw" should be in "Eday" table and not "day" table.
cmor https://github.com/PCMDI/cmor/tree/master/TestTables has "mrro" and "snw" in "Eday" table and not "day" table.

**Comment by martinjuckes** [comment]
I think this was a delay in the cmor tables adopting a change introduced in the data request. The MCOR tables are generated from the data request, so should follow what is done there.
