### ISSUE TITLE
Wrong cell_methods for clisccp in E3hr

### ISSUE THREAD

**Issue by alejandrobodas** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#186]
Currently, the 3-hourly request of _clisscp_ has cell_metods _time:mean_, which places this variable in the E3hr mip table. The request is for instantaneous data, so the cell_methods should be _time:point_. That should move this instance of _clisccp_ to E3hrPt.

**Comment by martinjuckes** [comment]
There is a request from HighResMIP for this as a time mean variable ... I'll check with them ... but the CFMIP request should be time: point.

**Comment by martinjuckes** [comment]
Comment from Mark Webb (be email): Just to clarify, the instantaneous 3 hourly ISCCP simulator outputs
required for CFMIP are just for one year in the AMIP experiment. 
These are there for simulator testing.

I don't know what the 3 hourly highresmip ISCCP simlator outputs are
requested for, but if it's for comparison with ISCCP retrievals, then
3 hourly means might indeed be more appropriate.

**Comment by martinjuckes** [comment]
Confirmed that HighResMIP also want 3hr instantaneous data (email from Malcolm Roberts)
