### ISSUE TITLE
Wrong dimensions in jpdftaureliqmodis and jpdftaureicemodis

### ISSUE THREAD

**Issue by alejandrobodas** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#187]
Currently, these variables contain the dimension **plev7c**, which is not correct. Also, the instance of **jpdftaureicemodis** in table **Eday** has dimension **effectRadLi**, which should be **effectRadIc**. In summary, the correct dimensions of these variables should be:

- jpdftaureliqmodis: longitude latitude  effectRadLi tau time[or time1]
- jpdftaureicemodis: longitude latitude effectRadIc tau time[or time1]

**Comment by martinjuckes** [comment]
Corrected for 01.00.11

**Comment by alejandrobodas** [comment]
Fantastic. Thanks Martin.
