### ISSUE TITLE
01.00.10 h2o AERMon incorrect 'title'

### ISSUE THREAD

**Issue by jkettleb** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#188]
h2o AERMon currently has the title: 'Water vapour volume mixing ratio', but its standard name is:
http://clipc-services.ceda.ac.uk/dreq/u/mass_fraction_of_water_in_air.html

I think the title should be: 'Mass Fraction of Water'.

We intend to set our runs going assuming this is a mass fraction rather than a volume mixing ratio.

**Comment by martinjuckes** [comment]
Agreed and corrected.
