### ISSUE TITLE
v01.00.10: cell_methods in some extensive SIMIP variables

### ISSUE THREAD

**Issue by matthew-mizielinski** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#189]
Following a review of our sea-ice mappings by @alex-west-met-office looking at v01.00.10 a few minor issues with the cell methods have been identified:

Example variable: `SImon/siflcondbot`: 
cell methods (current): `area: time: mean where sea_ice (comment: mask=siconc)`
suggested change to: `area: time: mean`
Defined as ‘total diffusive energy flux to ice base divided by grid cell area’, this variable goes to zero naturally as ice area goes to zero, so is _extensive_ by the SIMIP definition and should be calculated by a simple time mean.  It is not clear that it is ‘masked’ (or weighted) by ice area in any meaningful sense – it’s just zero where there’s no ice, quite naturally.

Similar reasons hold for the following variables, all of which are defined as energy/mass fluxes to or from sea ice divided by grid cell area, so they scale naturally with ice area and require no masking or weighting.

Variables affected; `siflcondtop`, `siflfwbot`, `siflfwdrain`, `sifllatstop`, `sifllwdtop`, `sifllwutop`, `siflsaltbot`, `siflsenstop`, `siflsensupbot`, `siflswdbot`, `siflswutop`,  `siflswdtop`, `sipr`

**Comment by martinjuckes** [comment]
The definition is NOT that all variables which naturally go to zero must be treated as extensive. SIMIP wants sea ice variables, where possible, to be averaged in a way which gives a result which is representative of the values on the ice. This means that they have adopted the masked mean in many cases where it would be possible to use an unmasked mean. They believe that it will be easier to analyse and verify the data if diagnostics of ice properties are masked by ice area.

**Comment by alex-west-met-office** [comment]
Hi Martin,

Can you confirm that 'masked by ice area' in the case of the fluxes listed above does mean only that, and not 'weighted by ice area'?

Alex

**Comment by alex-west-met-office** [comment]
To expand on why *weighting* these variables by sea ice area would not be a very good idea:

Take sipr, rainfall rate over sea ice. This is defined in the SIMIP paper as ‘Mass of liquid precipitation falling onto sea ice divided by grid-cell area.’ Suppose you have 

-	a grid cell of area 10^9 m2; 
-	timestep length 1s (for simplicity)
-	that 2*10^9 kg rainfall falls onto sea ice during timestep 1, during which the sea ice fraction is 50%
-	and that 4*10^9 kg rainfall falls onto sea ice during timestep 2, during which the sea ice fraction is 100%

Under the SIMIP definition, the values calculated at each timestep would be 2. and 4. kg m-2 s-1 respectively. The total rain that has fallen onto sea ice during the period is 6*10^9 kg, equivalent to a flux of 3. Kg m-2, the simple time mean of the two values; an ice-area weighted mean gives (2 * .5 + 3. * 1.) / (.5 + 1.) = 2.67 kg m-2, which isn’t a representative answer.

The same reasoning applies to any flux that is defined as the total value of some quantity passing to or from sea ice, divided by grid cell area.

Of course if the intention is only to mask, and not weight, there’s no issue, and I’m sorry for wasting your time if so.

**Comment by martinjuckes** [comment]
The definition in the Data Request is in this case not the same as in the SIMIP paper. The definition in the data request is masked and weighted by the sea ice area. See https://www.earthsystemcog.org/projects/wip/time_averages for more background about how masking and weighting are defined in the metadata.
