### ISSUE TITLE
wap is missing positive

### ISSUE THREAD

**Issue by jonseddon** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#192]
Hi, wap includes in its description `(positive down)` but positive is set to none where wap is used in all of the tables. Is the description or positive value incorrect?

Thanks,

Jon

**Comment by martinjuckes** [comment]
I believe that it is correct, as in CMIP5, to leave the `positive` attribute blank in this case, but perhaps Karl (@taylor13) can confirm: the `positive` attribute should be used when a CF standard name has two valid sign conventions, as is the case for may vertical fluxes. In such cases, the standard name alone is ambiguous. The Lagrangian pressure tendency, on the other hand, only has one valid sign convention (positive values should be used for a positive pressure tendency). The comment in the description is there to avoid any confusion, even though in this case the standard name is not ambiguous.

**Comment by taylor13** [comment]
Yes, Martin is entirely correct.

**Comment by jonseddon** [comment]
Brilliant, thanks for clarifying that.
