### ISSUE TITLE
1.00.10 Eday prhmax incorrect cell_methods?

### ISSUE THREAD

**Issue by jkettleb** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#193]
Could you check the cell_methods on Eday prhmax - I think the cell_methods should be `area: mean time: mean within hours time: maximum over hours` to make them consistent with other tables prhmax. (they are currently `area: time: mean`

**Comment by martinjuckes** [comment]
OK, should be fixed in 01.00.12

**Comment by jkettleb** [comment]
thanks Martin

**Comment by aearamos** [comment]
Hi, @martinjuckes.

Sorry to reopen an old issue, but  I was wondering if you know how to output prhmax from the ifs grib codes. I know it doesn't output prhmax directly, but I could use some other variables to generate it. 

Thanks

**Comment by martinjuckes** [comment]
Sorry @aearamos , I don't know about GRIB code --> data request conversions. If you have an hourly mean precipitation rate, you will need to evaluate the maximum over the relevant time period specified by the frequency. If you don't have the hourly mean then I think we have to accept that you can't provide this variable.
