### ISSUE TITLE
hfx and hfy - Should these be 2D or 3D

### ISSUE THREAD

**Issue by TimGraham1982** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#197]
In the OMIP paper hfx and hfy are listed as 2D variables but in the data request they are 3D. Can you clarify which is correct?

**Comment by StephenGriffies** [comment]
Thanks for your careful considerations.   

--As requested for OMIP as per Griffies et al (2016), hfx and hfy are depth integrated 2d horizontal fields.  I see more routine diagnostically use with the depth integrated fields than their three dimensional versions.  We also save on the CMIP6 archive relative to the CMIP5 request (which asked for the full 3d field). 

--I recommend we stick to the Griffies et al (2016) request for depth integrated diagnostics.  The data request asking for 3d fields must be an artefact of the CMIP5 request.  

Stephen Griffies

**Comment by durack1** [comment]
Ok folks, so we need to update a number of the sheet entries - for reference see the Physics Omon sheet: https://goo.gl/Rhrcwp
**OLD**

| line | Comment | Questions&Notes | output variable name | CMOR dimensions |
|:---|:---:|:---:|:---:|:---:|
| 60 | Contains all contributions to "x-ward" heat transport from resolved and parameterized processes. Use Celsius for temperature scale | 3d field for CMIP6. Report on native horizontal grid. Online mapping to depth/pressure vertical grid if depth or pressure are not native | hfx | longitude latitude olevel time |
| 61 | Contains all contributions to "y-ward" heat transport from resolved and parameterized processes. Use Celsius for temperature scale | 3d field for CMIP6. Report on native horizontal grid. Online mapping to depth/pressure vertical grid if depth or pressure are not native | hfy | longitude latitude olevel time |

**NEW**

| line | Comment | Questions&Notes | output variable name | CMOR dimensions |
|:---|:---:|:---:|:---:|:---:|
| 60 | Contains all depth-integrated contributions to "x-ward" heat transport from resolved and parameterized processes. Use Celsius for temperature scale | 2d field for CMIP6. Report on native horizontal grid. Online integration from depth/pressure vertical grid | hfx | longitude latitude time |
| 61 | Contains all contributions to "y-ward" heat transport from resolved and parameterized processes. Use Celsius for temperature scale | 2d field for CMIP6. Report on native horizontal grid. Online integration from depth/pressure vertical grid | hfy | longitude latitude time |

@StephenGriffies are you happy with these amendments - or would you like to tweak these?

**Comment by StephenGriffies** [comment]
The suggested change makes the diagnostic consistent with the Griffies et al (2016) OMIP paper. I support making the change so that we move away from 3d vectors to depth-integrated 2d vectors for the heat transports. 

Thanks for pushing this forward.

**Comment by StephenGriffies** [comment]
No tweaks needed.  Thanks.

**Comment by durack1** [comment]
@martinjuckes @StephenGriffies this change has been implemented (see https://goo.gl/Rhrcwp).

@martinjuckes please close this issue.

**Comment by martinjuckes** [comment]
Fixed in data request 01.00.16
