### ISSUE TITLE
01.00.11 ERROR: experiment label duplicated: dcppC-forecast-addPinatubo

### ISSUE THREAD

**Issue by SebastienDenvil** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#198]
from dreqPy import dreq
dq = dreq.loadDreq()
from dreqPy.scope import dreqQuery
sc = dreqQuery(dq=dq, tierMax=3)

ERROR: experiment label duplicated: dcppC-forecast-addPinatubo

**Comment by senesis** [comment]
already reported as :  https://github.com/cmip6dr/dreqPy/issues/13
