### ISSUE TITLE
v1.0.11 : dimensions 'olevel', 'alevel', 'alevhalf' and 'typeresidual' have no standard name

### ISSUE THREAD

**Issue by senesis** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#199]
... while model_level_number seems to fit the first two, and maybe the third, too

**Comment by martinjuckes** [comment]
The "olevel", "alevel", "alevhalf" entries indicate that the model vertical coordinates should be used. A standard name is not required by the CF Convention, but could be added if possible. "model_level_number" may be appropriate, or "atmosphere_sigma_coordinate". The options are not listed in the CMOR tables.

For "typeresidual" I do not believe that there are any valid standard_name options, so the dimension variable should not carry a standard_name attribute.

**Comment by martinjuckes** [comment]
I'll add a comment in the `description` attributes.
