### ISSUE TITLE
CFMIP sites : where is the reference list for location and indices ?

### ISSUE THREAD

**Issue by senesis** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#200]
According to http://clipc-services.ceda.ac.uk/dreq/u/63c0a932-15f2-11e7-87e0-5404a60d96b5.html , the title for str-d09 is  

> Instantaneous value (i.e. synoptic or time-step value), Site (129 specified sites) [S-na] [apt-tpt]

But 
1- this refers to dimension dim:site (see http://clipc-services.ceda.ac.uk/dreq/u/dim:site.html) which title is 

> an integer assigned to each of 119 stations (standard) and 73 stations (aquaplanet)

2- and the supplement material to the GMD paper about CFMIP does list 121 sites in file cmip6-cfsites-locations.txt

So, which is the reference information location ?

**Comment by senesis** [comment]
Here is a copy of a similar request on the Data Request mailing list  by "Sheri Mickelson" <mickelso@UCAR.EDU>: 
I was wondering if someone would be able to help clarify the "site" dimension within the data request.  Based on its description within the request, the number of sites seems to be in flux changing from 119, 121, 129, and now it looks like it's back to 119 stations.  Have the station locations been finalized?  Or are they still being determined?

I was also wondering if it is possible to query the data request to find the specific site locations that are needed (ie. lat, lon values)?  Or if it isn't, will this be an option in the future?

Thanks,
Sheri

**Comment by senesis** [comment]
And Karl Taylor's answer:

Hi Sheri,

In CMIP5 there were 120 sites and their coordinates were listed here:
http://cfmip.metoffice.com/cfmip2/pointlocations.txt  . Actually for
aquaplanet experiments there were only 73 sites (listed at the end of
the same file).

For CMIP6, they indicate on the CFMIP GMD paper
(http://www.geosci-model-dev.net/10/359/2017/gmd-10-359-2017.pdf) that
they request output at 121 locations and that "A text file containing
the list of locations is avail-
able in the Supplement and on the CFMIP website; these are also
presented graphically in Fig. 2."  They no longer request output from
aquaplanet experiments.

I found the updated list in the GMD supplementary material
(http://www.geosci-model-dev.net/10/359/2017/gmd-10-359-2017-supplement.zip
as a text file), but not on the CFMIP website.  The list contains 121
locations so I'm guessing that's the correct number.

best regards,
Karl

**Comment by taylor13** [comment]
thanks, @senesis , for transferring the discussion here.
cheers,
Karl

**Comment by martinjuckes** [comment]
Yes, I have an email from Mark Webb .. 121 is the correct number:
> Dear Martin, cc Karl,
> 
> Thanks for the fixes to the CFMIP data request which you've
> incorporated into the latest release.
> 
> I'm afraid I've spotted another minor issue:
> 
> A number of the variables requested in MIP table CFsubhr 
> (mainly 2D ones I think) are listed as having 129 
> site locations - see:
> 
> http://clipc-services.ceda.ac.uk/dreq/u/MIPtable::CFsubhr.html
> 
> Actually there are 121 cfsites locations requested by CFMIP in CMIP6.
> 
> I see that many of the 3D variables are listed as 'at specified sites'.
> That would be fine for the 2D variables.  I don't think that we need
> to specify the number of locations.  That's all covered in the CFMIP
> paper.
> 
> Also it would be possible to change the description of this MIP 
> table and the associated variable groups to something a bit more
> informative?  
> 
> Rather than
> 
> 'Diagnostics for cloud forcing analysis at specific sites'
> 
> I would propose:
> 
> CFMIP instantaneous high-frequency "cfSites" outputs at specific sites
> 
> Many thanks,
> Mark
I'll fix this in the next update.

I could also add the locations into the grids section.

**Comment by senesis** [comment]
In my opinion, it is not necessary that the DR content includes site locations. Providing the link is enough (except if the PrePare QC software was turned to also checking that grid)

**Comment by martinjuckes** [comment]
I've added the locations in a "remarks" record -- not necessary, perhaps, but potentially useful. I hade thought of putting them in as auxillary coordinates, but that won't work because they are not organised as a monotonic sequence (required by CF). I'll also add the link to the description of the site index dimension.

**Comment by taylor13** [comment]
I think that will be satisfactory for CMOR and PrePARE

**Comment by martinjuckes** [comment]
OK, this is done for the next release ... I'll close the issue.
