### ISSUE TITLE
table CFsubhr has mixed frequencies (it includes fixed fields latitude and longitude)

### ISSUE THREAD

**Issue by senesis** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#203]
See http://clipc-services.ceda.ac.uk/dreq/u/MIPtable::CFsubhr.html
As far as I remember, mixed frequencies shouldn't occur in a single table

**Comment by martinjuckes** [comment]
The only two fixed variables are, I hope, latitude and longitude ... which are ancillary variables.  This problem is also discussed here: https://github.com/cmip6dr/cmip7_forward_look/issues/6 ... I was hoping we could defer any solution until CMIP7 .. it probably needs a tweak to the schema.

**Comment by senesis** [comment]
As far as CNRM-CM's workflow is concerned, there is no need for a change in DR content for CMIP6; tweaking is quite easy downstream

**Comment by martinjuckes** [comment]
OK .. thanks for the understanding.
