### ISSUE TITLE
some climatology methods are not fully defined by the DR

### ISSUE THREAD

**Issue by senesis** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#204]
Among this few methods :
   - area: mean time: maximum within days time: mean over days [dmax]: Daily Maximum {1/2}
   - area: mean time: mean within hours time: maximum over hours [am-tmh]: Maximum Hourly Rate {1/3}
   - area: mean time: mean within days time: mean over days [amn-tdnl]: Mean Diurnal Cycle {1/5}
   - area: mean time: mean within years time: mean over years [aclim]: Annual Climatology {6/43}

 number 1 and number 2  are unambiguous, while the last two does not really describe what is expected, as e.g. 

  - what is the expected time resolution of the diurnal cycle
  - does "annual climatology" means 'annual cycle', and if yes, with which time resolution (day ? decade ? month ?)

Is there more documentation available ?

**Comment by martinjuckes** [comment]
The documentation is the CF Convention, eg. example 7.11 for `time: mean within days time: mean over days` .  The cell_methods string has all the information which can be put into it. The answer to your question may be different for different frequencies. 
For the diurnal cycle, the frequency is always "1hrClimMon" which means hourly data averaged over each month (i.e. 24 hourly values for January 1850, etc ).
The annual climatology with frequency "monClim" means averaged over all requested years and for each month .. so there should be 12 monthly values. I noticed two variables with frequency mon, which is an error and will be changed to monClim in 01.00.14
The daily maximum occurs with frequency "mon" .. so it is a monthly mean of the daily maximum. 

I've also added some clarification in the MIP table descriptions.

**Comment by senesis** [comment]
Thanks. So the general rule looks like : when "time: mean within days time: mean over days" is applied to frequency "<period1>Clim<period2>":
- period1 is the time resolution for "time: mean within days"
- period2 is the averaging period for "time: mean over days"; 
- when period2 is missing in the frequency  label (such as in monClim), it is specified 'somewhere else';  but : is it implicitly the whole experiment duration, or is there an attribute somewhere else for that ?

**Comment by martinjuckes** [comment]
"Clim" is not a frequency. The cell_methods string does not specify the 2nd period. For 1hrClimMon the 2nd period is a month. For monClim, the avergaing period should be all the years requested. In some cases 'monClim' is used to request parameters which are prescribed in the model with no interannual variation, in which case it is just the prescribed annual cycle that is wanted.
