### ISSUE TITLE
prra Eday, inconsistent title and cell_methods

### ISSUE THREAD

**Issue by jkettleb** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#207]
The title for prra (http://clipc-services.ceda.ac.uk/dreq/u/d227fb60-4a9f-11e6-b84e-ac72891c3257.html) is 'Rainfall Flux where Ice Free Ocean over Sea', but cell_methods 
)http://clipc-services.ceda.ac.uk/dreq/u/f7de23aa-562c-11e6-a2a4-ac72891c3257.html) are: area: mean where land time: mean.

We think the cell_methods are correct as this is an LS3MIP diagnostic.  Is that right? (we are setting runs going assuming it is...)

**Comment by jkettleb** [comment]
sorry - its prra in E3hr too.

**Comment by martinjuckes** [comment]
OK, names corrected in 01.00.15
