### ISSUE TITLE
Emon sfcWindmax cell_methods - could you check?

### ISSUE THREAD

**Issue by jkettleb** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#209]
The Emon sfcWindmax variable has cell_methods of `area: mean time:mean`.  Should this be `area: mean time: maximum within days time: mean over days`?  (e.g. similar to Amon tasmx)

**Comment by martinjuckes** [comment]
Yes -- should be fixed in next version/

**Comment by martinjuckes** [comment]
Left out in 01.00.14, but will be in 01.00.15
