### ISSUE TITLE
Emon hus - which set of pressure levels?

### ISSUE THREAD

**Issue by jkettleb** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#210]
Talking to Malcolm Roberts from HighResMIP we think Emon hus should be on plev7h rather than plev7c - do you agree, or has someone else requested it as plev7c?

**Comment by jkettleb** [comment]
We intend to set up our runs assuming its plev7h - please shout if this is wrong.

**Comment by martinjuckes** [comment]
@jkettleb Yes ... and please note that ua and va should also be request on the same levels as hus, as monthly means.

**Comment by senesis** [comment]
We, at CNRM and IPSL, setup our runs using the DR content and can hardly incorporate adhoc tricks for dealing with DR version shortcomings by parsing every comment posted on this issue tracking system

**Comment by martinjuckes** [comment]
Hi @senesis .. sorry .. but corrections wont be in place before the next version ....

**Comment by senesis** [comment]
Thanks Martin. I am not expecting everything to be clean at once. But I would welcome your expert advice on these questions : 
  - where are the remaining weaknesses (or your guess of -) ?
  - when will timeslices be clean, i) for control , ii) for Deck , iii) for the whole of experiments
  - when do you plan to release 01.00.14 ?
  - is it safe to use pending standard names, w.r.t. to the downstream checks at publication stage ?
  - because publication stage checks cannot deal will the whole set of DR versions, but only a subset of, is there any agreement on which they are, and which is next to be released (and when)

**Comment by martinjuckes** [comment]
Main weaknesses are standard names;
There are some issues with the OMIP request ... I'll try to go over that on Tuesday;
I hope to release 01.00.14 on Tuesday;
I'm not sure of the policy on pending standard names I'm afraid ... it will be easier, of course, if they get accepted without change. 
I'm not sure why publication checks can only handle a limited number of DR versions ... when this started I assumed that the software would be capable of handling multiple versions, using the version identifier in the file -- I'm afraid I don't know what decisions are being taken there.

**Comment by jkettleb** [comment]
thanks Martin - I think monthly ua7h, va7h may have been deleted in an earlier version of the data request?

I'll add them into our model diagnostic setup with hus on plev7h.

**Comment by martinjuckes** [comment]
Thanks .. they are added back in 01.00.14

**Comment by jkettleb** [comment]
I can't find ua7h, va7h at monthly frequency at 1.00.15.  Do you know whether these diagnostics are still required?  If required which MIP(s) are requesting them?

**Comment by jkettleb** [comment]
Do you know whether ua7h, va7h re requested at monthly frequency?  (I can't reopen this ticket - but hope you are still getting notification of comments like this)

**Comment by martinjuckes** [comment]
Sorry, they have been changed to just ua, va in Emon: http://clipc-services.ceda.ac.uk/dreq/u/ca7f7ade-6e00-11e7-9fbe-5404a60d96b5.html , http://clipc-services.ceda.ac.uk/dreq/u/cad8979a-6e00-11e7-9fbe-5404a60d96b5.html

**Comment by jkettleb** [comment]
thanks Martin - could I have worked that out, easily, without having to ask you? (In case something like this happens again in the future)

**Comment by martinjuckes** [comment]
Hi Jamie, this variable was requested as part of a group which HighResMIP wanted .. so you could look at that variable group: http://clipc-services.ceda.ac.uk/dreq/u/efc08076-5629-11e6-9079-ac72891c3257.html . The usage of variable groups is more mixed than I'd hoped, but they can be used to track related groups of variables.
