### ISSUE TITLE
Should evspsbl have a positive direction specified?

### ISSUE THREAD

**Issue by cdr30** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#214]
From the description it is clear that evaporation is an upwards flux, but it is not specified in the "positive" attribute. Without this attribute, CMOR will not  automatically change the sign of data that is specified with the opposite sign.

**Comment by martinjuckes** [comment]
In general, I think "positive" is set when the CF Standard Name allows two possible sign conventions. In the case of evspbl, the standard name definition includes the comment "Evaporation is the conversion of liquid or solid into vapor", so the flux direction is specified implicitly. I'll check with the CMOR team .. see CMOR issues link above.

**Comment by martinjuckes** [comment]
Set to up in 01.00.16 (also clarification of help note on `positive` attribute of CMORvar record -- http://clipc-services.ceda.ac.uk/dreq/u/ATTRIBUTE::CMORvar.positive.html )
