### ISSUE TITLE
expcfe and expfe

### ISSUE THREAD

**Issue by dnadeau4** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#216]
There are two variable names in use for the CF 'sinking_mole_flux_of_particulate_iron_in_sea_water':
Emon: expcfe
Oyr: expfe
I guess that there is a typo in the Emon table and it should be also 'expfe'.

**Comment by dnadeau4** [comment]
https://github.com/PCMDI/cmip6-cmor-tables/issues/69

**Comment by martinjuckes** [comment]
Thanks, typo fixed.
