### ISSUE TITLE
Incorrectly named variables?

### ISSUE THREAD

**Issue by ehogan** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#219]
I was wondering whether `od443dust` should be named `od440dust` for consistency with `od440aer`?

In a similar fashion, should `od865dust` be named `od870dust` for consistency with `od870aer`?

**Comment by martinjuckes** [comment]
@jypeter The optical depth variables `od443dust` and `od865dust` requested by PMIP are slightly different from the AERmon variables `od440dust`, `od860dust`: can we change them to be the same, or is there a reason for this difference?

**Comment by martinjuckes** [comment]
resolved to 443, 550 and 865.

**Comment by martinjuckes** [comment]
Unfortunately this did not get resolved as expected, so the variable names remain with this inconsistency -- and the deadline for modifications has passed. Should be fixed in the future - see https://github.com/cmip6dr/cmip7_forward_look/issues/26
