### ISSUE TITLE
Different dimensions for a variable in different MIP tables

### ISSUE THREAD

**Issue by ehogan** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#220]
All the [phalf](http://clipc-services.ceda.ac.uk/dreq/u/154ab10964742eaff37de9cc5beef39c.html) variables have the title "Pressure on Model Half-Levels" and dimensions containing `alevhalf` except for AERmon, which has the title "air pressure at interfaces" and dimensions containing `alevel`.

The same is true for `rsdcs` and `rsucs` (`E3hrPt` differs in both cases) .

**Comment by martinjuckes** [comment]
Thanks, fixed in 01.00.15.

**Comment by ehogan** [comment]
Thanks @martinjuckes! :)
