### ISSUE TITLE
Should lwtoacs be renamed lwtoacsdust?

### ISSUE THREAD

**Issue by ehogan** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#221]
Should [lwtoacs](http://clipc-services.ceda.ac.uk/dreq/u/59134bf6-9e49-11e5-803c-0d0b866b59f3.html) (Clear-sky TOA Longwave radiative flux due to Dust) be renamed `lwtoacsdust` for consistency with [lwtoacsaer](http://clipc-services.ceda.ac.uk/dreq/u/ab57604d6acd918c08aa6252145c608e.html) (Clear Sky LongWave Radiative Forcing due to Aerosols at TOA) and [lwtoaasdust](http://clipc-services.ceda.ac.uk/dreq/u/f9f66ff437154f86913937f9e2d9a26d.html) (All Sky Longwave Radiative Forcing due to Dust at TOA)? Should the title and standard name also be updated?

**Comment by martinjuckes** [comment]
short and long name updated in 01.00.17
