### ISSUE TITLE
v01.00.14: bug in long name of Lmon/c3PftFrac

### ISSUE THREAD

**Issue by matthew-mizielinski** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#222]
Long name of Lmon/c3PftFrac replaced with an unconnected standard name at 01.00.14:

http://clipc-services.ceda.ac.uk/dreq/u/2ca96cd5a4e83feb0d493bf9aa1a5b59.html

Previously was 'Percentage Cover by C3 Plant Functional Type'

**Comment by martinjuckes** [comment]
Fixed in 01.00.16
