### ISSUE TITLE
wrong title for str-359; should read 'global mean' rather than 'global field' (or cell method is wrong)

### ISSUE THREAD

**Issue by senesis** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#225]
The dimensions object at  http://clipc-services.ceda.ac.uk/dreq/u/f7eca81c-562c-11e6-a2a4-ac72891c3257.html has title : 
   Instantaneous value (i.e. synoptic or time-step value), Global field (single level) [XY-na] {sza5:}
while its cell method has title:
   Cell Methods: [gmn-tpt] Global Mean

**Comment by martinjuckes** [comment]
Cell methods is wrong. Corrected to "area: mean time: point" in 01.00.16
