### ISSUE TITLE
mmraerso4 and mmrso4 are two names for the same variable (or one title is wrong)

### ISSUE THREAD

**Issue by senesis** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#228]
Both variables refer to the same standard name, and have the same title; the first one, defined in AERmon, has shape XY-na while the second, in Emon, has shape XY-A; however, there is no indication that the first one is a vertical integration. 
So there is a need for clarification or simplification

**Comment by martinjuckes** [comment]
mmraerso4 removed ... in 01.00.16
