### ISSUE TITLE
120 requestItems have an unset esid

### ISSUE THREAD

**Issue by senesis** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#229]
All requestItems listed below have esid=remarks. Does it mean that they do not apply to any experiment ?

ISMIP6, ISMIP6-OmonNew, SSP5-85-01 		  uid=94040a18-267c-11e7-8933-ac72891c3257 
ISMIP6, ISMIP6-OmonNew, ISMP6-5 		  uid=94040298-267c-11e7-8933-ac72891c3257 
ISMIP6, ISMIP6-OmonNew, ISMP6-4 		  uid=9403ffb4-267c-11e7-8933-ac72891c3257 
ISMIP6, ISMIP6-OmonNew, ISMP6-6 		  uid=940404f0-267c-11e7-8933-ac72891c3257 
ISMIP6, ISMIP6-OmonNew, lgm127k 		  uid=94040752-267c-11e7-8933-ac72891c3257 
GeoMIP, Amon, ScenarioMIP-1 			  uid=93fee844-267c-11e7-8933-ac72891c3257 
GeoMIP, Amon, ScenarioMIP-3 			  uid=93feea92-267c-11e7-8933-ac72891c3257 
PMIP, PMIP.Lmon, HistNolulccLnd 		  uid=940b58ea-267c-11e7-8933-ac72891c3257 
PMIP, PMIP.Lmon, HistNolulcc01 			  uid=940b5b60-267c-11e7-8933-ac72891c3257 
PMIP, PMIP.Lmon, IdealizedRegDeforest 		  uid=940b5674-267c-11e7-8933-ac72891c3257 
PMIP, PMIP.Lmon, EsmhistbgcNolulcc 		  uid=940b5e26-267c-11e7-8933-ac72891c3257 
PMIP, PMIP.Lmon, IdealizedGlobalDeforest 	  uid=940b53e0-267c-11e7-8933-ac72891c3257 
GeoMIP, Emon-subset-01, ScenarioMIP-1 		  uid=94000c24-267c-11e7-8933-ac72891c3257 
GeoMIP, Emon-subset-01, ScenarioMIP-3 		  uid=94000e90-267c-11e7-8933-ac72891c3257 
DAMIP, DAMIP-AERmon, DAMIP-1 			  uid=93f8fc40-267c-11e7-8933-ac72891c3257 
DAMIP, DAMIP-AERmon, ssp245 			  uid=93f907e4-267c-11e7-8933-ac72891c3257 
ISMIP6, ISMIP6-fxNew, ISMP6-6 			  uid=940437a4-267c-11e7-8933-ac72891c3257 
ISMIP6, ISMIP6-fxNew, lgm127k 			  uid=94043a24-267c-11e7-8933-ac72891c3257 
ISMIP6, ISMIP6-fxNew, ISMP6-4 			  uid=94043182-267c-11e7-8933-ac72891c3257 
ISMIP6, ISMIP6-fxNew, SSP5-85-01 		  uid=94043d30-267c-11e7-8933-ac72891c3257 
ISMIP6, ISMIP6-fxNew, ISMP6-5 			  uid=94043452-267c-11e7-8933-ac72891c3257 
GeoMIP, AERmon-subset-02, ScenarioMIP-3 	  uid=93fdf920-267c-11e7-8933-ac72891c3257 
GeoMIP, AERmon-subset-02, ScenarioMIP-1 	  uid=93fdf6be-267c-11e7-8933-ac72891c3257 
DAMIP, DAMIP-3hr-p2, DAMIP-1 			  uid=93fa4e74-267c-11e7-8933-ac72891c3257 
DAMIP, CFmon-3dstd, DAMIP-1 			  uid=93f85b64-267c-11e7-8933-ac72891c3257 
GeoMIP, Omon, ScenarioMIP-3 			  uid=93ff8ccc-267c-11e7-8933-ac72891c3257 
GeoMIP, Omon, ScenarioMIP-1 			  uid=93ff8a7e-267c-11e7-8933-ac72891c3257 
ISMIP6, ISMIP6.IfxGre, ISMP6-7 			  uid=94035fa0-267c-11e7-8933-ac72891c3257 
ISMIP6, ISMIP6.IfxGre, lgm127k 			  uid=9403627a-267c-11e7-8933-ac72891c3257 
ISMIP6, ISMIP6.IfxGre, ISMP6-4 			  uid=940355a0-267c-11e7-8933-ac72891c3257 
ISMIP6, ISMIP6.IfxGre, ISMP6-6 			  uid=94035cc6-267c-11e7-8933-ac72891c3257 
ISMIP6, ISMIP6.IfxGre, SSP5-85-01 		  uid=94036504-267c-11e7-8933-ac72891c3257 
ISMIP6, ISMIP6.IfxGre, ISMP6-5 			  uid=940359d8-267c-11e7-8933-ac72891c3257 
GeoMIP, LImon, ScenarioMIP-1 			  uid=93ff60c6-267c-11e7-8933-ac72891c3257 
GeoMIP, LImon, ScenarioMIP-3 			  uid=93ff63a0-267c-11e7-8933-ac72891c3257 
DAMIP, DAMIP-day, DAMIP-1 			  uid=93f98bf6-267c-11e7-8933-ac72891c3257 
DAMIP, DAMIP-day-zm, DAMIP-1 			  uid=93f9b8e2-267c-11e7-8933-ac72891c3257 
DAMIP, DAMIP-day-zm, ssp245 			  uid=93f9c486-267c-11e7-8933-ac72891c3257 
ISMIP6, ISMIP6.IyrAnt, ISMP6-7 			  uid=94047ae8-267c-11e7-8933-ac72891c3257 
ISMIP6, ISMIP6.IyrAnt, ISMP6-4 			  uid=94047390-267c-11e7-8933-ac72891c3257 
ISMIP6, ISMIP6.IyrAnt, ISMP6-5 			  uid=94047638-267c-11e7-8933-ac72891c3257 
ISMIP6, ISMIP6.IyrAnt, ISMP6-6 			  uid=94047890-267c-11e7-8933-ac72891c3257 
GeoMIP, Oclim-subset-01, ScenarioMIP-1 		  uid=93ff11ca-267c-11e7-8933-ac72891c3257 
GeoMIP, Oclim-subset-01, ScenarioMIP-3 		  uid=93ff1486-267c-11e7-8933-ac72891c3257 
ISMIP6, ISMIP6.Amon, ISMP6-5 			  uid=94038e26-267c-11e7-8933-ac72891c3257 
ISMIP6, ISMIP6.Amon, ISMP6-4 			  uid=94038b88-267c-11e7-8933-ac72891c3257 
ISMIP6, ISMIP6.Amon, SSP5-85-01 		  uid=940395f6-267c-11e7-8933-ac72891c3257 
ISMIP6, ISMIP6.Amon, ISMP6-6 			  uid=940390c4-267c-11e7-8933-ac72891c3257 
ISMIP6, ISMIP6.Amon, lgm127k 			  uid=94039326-267c-11e7-8933-ac72891c3257 
GeoMIP, CF3hr-subset, ScenarioMIP-3 		  uid=93fe21fc-267c-11e7-8933-ac72891c3257 
GeoMIP, CF3hr-subset, ScenarioMIP-1 		  uid=93fe1ee6-267c-11e7-8933-ac72891c3257 
DAMIP, LImon, DAMIP-1 				  uid=93f87f18-267c-11e7-8933-ac72891c3257 
DAMIP, day-ss, DAMIP-1 				  uid=93f7ea44-267c-11e7-8933-ac72891c3257 
GeoMIP, Oyr, ScenarioMIP-3 			  uid=93fe9916-267c-11e7-8933-ac72891c3257 
GeoMIP, Oyr, ScenarioMIP-1 			  uid=93fe96b4-267c-11e7-8933-ac72891c3257 
DAMIP, AERmon-3d, DAMIP-1 			  uid=93f9424a-267c-11e7-8933-ac72891c3257 
ISMIP6, ISMIP6.IyrGre, ISMP6-4 			  uid=9403d3a4-267c-11e7-8933-ac72891c3257 
ISMIP6, ISMIP6.IyrGre, ISMP6-5 			  uid=9403d6f6-267c-11e7-8933-ac72891c3257 
ISMIP6, ISMIP6.IyrGre, ISMP6-7 			  uid=9403dc82-267c-11e7-8933-ac72891c3257 
ISMIP6, ISMIP6.IyrGre, ISMP6-6 			  uid=9403d9a8-267c-11e7-8933-ac72891c3257 
ISMIP6, ISMIP6.ImonGre, ISMP6-4 		  uid=94049ea6-267c-11e7-8933-ac72891c3257 
ISMIP6, ISMIP6.ImonGre, ISMP6-6 		  uid=9404a4fa-267c-11e7-8933-ac72891c3257 
ISMIP6, ISMIP6.ImonGre, ISMP6-7 		  uid=9404a7de-267c-11e7-8933-ac72891c3257 
ISMIP6, ISMIP6.ImonGre, lgm127k 		  uid=9404aa4a-267c-11e7-8933-ac72891c3257 
ISMIP6, ISMIP6.ImonGre, SSP5-85-01 		  uid=9404acd4-267c-11e7-8933-ac72891c3257 
ISMIP6, ISMIP6.ImonGre, ISMP6-5 		  uid=9404a28e-267c-11e7-8933-ac72891c3257 
DAMIP, DAMIP-6hrPlev-p2, DAMIP-1 		  uid=93f8a560-267c-11e7-8933-ac72891c3257 
DAMIP, DAMIP-Amon-new, ssp245 			  uid=93f8df94-267c-11e7-8933-ac72891c3257 
DAMIP, DAMIP-Amon-new, DAMIP-1 			  uid=93f8d3dc-267c-11e7-8933-ac72891c3257 
GeoMIP, Lmon, ScenarioMIP-3 			  uid=93ffb6ca-267c-11e7-8933-ac72891c3257 
GeoMIP, Lmon, ScenarioMIP-1 			  uid=93ffb40e-267c-11e7-8933-ac72891c3257 
DAMIP, DAMIP-Emon, ssp245 			  uid=93fa88a8-267c-11e7-8933-ac72891c3257 
DAMIP, DAMIP-Emon, DAMIP-1 			  uid=93fa7d04-267c-11e7-8933-ac72891c3257 
ISMIP6, ISMIP6.ImonAnt, ISMP6-7 		  uid=9403c33c-267c-11e7-8933-ac72891c3257 
ISMIP6, ISMIP6.ImonAnt, ISMP6-4 		  uid=9403bb30-267c-11e7-8933-ac72891c3257 
ISMIP6, ISMIP6.ImonAnt, SSP5-85-01 		  uid=9403c8aa-267c-11e7-8933-ac72891c3257 
ISMIP6, ISMIP6.ImonAnt, ISMP6-6 		  uid=9403c062-267c-11e7-8933-ac72891c3257 
ISMIP6, ISMIP6.ImonAnt, lgm127k 		  uid=9403c5a8-267c-11e7-8933-ac72891c3257 
ISMIP6, ISMIP6.ImonAnt, ISMP6-5 		  uid=9403bd92-267c-11e7-8933-ac72891c3257 
ISMIP6, ISMIP6.IfxAnt, ISMP6-5 			  uid=9405022e-267c-11e7-8933-ac72891c3257 
ISMIP6, ISMIP6.IfxAnt, ISMP6-7 			  uid=940507f6-267c-11e7-8933-ac72891c3257 
ISMIP6, ISMIP6.IfxAnt, SSP5-85-01 		  uid=94050d64-267c-11e7-8933-ac72891c3257 
ISMIP6, ISMIP6.IfxAnt, lgm127k 			  uid=94050ae4-267c-11e7-8933-ac72891c3257 
ISMIP6, ISMIP6.IfxAnt, ISMP6-6 			  uid=940504fe-267c-11e7-8933-ac72891c3257 
ISMIP6, ISMIP6.IfxAnt, ISMP6-4 			  uid=9404ff54-267c-11e7-8933-ac72891c3257 
GeoMIP, GeoMIP.aeroGeo, ScenarioMIP-3 		  uid=93ffe0dc-267c-11e7-8933-ac72891c3257 
GeoMIP, GeoMIP.aeroGeo, ScenarioMIP-1 		  uid=93ffdde4-267c-11e7-8933-ac72891c3257 
DAMIP, DAMIP-EmonZ, DAMIP-1 			  uid=93fa2ed0-267c-11e7-8933-ac72891c3257 
DAMIP, DAMIP-EmonZ, ssp245 			  uid=93fa3a7e-267c-11e7-8933-ac72891c3257 
DAMIP, AERmon-oth, DAMIP-1 			  uid=93f91c8e-267c-11e7-8933-ac72891c3257 
DAMIP, day-oth, DAMIP-1 			  uid=93f81000-267c-11e7-8933-ac72891c3257 
ISMIP6, ISMIP6-LImon-01, SSP5-85-01 		  uid=940468c8-267c-11e7-8933-ac72891c3257 
ISMIP6, ISMIP6-LImon-01, lgm127k 		  uid=94046652-267c-11e7-8933-ac72891c3257 
ISMIP6, ISMIP6-LImon-01, ISMP6-5 		  uid=94046148-267c-11e7-8933-ac72891c3257 
ISMIP6, ISMIP6-LImon-01, ISMP6-4 		  uid=94045ef0-267c-11e7-8933-ac72891c3257 
ISMIP6, ISMIP6-LImon-01, ISMP6-6 		  uid=940463e6-267c-11e7-8933-ac72891c3257 
DAMIP, Omon-subset-01, DAMIP-1 			  uid=93f834c2-267c-11e7-8933-ac72891c3257 
DAMIP, SIMIP-seaicemon, DAMIP-1 		  uid=93f9d872-267c-11e7-8933-ac72891c3257 
GeoMIP, AERmon-subset-01, ScenarioMIP-3 	  uid=93fe4a42-267c-11e7-8933-ac72891c3257 
GeoMIP, AERmon-subset-01, ScenarioMIP-1 	  uid=93fe47e0-267c-11e7-8933-ac72891c3257 
DAMIP, Amon, DAMIP-1 				  uid=93faa540-267c-11e7-8933-ac72891c3257 
DAMIP, Amon, ssp245 				  uid=93fab7d8-267c-11e7-8933-ac72891c3257 
DAMIP, DAMIP-Omon-p2, DAMIP-1 			  uid=93f96734-267c-11e7-8933-ac72891c3257 
PMIP, PMIP-Lmon-02, HistNolulcc01 		  uid=940c4f5c-267c-11e7-8933-ac72891c3257 
PMIP, PMIP-Lmon-02, IdealizedRegDeforest 	  uid=940c49c6-267c-11e7-8933-ac72891c3257 
PMIP, PMIP-Lmon-02, EsmhistbgcNolulcc 		  uid=940c51dc-267c-11e7-8933-ac72891c3257 
PMIP, PMIP-Lmon-02, IdealizedGlobalDeforest 	  uid=940c46ba-267c-11e7-8933-ac72891c3257 
PMIP, PMIP-Lmon-02, HistNolulccLnd 		  uid=940c4c96-267c-11e7-8933-ac72891c3257 
GeoMIP, day-subset-01, ScenarioMIP-1 		  uid=93ff38e4-267c-11e7-8933-ac72891c3257 
GeoMIP, day-subset-01, ScenarioMIP-3 		  uid=93ff3b3c-267c-11e7-8933-ac72891c3257 
ISMIP6, ISMIP6.Omon, SSP5-85-01 		  uid=9404dbaa-267c-11e7-8933-ac72891c3257 
ISMIP6, ISMIP6.Omon, ISMP6-4 			  uid=9404d100-267c-11e7-8933-ac72891c3257 
ISMIP6, ISMIP6.Omon, ISMP6-5 			  uid=9404d452-267c-11e7-8933-ac72891c3257 
ISMIP6, ISMIP6.Omon, ISMP6-6 			  uid=9404d6b4-267c-11e7-8933-ac72891c3257 
ISMIP6, ISMIP6.Omon, lgm127k 			  uid=9404d920-267c-11e7-8933-ac72891c3257 
DAMIP, CFmon-sim, DAMIP-1 			  uid=93f9fe92-267c-11e7-8933-ac72891c3257 
GeoMIP, CFmon-3dstd, ScenarioMIP-3 		  uid=93fe72ec-267c-11e7-8933-ac72891c3257 
GeoMIP, CFmon-3dstd, ScenarioMIP-1 		  uid=93fe7080-267c-11e7-8933-ac72891c3257 
GeoMIP, SIMIP-seaicemon, ScenarioMIP-3 		  uid=93fec17a-267c-11e7-8933-ac72891c3257 
GeoMIP, SIMIP-seaicemon, ScenarioMIP-1 		  uid=93febf22-267c-11e7-8933-ac72891c3257

**Comment by martinjuckes** [comment]
Fixed in or before 01.00.27

**Comment by senesis** [comment]
For those centers which believed in the WIP assertion that DR01.00.21 can be used for production, that answer is lacking some precision regarding the spread of fixes among versions
