### ISSUE TITLE
toz, tropoz units

### ISSUE THREAD

**Issue by lwhorowitz** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#232]
The units for these AERmon variables are currently (v1.0.15) given as "m". But, Description/Comments suggest the units should be "DU" (Dobson Units).

**Comment by martinjuckes** [comment]
The units should be "m": "DU" is not a valid unit in the CF convention. I've modified the descriptions and comments.

**Comment by lwhorowitz** [comment]
I suspected this was the reason forusing "m". This is fine, as long as the comment/description include a specification of the standard temperature and pressure at which the column depth is calculated, presumably 0 degrees C and 1 atm, such that 1m = 1e5 DU. Thanks!

**Comment by martinjuckes** [comment]
OK, I'll add that clarification: taking stp to be 0C and 1 bar.
