### ISSUE TITLE
emilnox

### ISSUE THREAD

**Issue by lwhorowitz** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#233]
The units of this AERmon variable are currently (v1.0.15) given as "mol s-1". For consistency with other emi* variables, these units should be changed to "kgN m-2 s-1".

**Comment by martinjuckes** [comment]
This would require a change of standard name, which would also need a new standard name, as there is no mass_content equivalent to the standard name used for emilnox: tendency_of_atmosphere_moles_of_nox_expressed_as_nitrogen

**Comment by lwhorowitz** [comment]
Moreso than whether emilnox is expressed in mass or molar units, my stronger objection to these units are that they are extensive (i.e., integrated over the volume of a grid cell) rather than intensive (i.e., per unit area). Among other problems, this will cause difficulty with regridding.

**Comment by martinjuckes** [comment]
That may be so, but if you want a different standard name you need to raise that with the CF Conventions discussion here (if you are not part of the email discussion, you can join here: http://mailman.cgd.ucar.edu/mailman/listinfo/cf-metadata --- sorry if the process is confusing, I don't like it either).
