### ISSUE TITLE
sedustCI is in realm atmos 

### ISSUE THREAD

**Issue by oligan** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#239]
sedustCI is in realm atmos but shouldn't it be in aerosol ??
and not clear it doesn't duplicate some variable that are already there 

Likewise depdust should also be in realm aerosol

**Comment by martinjuckes** [comment]
I will change the realms. I don't see and candidate for a duplicate .. do you have something in mind?

**Comment by oligan** [comment]
Hello Martin, 
for consistency with the other variables in the aerosol realm (drydust, wetdust, emidust), the variable name should be seddust. It is not clear why there is a seddust but not a sedss. Maybe bounce the question back to Michael Schulz. 
Olivier

**Comment by martinjuckes** [comment]
The difference will be because sedustCI and depdust are requested by PMIP, not by AerChemMIP. I suppose PMIP is not interested in salt sedimentation. The change for sedustCI and depdust will be in 01.00.17
