### ISSUE TITLE
*bnd variables do not have an extra dimension for wavebands

### ISSUE THREAD

**Issue by oligan** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#240]
There is a range of radiation quantities that are requested for the various wavebands of the radiation model, such as aerasymbnd, aeroptbnd, aerssabnd, solbnd, etc.... However the dimensions in the metadata do not seem to include that extra dimension.

**Comment by martinjuckes** [comment]
[aerasymbnd ](http://clipc-services.ceda.ac.uk/dreq/u/7b3026d8-a220-11e6-a33f-ac72891c3257.html) has dimenions of time, latitude, longitude, model level and spectral band. The spectral band dimension is included in the `odims` and `dids`records of the `structure` [record](http://clipc-services.ceda.ac.uk/dreq/u/63c353f8-15f2-11e7-87e0-5404a60d96b5.html). The spectral band dimension is [spectband](http://clipc-services.ceda.ac.uk/dreq/u/dim:spectband.html),  which simply asks for the central value of each band. Were you looking for the [spectband](http://clipc-services.ceda.ac.uk/dreq/u/dim:spectband.html) dimension, or is something else missing?

**Comment by martinjuckes** [comment]
I've raised an issue in the "CMIP7 Forward Look" repo (https://github.com/cmip6dr/cmip7_forward_look/issues/10 ) related to this, but I don't think there is anything to do for CMIP6.
