### ISSUE TITLE
o3ste

### ISSUE THREAD

**Issue by lwhorowitz** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#242]
Is this tracer intended to be defined as was "o3ste" in CCMI?:

> (a) set o3ste to O3 at top layer;
> (b) use standard O3 P-L terms to change o3ste every chemistry time step for 'stratospheric' air grid boxes;
> (c) reset o3ste to O3 in the lowermost layers (fix these layers to be up to sigma=0.9, ~1 km altitude) and record this tropospheric reset only as a 2-D (lat,long) monthly mean tendency (Tg/s or Tg per month per grid cell).
> Determine 'stratopsheric' air in any way that is most convenient (e90, O3, PV-theta, etc).

Or as "o3s" in CCMI:

> stratospheric ozone tracer set to ozone in the stratosphere, then destroyed in the troposphere using the ozone chemical loss rate. Specify the tropopause definition.

**Comment by martinjuckes** [comment]
I think this is no longer relevant .. o3s is not in the request.
