### ISSUE TITLE
wrong cell_measures attributes on some ocean variables

### ISSUE THREAD

**Issue by taylor13** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#243]
in the Odec and Omon tables several variables quantifying merdional transport have cell_measures = "area: areacella".  None of the variables with areacella should have a cell measure because there is no horizontal extent of grid cells (they are vertical cross-sections).  some of the variables that are incorrect are "msft...." "hto ...", "slt...", "mfo", "hfbasin".
cc: @durack1

**Comment by martinjuckes** [comment]
Thanks for pointing it out. Fixed for 01.00.17
