### ISSUE TITLE
afullo in wrong table

### ISSUE THREAD

**Issue by taylor13** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#244]
The ocean folks have requested that zfullo be placed in "Omon" but in the current release it is found in table "Eyr".  They want it sampled monthly and they don't want it mixed with the atmospheric variables in Eyr.  (see https://goo.gl/Fyr6QW )

Also it would make things a lot cleaner if all the ocean variables currently listed in "Emon" were moved to "Omon", but at this late date that might be too disruptive.
cc: @durack1

**Comment by martinjuckes** [comment]
You mean `zfullo`?  `zfullo` is already in Omon as requested by OMIP, and is also in Eyr at the request of of DCPP and LUMIP.

**Comment by durack1** [comment]
Looks to me like we have 3 entries:
[Oclim](http://clipc-services.ceda.ac.uk/dreq/u/3c564abe-b89b-11e6-be04-ac72891c3257.html)
[Omon](http://clipc-services.ceda.ac.uk/dreq/u/5a4c10e4-c77d-11e6-8a33-5404a60d96b5.html)
[Eyr](http://clipc-services.ceda.ac.uk/dreq/u/90e8026c-267c-11e7-8933-ac72891c3257.html)

**Comment by taylor13** [comment]
@martinjuckes @durack1 I would say Eyr and "Oclim" are redundant.  Do you agree?  If so, let's eliminate zfullo from Eyr.

**Comment by durack1** [comment]
@taylor13 there is not an `Oclim` request from OMIP, so not sure where that came from. A climatology by definition needs to have some temporal extent. We only have `Ofx`, `Oday`, `Omon`, `Oyr` and `Odec` across the 3 sheets, biogeochemistry (https://goo.gl/Fyr6QW), chemistry (https://goo.gl/BrXVgb) and physics (https://goo.gl/Rhrcwp)
