### ISSUE TITLE
siconc vs. siconco

### ISSUE THREAD

**Issue by taylor13** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#245]
@martinjuckes (cc @durack1):  In SIday and SImon, it's not clear to me what the difference is between siconc and siconco.  I thought that siconco might be the concentration of sea ice reported on the ocean grid but it has cell_measures with "areacella".  And siconc has "areacello".  Shouldn't these be reversed?

**Comment by matthew-mizielinski** [comment]
This is probably down to our request (see discussion in #33); we have a few sea ice variables computed in our land model JULES (atmosphere lat-lon grid) while the rest come from CICE (tripolar ORCA grid). As sea ice concentration is needed to perform weighting in averaging operations, e.g. November mean over 20 years, we would need to provide it on both grids. 

The issue around areacella and areacello being the wrong way round has been raised in #182 , but this may be connected with the discussion around the complexity in cell methods specifications (PCMDI/cmor#220).

**Comment by taylor13** [comment]
@matthew-mizielinski   Of the two variables, which applies to the CICE (ORCA) grid, and which the land/atmos grid?  I think it would make most sense to let siconco represent concentration on the ocean grid (in which case it should have cell_measures=area:areacello) and siconc represent the concentration on the land/atmos grid (with cell_measures=area:areacella).  Does that make sense?

**Comment by matthew-mizielinski** [comment]
My interpretation, based on the cell_measures, of the information in v01.00.15 is the same as yours; the cell_measures are the wrong way around, i.e. siconco _should_ correspond to the "ocean" grid and siconc to the "land/atmosphere" grid. The modelling realm for each of these variables is correct (both have `seaIce`), but the structure ids (determining dimensions, cell_methods and cell_measures) need to be swapped. 

@martinjuckes, would it possible for this minor tweak to be made for v01.00.16?

**Comment by durack1** [comment]
While changes are being discussed I thought it relevant to raise the CMIP5 vs CMIP6 status of this variable. The CMIP5 data request included `sic` which has been renamed to `siconc`. The realm for `sic` was `seaIce ocean`, the units were `% (fraction of grid cell area covered by sea ice)` and `cell_measures = area: areacello`. For [CMIP6 the variable name is different (sic -> siconc), along with the realm information ("seaIce ocean" -> "seaIce")](http://clipc-services.ceda.ac.uk/dreq/u/71190054-faa7-11e6-bfb7-ac72891c3257.html)

**Comment by martinjuckes** [comment]
Yes, this should be switched. Sorry I didn't get it done for 01.00.16 .. it will be in 01.00.17

**Comment by dirknotz** [comment]
Sorry for joining late. We had some offline discussion on this back in June, and the last email I found was suggesting that siconc should be the "standard variable" for sea-ice concentration, and hence should be reported on the standard grid of sea-ice models, which is the ocean grid. 

The supplementary information on sea-ice concentration on the atmospheric grid should be called siconca. I believe it will cause lots of confusion if siconc is reported on the atmospheric grid.

Alternatively, we could have siconco and siconca and drop siconc.

**Comment by taylor13** [comment]
@martinjuckes @durack1 In CMIP5 there was only one sea ice fraction variables with the following specifications:
1) the name was "sic"
2) It was supposed to be reported on the grid used for all other ocean fields
3) It was "total" fraction (not broken up into sea ice "types" i.e., not distinguishing among frazil ice, grease ice, slush, shuga, etc.)

I had assumed that in CMIP6 "siconco" replaced "sic", but now I notice this is *not* the case [even after correcting the mistake with "areacell"] because siconco has a singleton (scalar) coordinate indicating "type".    There is no need to include the type="seaice", since the standard_name is sea_ice_area_fraction.  

Also I see little value in collecting siconc in addition to siconco, since it can be obtained using conservative regridding. 

In any case, since the primary grid (in nearly all models) is the ocean, let's name the standard variable without a suffix (i.e., siconc), and if you want to include the new variable (on the atmospheric grid), name it "siconca".

**Comment by matthew-mizielinski** [comment]
> Also I see little value in collecting siconc in addition to siconco, since it can be obtained using conservative regridding.

I can see your point, but given how important siconc is for aggregating sea-ice variables I suspect the average scientist using this data will simply ignore models that don't provide it on the same grid as the variables they are working with.

I think it might be prudent at this stage to identify whether there are any models involved in CMIP6, other than UKESM1 and HadGEM3, that have this issue. If no-one else has this issue then perhaps we can/should manage this using grid labels.

**Comment by dirknotz** [comment]
@taylor13 : We intended to have siconc directly replace sic. The singleton coordinate indicating type="seaice: should be removed it is confusing. 

I agree with Matthew that siconca is a useful additional variable, as quite a few studies exist that use different proxies to obtain sea-ice coverage on the atmospheric grid, for example surface albedo. Having siconca directly stored would thus ease analysis of atmosphere-sea-ice interaction.

**Comment by taylor13** [comment]
I will not object to sic becoming siconc (although because of the name change this makes it difficult to use model results from the earlier phases of CMIP in a study with CMIP6 siconc data).  [Note that input4MIPs has adopted this new name (i.e., sic has become siconc), so let's not change it again to siconco.]

there seems to be agreement that the singleton coordinate type= "seaice" should be removed.  

The majority seem to think that siconca is a useful addition.

**Comment by martinjuckes** [comment]
sic --> siconco for ocean, siconc on atmospheric grid.

**Comment by durack1** [comment]
@martinjuckes referencing the comment from @dirknotz [above](https://github.com/cmip6dr/CMIP6_DataRequest_VariableDefinitions/issues/245#issuecomment-334930170)
> the last email I found was suggesting that siconc should be the "standard variable" for sea-ice concentration, and hence should be reported on the standard grid of sea-ice models, which is the ocean grid. The supplementary information on sea-ice concentration on the atmospheric grid should be called siconca. I believe it will cause lots of confusion if siconc is reported on the atmospheric grid.

We've been generating `siconc` data (renamed from `sic`) [since June 2016 (PCMDI)](https://github.com/PCMDI/amipbcs/releases/tag/v1.1.0) and [May 2017 (MOHC)](https://esgf-node.llnl.gov/search/input4mips/?dataset_version_number=2.2.0.0-r0) for input4MIPs in order to conform to the CMIP6 data request

**Comment by dirknotz** [comment]
@martinjuckes 
I thought we had agreed that siconc should be on the ocean grid, and that we additionally introduce siconca? siconco should then be removed. In any case, it would cause endless confusion to have siconc on the atmosphere grid. Thanks.

**Comment by martinjuckes** [comment]
siconco removed.
