### ISSUE TITLE
Redundant land variables

### ISSUE THREAD

**Issue by ducharne-ipsl** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#246]
The following pairs of variables (from land realm) seem to be redundant:
- Total water storage: tws (provMIP=LS3MIP, P1) & mrtws (provMIP=PMIP, P2)
- Total water content of soil layer: mrsol (provMIP=PMIP, P1) & mrlsl (provMIP=CMIP5, P1)
- Potential ET: potet (provMIP=LS3MIP, P1) & evspsblpot (prov=CORDEX, P1)
At least one of each pair below is requested by LS3MIP

**Comment by matthew-mizielinski** [comment]
Note that you don't have to respond to every request for data. For certain of our configurations of HadGEM3/UKESM1 we will be responding to PMIP requests, but not to LS3MIP and vice versa for others.

Also be careful with the provMIP field, [Emon/mrtws](http://clipc-services.ceda.ac.uk/dreq/u/6f6a4484-9acb-11e6-b7ee-ac72891c3257.html) is requested by both C4MIP and PMIP.

Note that you need to be a little careful with priorities when you start filtering on MIPs; the resolved priority can be different to the default priority. Have a look at cmip6dr/Request#56 for some discussion of the connections within the data request and how they impact on the priority of a particular variable once decisions about which MIPs you wish to respond to have been made.

**Comment by martinjuckes** [comment]
(1) tws and mrtws: this looks like redundancy, I'll check with the MIP cochairs;

(2) mrsol, mrlsl: this is a redundancy (same standard name), I'll remove mrlsl;

(3) potet and evspsblpot: also a redundancy, I'll remove potet in favour of evspsblpot (the latter already has a correct standard name);

**Comment by martinjuckes** [comment]
mrsol/mrlsl & potet/evspsblpot fixed in 01.00.16,  tws/mrtws in 01.00.17
