### ISSUE TITLE
Ambiguous definition of some soil properties (requested by LS3MIP)

### ISSUE THREAD

**Issue by ducharne-ipsl** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#247]
**1. mrsofc**: CF Standard Name = "soil_moisture_content_at_field_capacity" ; Long Name = "Capacity of Soil to Store Water" ; description = "divide the total water holding capacity of all the soil in the grid cell by the land area in the grid cell; reported as *missing* where the land fraction is 0.“
These elements are only consistent if the field capacity defines the maximum water holding capacity of the soil, which is not the case in the ORCHIDEE LSM and many others. In ORCHIDEE, the capacity of the soil is defined by the porosity, or saturated water content, and is larger than the field capacity.
**Proposition**: omit the reference to the field capacity  and replace "mrsofc" by "mrsox" or "mrsomax" ? with CF Standard Name = "max_soil_moisture_content" ; Long Name = "Capacity of Soil to Store Water" ; description = "divide the total water holding capacity of all the soil in the grid cell by the land area in the grid cell; reported as *missing* where the land fraction is 0.“
**2. wilt and fldcapacity** are expected in %, but in % of what ? It would make sense to define them in % of the maximum water capacity, but this sends back to the above question. Alternatively, they could be given in kg/m² over the soil depth.

**Comment by martinjuckes** [comment]
1. I think the distinction hinges on the interpretation of *holding* in the description. If we modify this to refer to holding over 2 to 3 days, then it should be consistent with the standard name. i.e. it is the amount of water that can be held in a steady state without new inflows, not the maximum that can be held at any time. This variable was used in CMIP5, so I think we should stay with the interpretation implied by the standard name and adjust the variable description: "The bulk water content retained by the soil at -33 J/kg of suction pressure, expressed as mass per unit land area; report as missing where there is no land".

On point 2, I'll ask for clarification from LS3MIP.

**Comment by ducharne-ipsl** [comment]
For point 1, I agree with you regarding the consistency between the standard name and the description.
But many models will produce mrso that is sometimes greater than mrsofc, and it may be important to have another variable giving the maximum capacity of the soil (to which wilt and fldcapacity in % could relate to, for instance).

**Comment by martinjuckes** [comment]
Sorry for the delay .. I've refreshed my query to the LS3MIP coordinators.

**Comment by martinjuckes** [comment]
Wilt and field capacity are expressed as percentages of soil volume, not the maximum capacity, so we don't have a clear need to add a new variable.
