### ISSUE TITLE
A few experiments have start year == "As above"

### ISSUE THREAD

**Issue by senesis** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#251]
... which is not self-explanatory when using the API. This is the case for :

piSST-4xCO2-rad      
a4SSTice-4xCO2       
piSST-pxK            
a4SSTice             
a4SST                
piSST-4xCO2

**Comment by martinjuckes** [comment]
Thanks for pointing that out ... I'll move this to https://github.com/cmip6dr/Request/issues as it is not about variable definitions.
