### ISSUE TITLE
fgdms {Emon}: Surface Upward Flux of DMS [mon: Temporal mean, Global ocean field on model levels [XY-O] [tmean]] (1)

### ISSUE THREAD

**Issue by jkettleb** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#253]
is `fgdms {Emon}: Surface Upward Flux of DMS [mon: Temporal mean, Global ocean field on model levels [XY-O] [tmean]] (1)` right?  the name implies 'Surface flux' but the dimensions are over model levels?

**Comment by martinjuckes** [comment]
This should be the same as the Omon variable .. (which is a surface layer variable). I'll correct the request.
