### ISSUE TITLE
co2 units

### ISSUE THREAD

**Issue by jkettleb** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#254]
co2 appears to be requested with both vmr and mmr units - would it be easier for data users if a consistent unit was requested?

mole fraction/vmr
http://clipc-services.ceda.ac.uk/dreq/u/9bb9a503065dfbd30c9bbe5c3c6abf99.html

mass mixing ratio
http://clipc-services.ceda.ac.uk/dreq/u/712473d6-c7b6-11e6-bb2a-ac72891c3257.html

**Comment by martinjuckes** [comment]
I'll ask Chris Jones

**Comment by martinjuckes** [comment]
This has now been confirmed and reinforced with a new standard name. The mass mixing ratio is an extra CO2 field used to analyse transport.
