### ISSUE TITLE
variables mmrbc and mmrss have erroneous shape (single level) in Emon

### ISSUE THREAD

**Issue by senesis** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#258]
MIP variable [mmrss](http://clipc-services.ceda.ac.uk/dreq/u/5980f8e283fd4709e4542c0652756dc1.html) matches two CMOR vars. The one in Emon is single level, while the one in AERmon is on model levels. And there is no cell_method for the variable in Emon which would indicate that one shoud integrate on the vertical 
Same occurs for mmrbc

**Comment by martinjuckes** [comment]
Both mmrss, mmrbc Emon variables have now been removed, replaced by AERmon variables which are 3d variables.
