### ISSUE TITLE
dimension misrBands has no value for field 'requested' 

### ISSUE THREAD

**Issue by senesis** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#259]
A value would ease computing accurate field sizes, and hence data volumes, for COSP-related requests

**Comment by senesis** [comment]
And as far as I know, requested values are 0.15, 0.8, 2.45, 6.5, 16.2, 41.5, 100

**Comment by martinjuckes** [comment]
The `misrBands` dimension is not used .. sorry for the confusion. It was used in request version 01.00.01, but the usage dropped by 01.00.04. I'll remove it from 01.00.18.  Sorry for the confusion.
