### ISSUE TITLE
Unit of specific humidity

### ISSUE THREAD

**Issue by oligan** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#261]
Specific humidity (variables hus, huss, hus7h, ...) has unit "1" (=no unit), kg kg-1 would be more appropriate.

**Comment by martinjuckes** [comment]
"1" and "kg kg-1" are equivalent. We have kept to the CMIP5 usage here, and I think it is too late to make a change at this stage. People sometimes write "kg kg-1" to signpost the distinction between, for instance, a mass and a volume mixing ratio, but in the CF Convention "kg kg-1" and "m3 m-3" are equivalent. Instead we make the variable definition unambiguous through the CF Standard Name.
