### ISSUE TITLE
Ocean variables requested in AMIP / Atmospheric variables requested in Land Only 

### ISSUE THREAD

**Issue by JeanneColin** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#262]
Hello,

We (CNRM) found quite a few AMIP experiments requesting ocean tables. There are also Land Only simulations (LS3MIP) requesting both atmospheric and oceanic variables. We think those tables should be suppressed in the requested tables of these experiments. 

Here is a list of the AMIP simulations we found with ocean variables (there may be more):
amip-piForcing
a4SSTice-4xCO2
piSST-4xCO2-rad
a4SST
piSST
piSST-4xCO2
piSST-pxK
amip-a4SST-4xCO2
amip-lwoff
amip-p4K-lwoff
amip-m4K
amip-future4K
amip-4xCO2
amip-p4K
a4SSTice
amip-lfmip-pObs
amip-lfmip-pdLC
amip-lfmip-rmLC

And here is the list of Land only experiments with atmospheric and oceanic tables (again, there may be more):
land-hist
land-hist-cruNcep
land-hist-princeton
land-hist-wfdei
land-future

Best regards,

Jeanne

---
Jeanne Colin
CNRM - Météo-France
---

**Comment by martinjuckes** [comment]
The Omon, Oday, Oyr tables can be suppressed, and I think this has now been done. We can't suppress individual variables so easily .. apologies for the inconvenience, but that will have to be something to look at as a future improvement.
