### ISSUE TITLE
tSoilPools cSoilPools description and shape uncoherent

### ISSUE THREAD

**Issue by SebastienDenvil** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#264]
Description is : defined as 1/(turnover time) for each soil pool. Use the same pools reported under cSoilPools

And shapes are for both of them :  [mon: Temporal mean, Global field (single level) [XY-na] [amnla-tmn]]

Which means a lon-lat field instead of a lon-lat-soilpool shape

**Comment by taylor13** [comment]
Looks to me that these are functions of each soil pool, so should have a "soilpool" dimension.  ????

**Comment by taylor13** [comment]
Are there standard "soilpool" descriptions, or how is the user supposed to know what each soilpool index signifies?

**Comment by matthew-mizielinski** [comment]
The change to pick this up in data request version 01.00.20 has also changed the cell_methods for these variables to instantaneous (see [here](http://clipc-services.ceda.ac.uk/dreq/u/e7071f58-aa7f-11e6-9a4a-5404a60d96b5.html) for example), but there is no mention of this change in the release notes. According to Chris Jones, C4MIP require these variables as time:mean.

@martinjuckes, could you fix the cell_methods in the next version?

**Comment by martinjuckes** [comment]
The soilpool dimension is defined in the same way as vegtype, which was also present in CMIP5: it is a character dimension which needs to be implemented by CMOR as an integer array ... and I've just realised that it needs a "coords" attribute, which I've added in 01.00.22 (coords=pool_decription).

I'll update the cell methods as well.

**Comment by taylor13** [comment]
CMOR has to treat vegtype and this new dimension specially, so this is not a trivial change.  It would have been better (more consistent) to name this entry "soiltype" and I think its altLabel should be  assigned the generic descriptor "type".   
How is the "coords" attribute defined by the data request?  I think CMOR might ignore coords and relies on special coding to write this particular auxiliary coordinate.

**Comment by taylor13** [comment]
I now think only altLabel needs to be changed from "soilpools" to "type".  No need to change the label itself to "soiltype".

**Comment by martinjuckes** [comment]
I'm trying to use `coords` in a way which is consistent with past usage ... but it appears that "altLabel" is the attribute which really matters. I've changed this as you suggest.

**Comment by taylor13** [comment]
Thanks!  This just relieved us from introducing a special case to CMOR3.
