### ISSUE TITLE
CMORvar 'rls' in table Eday may call for multiple cell methods

### ISSUE THREAD

**Issue by senesis** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#267]
This CMOR var is requested there both by DCPP and LS3MIP. Cell method is 'mean where land', which seems fine for LS3MIP, but seems odd for DCPP

**Comment by senesis** [comment]
Same applies for variable 'rss'

**Comment by martinjuckes** [comment]
I'll check with DCPP coordinators.

**Comment by martinjuckes** [comment]
rls now has a land-masked version in Eday, and an unmasked version in day. The unmasked version is requested by DCPP, as suggested above.
