### ISSUE TITLE
miptable proliferation

### ISSUE THREAD

**Issue by taylor13** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#27]
In CMIP5, separate CMOR tables (the analog to MIP tables in CMIP6) are defined, with a few exceptions) to distinguish "frequency" and "realm".  In CMIP6, we now have many additional tables.  What is the rationale for not including these into existing tables?  In particular 
1) What does the "em" prefix mean in 14 new tables?
2) Is it really necessary to have essentially duplicate tables for Greenland and Antarctica (or are there important differences)?
3) Why are both 6hrPlev and 6hrPlevpt needed?

Perhaps we should also include the "aer" and "cf" tables in the generic tables, although in the case of "aer" you could argue it belongs to a significantly different "realm".  

We can obviously have many "variable groups" that contribute to a MIP table, and I think, for example, CFMon variables would belong to a group separate from Amon, even if they are in the same MIP table.

We also need to check that all variables in a single file belong to the same "frequency", so that frequency can be assigned on a per table basis.  [I'm not sure how to deal with the rare cases where it doesn't make sense to store many years of monthly data, when a model prescribes the field as an monthly climatology (not changing from 1 year to the next).  In CMIP5 we stored it under the same variable name, but only 12 time points were saved and some of the other global (and variable) attributes were changed.]

**Comment by taylor13** [comment]
I think this ticket should be merged with issue 29 (or perhaps just closed), although I would first like an answer to items 1-3 above.
thanks.

**Comment by martinjuckes** [comment]
I agree that they should be merged. I think items 1-3 are answered in my response to #29, but for clarity:
(1) "em..." tables  contain variables requested by individual MIPs which are not automatically added to data requested by other MIPs;
(2) The tables for Greenland and Antarctica are identical apart from the use of different coordinates;
(3) 6hrPlev is for time mean fields,  6hrPlevpt is for instantaneous fields. i.e. a file name starting "ua_6hrPlev_..." will indicate a time mean, "ua_6hrPlevpt_..." will be for instantaneous data. 

We should continue the discussion in #29 .. I'll close this issue.
