### ISSUE TITLE
vtendogw end vtendnogw DAMIP requests disappeared

### ISSUE THREAD

**Issue by senesis** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#270]
As far as I can tell, these two variables were requested in Emon in DR01.00.18 through RequestLink DAMIP-Emon . In DR01.00.19, they are no more requested. Is it on purpose ? 
(given the fact that zonal wind counter parts have not been suppressed)

**Comment by martinjuckes** [comment]
I'm puzzled by this as I can't find evidence of them having been included in DAMIP-Emon. I've checked, and DAMIP is definitely not requesting these variables.
