### ISSUE TITLE
zmeso in Emon is the same as zoomeso in Omon 

### ISSUE THREAD

**Issue by senesis** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#271]
As far as I understand, the same physical variable is requested in two distinct tables and as to distinct MIPvariables with the same shape and cell-method
http://clipc-services.ceda.ac.uk/dreq/u/f5ec9258-dca5-11e5-a52e-5404a60d96b5.html
and
http://clipc-services.ceda.ac.uk/dreq/u/30a7a10d4c71066f19eae9a89ddfafba.html

**Comment by senesis** [comment]
They also have the same frequency in those two tables (Emon and Omon)
And this also applies to zmicro/zoomicro

**Comment by taylor13** [comment]
also zmisc/zoomisc

**Comment by martinjuckes** [comment]
Fixed in 01.00.20

**Comment by senesis** [comment]
And, actually, all 3 variables should have modeling_realm=ocnBgChem , like 'zooc'

**Comment by martinjuckes** [comment]
in 01.00.20 requests for zoomeso, zoomicro and zoomisc have been replaced with requests for zmeso, zmicro and zmisc. But the CMORvar records are still present and should be removed.

**Comment by martinjuckes** [comment]
Fixed in 01.00.21

**Comment by taylor13** [comment]
Hi Martin,
Do you think the CMORvar records will affect the CMOR tables that Denis will generate based on the 01.0021?
thanks,
Karl

**Comment by martinjuckes** [comment]
I hope so .. I think that is where he is getting his information from.

**Comment by taylor13** [comment]
I was confused. I didn't notice that you'd fixed part of the problem in 01.00.20 and part in 01.00.21.  I thought only part had been fixed and was worried about inconsistencies.  I agree that once Denis updates to 01.00.21, everything will be o.k.  Thanks.  
I agree this can be closed.
