### ISSUE TITLE
rsucs in CFsubhr should have shape S-AH

### ISSUE THREAD

**Issue by senesis** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#272]
... while it shows as S-na in DR01.00.19
cf http://clipc-services.ceda.ac.uk/dreq/u/a955260e-817c-11e6-a4e2-5404a60d96b5.html

**Comment by martinjuckes** [comment]
Changed to S-AH. Also rsucs in CF3hr changed from XY-A to XH-AH
