### ISSUE TITLE
title and description are wrong for MIP variable tsnl

### ISSUE THREAD

**Issue by senesis** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#273]
They should be in line with the shape of the sole corresponding CMORvar , which is for a vertically-averaged snow layers temperature

**Comment by martinjuckes** [comment]
I'm sorry, I don't understand this comment. What aspect of the title and description do you want changed?

**Comment by senesis** [comment]
Sorry, I mean that the variable has no vertical dimension (according to shape requested by LS3MIP), and should hence be described as a snow mantle mean temperature, rather than as a profile
However, the difference with variable 'tsn' is then unclear

**Comment by martinjuckes** [comment]
OK. I've added a dimension `snowdepth`.

**Comment by martinjuckes** [comment]
Sorry for the misunderstanding. `tsnl` should be changed to `tsn`.

**Comment by martinjuckes** [comment]
tsnl removed from request: the variable tsn is a mean temperature for the snow layer.

**Comment by senesis** [comment]
tsnl is back in 28b. Is it on purpose ?
