### ISSUE TITLE
remove extraneous scalar ancillary coordinates attached to area fraction/% variables

### ISSUE THREAD

**Issue by taylor13** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#274]
There are several problems with specifications of area_type identifiers:

1)  First, I note that surface_snow_area_fraction is a function of (lon, lat, time) and does not have a scalar ancillary coordinate variable associated with it. This seems correct to me.

For the other area_fraction variables where the area is identified by the standard_name (including land_area_fraction, sea_ice_area_fraction, and sea_area_fraction), the data requests includes also  a coordinate label, which also indicates the "area_type" that is being accounted for.  These are unnecessary since the standard_names already provide the information. I think the following dimensions are therefore unneeded for CMIP6:  typeland, typesi, typesea.

2) typecloud appears in the list of CMIP6 dimensions, but it isn't used by any variable, so it should be removed.

3)  The variable "wetLandFraction" shows a standard_name of "wetland_fraction", but this is not in the current CF standard name table. Change to the generic "area_fraction"

4)  The scalar coordinate identified by "typenwd" has a standard_name = "area_type" and a value of "non_woody_vegetation", but that isn't in the latest CF convention area_type table posted  at http://cfconventions.org/standard-names.html .  Something is not right.

5) Variables cropFracC3 and cropFracC4 each have two ancillary scalar coordinates: (typec3pft, typecrop) and (typec4pft, typecrop).  In each case typecrop is unneeded and should be removed.

**Comment by taylor13** [comment]
Correction to point 5 above:  We can't remove "typecrop" because then the only way to distinguish the two area_fractions would be by reading the long_name (which is not standardized).

Need to confirm that CMOR3 is able to write the six variables that are functions of 2 scalar dimensions (cropFracC3, cropFracC4, grassFracC3, grassFracC4, pastureFracC3, patureFracC4).

**Comment by martinjuckes** [comment]
Additional area types have now been added, so we have reverted to single scalar coordinates.

**Comment by taylor13** [comment]
I think 2 hasn't been addressed, but this is not a high priority.
```
2. typecloud appears in the list of CMIP6 dimensions, but it isn't used by any variable, 
so it should be removed.
```
