### ISSUE TITLE
units missing for 9 variables in Emon

### ISSUE THREAD

**Issue by taylor13** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#275]
The variables identifying isotopes in the Emon table (e.g., 18O in total precipitation) might need units.  If they are fractions, CMOR expects a "1" for the units (although it's possible that "1.0" might also work).

I note that for variables aeroptbnd, aerssabnd, and aerasymbnd, the units are "1", consistent with the CF conventions and as they were for all dimensionless units in CMIP5.  I think for consistency, we should change all all units of "1.0" be changed to "1".

**Comment by martinjuckes** [comment]
Units "1.0" --> "1" fixed in 01.00.21. 
I'll check with PMIP about the units for O18p, O18s, H2p, H2s, O17p, O17s, O18wv, O17wv, H2wv, O18sw

**Comment by jypeter** [comment]
The values to be used for the missing units are listed in the table below and in the [CMIP6_MIP_tables_DR22vsRoche_units.xlsx](https://files.lsce.ipsl.fr/public.php?service=files&t=b0bfde6262ae9f85bda6947129cf8d33) file

The table gives alternating lines of current variable definitions in DR 01.00.22 and the new requested definitions in #316 , and the first column gives either the row number of the variable in the DR 01.00.22 Emon variables, or _updated_ to show the new values, or _NEW_ for the 2 new variables

Ping @dmr-dj (Didier Roche) if there are questions about the units

Line in   DR22 Emon | Long name | units | Variable Name
-- | -- | -- | --
280 | 18O in total precipitation |   | O18p
updated | H218O in precipitation | kg m-2 s-1 | pr18O
281 | 18O in solid precipitation |   | O18s
updated | H218O in snowfall flux | kg m-2 s-1 | prsn18O
282 | 2H in total precipitation |   | H2p
updated | 1H2HO in precipitation | kg m-2 s-1 | pr2h
283 | 2H in solid precipitation |   | H2s
updated | 1H2HO in snowfall flux | kg m-2 s-1 | prsn2h
284 | 17O in total precipitation |   | O17p
updated | H217O in precipitation | kg m-2 s-1 | pr17O
285 | 17O in solid precipitation |   | O17s
updated | H217O in snowfall flux | kg m-2 s-1 | prsn17O
286 | O18 in water vapor |   | O18wv
updated | H2O18 in water vapor | kg m-2 | prw18O
287 | O17 in water vapor |   | O17wv
updated | H2O17 in water vapor | kg m-2 | prw17O
288 | H2 in water vapor |   | H2wv
updated | 1H2HO in water vapor | kg m-2 | prw2H
318 | O18 in sea water |   | O18sw
updated | H2O18 in sea water | 1 | sw18O
  |   |   |  
NEW | H2O17 in sea water | 1 | sw17O
NEW | 1H2HO in sea water | 1 | sw2H

**Comment by taylor13** [comment]
@jypeter Thanks!

**Comment by martinjuckes** [comment]
Done
