### ISSUE TITLE
Variables for AerChemMIP simulations in the data request

### ISSUE THREAD

**Issue by taylor13** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#277]
Dear all,

the version 1.00.19 of the data request has just been published. Now I think that the variables are correct for several experiments (hist-pi*, histSST*, hist-1950HC, ssp370-lowNTCF), thanks for that !
However for all the other experiments (piClim*, ssp370SST*) there is still the same issue : no atmospheric variable in the data request (notably no aerosol, no chemistry).
Is there any plan to correct it ?

Best regards,
Pierre

**Comment by martinjuckes** [comment]
Sorry about that --- I'll release an update today fixing this.
