### ISSUE TITLE
valid_min 

### ISSUE THREAD

**Issue by dnadeau4** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#28]
Some of the variables in the MIP tables have both `valid_min` = `"0"` and `valid_max` = `"0"`, which causes CMOR3 to error, for example​ [siage](https://github.com/PCMDI/cmor/blob/master/TestTables/CMIP6_SImon.json#L2357) in the [SImon](https://github.com/PCMDI/cmor/blob/master/TestTables/CMIP6_SImon.json) MIP table.
See:
https://github.com/PCMDI/cmor/issues/91

**Comment by martinjuckes** [comment]
Thanks, I've located the bug causing this and it should be resolved in 01.beta.37
