### ISSUE TITLE
 "type" information missing or incorrect for many variables.

### ISSUE THREAD

**Issue by taylor13** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#280]
the data request should indicate for every variable whether we want "integer" "real" (single precision float) or "double"  (double precision float).

Many variables are missing this information.

To fix the problem:
1) where type is "float" change it to "real"
2) where type is missing, change it to "real".

**Comment by martinjuckes** [comment]
Corrected in 01.00.21
