### ISSUE TITLE
clarify positive of fgdms Omon

### ISSUE THREAD

**Issue by jkettleb** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#281]
http://clipc-services.ceda.ac.uk/dreq/u/baa0e906-e5dd-11e5-8482-ac72891c3257.html Omon fgdms has a positive=down, but the comment and standard name suggest upward.

Should the variables positive=up?

**Comment by martinjuckes** [comment]
Yes, .. corrected in 01.00.20

**Comment by jkettleb** [comment]
thanks Martin
