### ISSUE TITLE
value should be specified for dimension typewetla

### ISSUE THREAD

**Issue by taylor13** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#284]
For the dimension "typewetla", a "value" must be specified:  I suggest value = "wetland".

**Comment by martinjuckes** [comment]
The value should be taken from the  CF [area_type table](http://cfconventions.org/Data/area-type-table/current/build/area-type-table.html), but I agree that "wetland" would be a suitable value. A believe it has been raised on the CF discussions, but I'm not sure what happened to the thread.

**Comment by taylor13** [comment]
I've also heard the term "wetlands" .  found this on the web: 
```
There are many different kinds of wetlands and many ways to categorize them. 
NOAA classifies wetlands into five general types: marine (ocean), estuarine (estuary), 
riverine (river), lacustrine (lake), and palustrine (marsh). Common names for wetlands 
include marshes, estuaries, mangroves, mudflats, mires, ponds, fens, swamps, deltas, 
coral reefs, billabongs, lagoons, shallow seas, bogs, lakes, and floodplains, to name 
just a few!
```
So if the plural refers to the various kinds that are included, perhaps it is to be preferred.  Wonder what the experts think.

**Comment by martinjuckes** [comment]
Area type `wetland` is now in the CF list and will be used here.
