### ISSUE TITLE
pl700 vs p700

### ISSUE THREAD

**Issue by slavakharin** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#285]
I am not sure if this the right place to comment. I noticed two dimension variables for 700hPa level, `p700` and `pl700`. Is it intentional or is `pl700` is just a duplicate of `p700`. There are many other `p###` variables but only a single `pl700`.

**Comment by senesis** [comment]
pl700 has bounds 600 and 800, which mean it is a layer-averaged value

**Comment by slavakharin** [comment]
I find the naming convention a bit inconsistent. Some of the p### variables have no bounds (e.g. p1000, p100, p10, p200, p500, p700, p850) while some other p### variable do have bounds (e.g. p220, p560, p840). pl700 also has bounds but a slightly different naming convention (probably because p700 was already taken). It would be perhaps better to rename p220, p560, p840 to pl220, pl560, pl840 to distinguish these "pressure layer-averaged" variables from "point" pressure variables. Not a big deal though and can be left as it is, if it's too much trouble to change.

**Comment by martinjuckes** [comment]
I agree that this is not ideal, and, it has, as you say, arisen through incremental changes. I believe that the usage of "pnnn" for both "point" and layer average variables dates back to CMIP5, and the single exception of "pl700" was needed to resolve a conflict which first arose in CMIP6. I'm not sure that it is worth changing at this stage, but will flag it for consideration in CMIP7:  https://github.com/cmip6dr/cmip7_forward_look/issues/16
