### ISSUE TITLE
rlut: long name misspelt

### ISSUE THREAD

**Issue by alejandrobodas** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#286]
In the following instances of rlut, the long name are missing the 'n' in radiation:

rlut {E1hrClimMon}: TOA Outgoing Longwave Radiatio [1hrCM: Mean Diurnal Cycle, Global field (single level) [XY-na]] (1)
rlut {E1hr}: TOA Outgoing Longwave Radiatio [1hrPt: Instantaneous value (i.e. synoptic or time-step value), Global field (single level) [XY-na] [amn-tpt]] (1)
rlut {E3hr}: TOA Outgoing Longwave Radiatio [3hr: Temporal mean, Global field (single level) [XY-na] [am-tm]] (1)
rlut {Esubhr}: TOA Outgoing Longwave Radiatio [subhrPt: Instantaneous value (i.e. synoptic or time-step value), Global field (single level) [XY-na] [amn-tpt]] (1)

**Comment by martinjuckes** [comment]
Thanks. Corrected for 01.00.21
