### ISSUE TITLE
dimension time3 cannot have altLabel=time

### ISSUE THREAD

**Issue by senesis** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#287]
attribute altLabel is supposed to be used for the name of NetCDF variables

As far as I understand, time3 is a dimension for the hour in the day for frequency 1hrClimMon , and it has to be added to a more 'standard' time dimension ( which describes - through its bounds - the extent of time (months, years) used in deriving each monthly value in the file).

If this is true, time3.altLabel must not be equal to the standard time dimension name

**Comment by senesis** [comment]
This issue can be closed : I hadn't read carefully the CF convention re. climatologies. Sorry

**Comment by martinjuckes** [comment]
Thanks ... the climatologies section is a tough read.
