### ISSUE TITLE
cell_methods clarification

### ISSUE THREAD

**Issue by jkettleb** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#288]
we are currently looking at some snow variables and have got a bit confused around cell_methods and words appearing in the comments and descriptions.

As I understand it when you have `cell_methods: area: mean where land` this means you consider ONLY the land portion of the grid box in the mean.  A diagnostic that is 1 over land, but in a grid box that is only half land would have a grid box `area: mean where land` as 1 (an `area: mean` would be 0.5).  Grid boxes where there is no land should have missing values (consistent with https://www.earthsystemcog.org/projects/wip/time_averages).  Does this all sound right?

Some diagnostics (like snm LIMon) have `cell_methods: area mean where land` but has a comment that says `report as 0.0 where the land fraction is 0`, but a description that says `report as zero for snow-free land regions and missing where there is no land.`.  Can we ignore the comments that talk about reporting as 0 where the land fraction is 0 (for `cell_methods: area: mean where land`').

Are there any diagnostics where you really want a `0` over non-land points yet have a `cell_methods: area: mean where land`?  If there are any then can you clarify what you want at coastal points - I assume you still don't count non-land as '0' in the mean on these points.

thanks
Jamie

**Comment by martinjuckes** [comment]
Please ignore the comments and report as missing where there is no land .. I'll try to clean up the comments in the next release. I believe this only applies to `snm` and `snmIs`.

Variables with `area: mean where land` should always be marked as missing when there is no land and the mean is consequently undefined.

**Comment by jkettleb** [comment]
thanks Martin - its good to have the clarification.
