### ISSUE TITLE
Inconsistency with tsl?

### ISSUE THREAD

**Issue by ehogan** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#289]
Hi Martin,

I believe there may be an inconsistency with `tsl` (see [here](http://clipc-services.ceda.ac.uk/dreq/u/3fd3cb4e2d6dd15b7dd73def96fea129.html)).

The `description` for `tsl` includes "Temperature of each soil layer". The dimensions for `tsl` for `Eday` and `Lmon` is specified as "Global field on soil levels", while `tsl` for `6hrPlevPt` is specified as "Global field (single level)". Is there a reason `tsl` for `6hrPlevPt` is specified for a single level rather than all soil levels as for `Eday` and `Lmon`?

**Comment by martinjuckes** [comment]
I'll check with the HighResMIP team.

**Comment by martinjuckes** [comment]
HighResMIP only want the near surface soil temperature, so the dimensions are correct and the description needs to be corrected. I've done this for 01.00.21.

**Comment by ehogan** [comment]
Great, thanks Martin :)
