### ISSUE TITLE
combining MIP tables for CMOR

### ISSUE THREAD

**Issue by taylor13** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#29]
Hi Martin, 

Ideally, the number and names of MIP tables in the dreq would be identical to those used as input to CMOR, but currently the number of tables has grown from 18 in CMIP5 to 48 in CMIP6.   As you know a table name appears in each file name, so I'd like to reduce the number of tables folks need to recognize (and use easily interpretable names for these).  

It is not absolutely essential for the arrangement into tables of the variables in your data request to be exactly the same their arrangement in CMOR tables (but we should be able to map from your tables toe CMOR's). 

 In CMIP5 we started out with a philosophy that a single file would contain all the variables sampled at a given frequency for a given model component (atmosphere, ocean, land, land ice, sea ice, aerosol, and cloud-related (CFMIP)), but there were several exceptions.  We decided

1) to put all monthly variables in a single table, whether or not they were climatological monthly means or means of individual months (so file included two "frequencies": "mon" and "monclim").
2) to construct separate tables for variables stored on pressure levels and for the same variables stored on model levels (even though they both were sampled at the same frequency)

Treating "CF" atmos. variables in a different table from other atmos. variables sampled at the same frequency) wasn't really that consistent with our philosophy, but we did this partly because we hadn't formally defined "variable groups", and the CF variables were collected from only a subset of the CMIP5 experiments/time periods.

For CMIP6 (with variable groups now defined), I think it could make sense to more strictly follow the general approach established in CMIP5, and to minimize the number of CMOR input tables.  

Instead of the current 48 tables in the data request, I think we could possibly get away with just the following tables (organized in a sparsely filled component x frequency matrix, except for "fx" which spans all components):

fx
Oyr, LIyr, aeryr
Amon, Omon, Lmon, LImon, SImon, aermon
Aday, Oday, SIday, aerday
A6hrLev, A6hrPlev
A3hr
A1hr, aer1hr
Asubhr

If only a few variables are included in Oday, SIday, and aerday, we could even consider combining these into a single table (like fx) called "day".

I'm not suggesting that these 20 tables will meet _all_ the needs of the data request, but perhaps along with the "variable groups" now defined, they might.  In any case I think they could meet the needs of CMOR and perhaps more importantly the DRS, and would make the CV for "table_id" much shorter.  Can you say why this short list of CMOR tables might not meet our needs?  Also, would it be practical to limit/align your data request tables with those listed above? 

thanks,
Karl

**Comment by martinjuckes** [comment]
I think it is essential to have the MIP tables in the request the same as those used by CMOR ... I don't see how we can keep track of things if we start using different table names. In our earlier discussions I thought it was understood that CMOR would use the tables defined in the data request.

We had discussions within the WIP and arrived at the conclusion that it would be good to separate ocean and atmosphere daily variables, and also to try to have a single "frequency" per table (as in a single value of the DRS "frequency" ... which has separate value for climatologies).  These changes would be fairly easy to undo, but it would go against the conclusion of the WIP discussions. I don't think the fact that increasing table numbers is a problem for CMOR was raised in the earlier discussion .. so we could of course revisit the discussion.

We also had a broader discussion about using separate tables for zonal means and to deal with cases in which there are both instantaneous and time mean versions of a variable requested at a given frequency. This leads to the presence of "6hrPlevpt" and "emDayZ", for example. This was to avoid having new variable names (e.g. uaz, or uapt). If we remove these tables we will need another approach to avoid file name ambiguity. I can't say that is impossible, but I don't have a clear alternative in mind.

For ISMIP we have variables requested on (a) global, (b) Antarctic and (c) Greenland grids. They could be put into the same table if it is clear that file name uniqueness will be preserved by the grd labels, but I think the separate tables make things clearer for the users.  

For tables like emDay, for instance, it may be possible to combine this with "day" ... it is separate to avoid confusion between the core daily variables and variables which are only requested for specific MIPs.  This could also lead to file naming problems.

I don't understand what the needs of the DRS are in this respect ... the DRS has some short vocabularies and some long ones .. there doesn't appear to be a clear need to keep it short. On the other hand, it is clear that there is room for improvement ... but also quite a lot of issues associated with the greater complexity of CMIP6 relative to CMIP5,

regards,
Martin
