### ISSUE TITLE
OMIP Standard names

### ISSUE THREAD

**Issue by martinjuckes** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#291]
@durack1 : There are now just one OMIP variable which is missing a standard name:
sossq Square of Sea Surface Salinity

It looks like an easy variation of the standard name used for tossq (square_of_sea_surface_temperature) ... do you know if `square_of_sea_surface_salinity` has been requested?

**Comment by durack1** [comment]
@martinjuckes thanks for pointing that out, I did think that it was requested, but upon a re-check it seems to have slipped through the cracks. I sent a new standard name request through to the CF mailing list just now, so hopefully this is approved quickly.

http://mailman.cgd.ucar.edu/pipermail/cf-metadata/2018/059853.html
