### ISSUE TITLE
landCoverFrac vegtype dimension?

### ISSUE THREAD

**Issue by jkettleb** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#296]
landCoverFrac has a vegtype dimension.  vegtype dimension has a description 'plant functional type. Several plant functional types have been defined in the area_type table available at: cf-pcmdi.llnl.gov/documents/cf-standard-names/area-type-table/current/'

but landCoverFrac is non-veg area_types as well isn't it? So vegtype doesn't seem quite right.

**Comment by martinjuckes** [comment]
True ... this is a problem inherited from CMIP5, also mentioned here: https://www.earthsystemcog.org/projects/wip/area_coverage . It has not been possible to find a clean approach within the CF Convention, so the attributes have been left unchanged. We could clear up the name and description though. Can you suggest something (I'm on leave this week)?

**Comment by jkettleb** [comment]
how about a description like `land cover type. Several land cover types have been defined in the area_type table available at: cf-pcmdi.llnl.gov/documents/cf-standard-names/area-type-table/current/`?

**Comment by martinjuckes** [comment]
Since the table does not cover all the types which we expect to be use (and has moved), how about: `Vegetation or land cover type. Where possible, please use terms from the CF Convention Area Type table: http://cfconventions.org/Data/area-type-table/6/build/area-type-table`

**Comment by taylor13** [comment]
I think pointing to cfconventions.org is he right thing to do.  @jkettleb please note:  "vegtype" is the data request and CMOR table entry name, but the "altLabel" (aka "outname") is the generic "type", which will be more correct since non-veg area_types could appear (as you note).  

Also note that the list of "area types" found in http://cfconventions.org/Data/area-type-table/6/build/area-type-table includes much more than just vegetation descriptors.  Hopefully, it is complete enough that most models will be able to describe their surface types using only descriptors appearing in the table.

**Comment by jkettleb** [comment]
great, thanks for following this up - I'm happy with the explanations and outcome.

**Comment by martinjuckes** [comment]
Hi @taylor13 , in CMIP5 a lot of models used non-standard descriptors -- listed here: https://github.com/cmip6dr/CMIP6_DataRequest_VariableDefinitions/blob/master/cmip5_landCoverUsage.xls . Of the 44 different types used, there are about 6 which clearly correspond to names in the table, the rest do not. 3 look like errors  (`n`, `b`, and `c` from BNU), but others, e.g. `boreal_evergreen`, `temperate_evergreen`, `extra-tropical evergreen trees`, are more specific than the terms in the CF list. Most of these are only used by one modelling centre. When I raised this on the CF discussions list a couple of years ago the consensus was that the CF list should not be used for specialised area types which are only used by one model (e.g. CSIRO has additional distinctions between `needleleaf` and `broadleaf`, but does not distinguish between `temperate` and `boreal`). So, I expect we will get a similar diversity in CMIP6, but the above definition allows for that.

**Comment by martinjuckes** [comment]
Another question @taylor13 : would it be worth changing the name of the coordinate variable, currently `vegtype`, as used in CMIP5? As pointed out by Jamie, this variable name is slightly mis-leading. We also have a `typeveg` coordinate, which is just for `area_type=vegetation`, which could lead to confusion. On the other hand, it is just a label and we have clearer terms in the long name and description ... so perhaps we should leave it for now.

**Comment by jkettleb** [comment]
It could be changed to 'surfacetype' maybe - though now the description is a little tidier this may not be high priority.  As Karl @taylor13 points out the name in the output it 'type'.  

On reflection I also wonder how much use this diagnostic gets - the specific vegtypes (grassFrac etc) are much more useful in a multi model context. (I'm not suggesting dropping landCoverFrac - just prioritising efforts in the data request appropriately.  I think I should have thought of this from the outset - hope I've not wasted too much time, sorry).

**Comment by martinjuckes** [comment]
OK .. it was not used much in CMIP5 ... one variable supplied by 6 institutions (14 models). In CMIP6 it is still only used in one variable, but there could be more institutions providing it. It was priority 2 in CMIP5, but VIACSAB and PMIP want it at priority 1 in CMIP6 ... so it is likely to be provided by more groups. 

It is good to have the name clarified.   I've also added a link to discussion in the "cmip7_forward_look" issue on `area_type` ... so we can take it up again, or avoid repeating the discussion.

**Comment by taylor13** [comment]
Let's wait to make any changes to this until CMIP7.  There are much higher priority problems to deal with.  [But the good ideas suggested above should not get lost, so thanks for linking with cmip7_forward_look.]
