### ISSUE TITLE
Additional C4MIP variables

### ISSUE THREAD

**Issue by martinjuckes** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#298]
cVegCrop, cLitterCrop, cSoilCrop, gppCrop, nppCrop, raCrop, rhCrop, cVegPast, cLitterPast, cSoilPast, gppPast, nppPast, raPast, rhPast.  (with Past --> Pasture to avoid confusion with times past).

Same as tree, grass,  shrub, crop, and pasture equivalents

**Comment by senesis** [comment]
As far as I understand, these variables here are just given values (crops,pasture) of the landUse dimension of other variables which are already duly defined in DR01.00.20 : gppLut, cVegLut, cLitterLut, cSoilLut, nppLut, rhLut

Examples 
    gppCrop=gppLut[crops] (=gppLut[3])
    cVegPast =cVegLut[pastures] (=cVegLut[2])

So, if I am right, defining and requesting new variables could generate double production , double store and users being lost

**Comment by martinjuckes** [comment]
It may make sense to just include a request for these variables in the C4MIP request rather than adding new variables?

**Comment by senesis** [comment]
I think so

**Comment by martinjuckes** [comment]
Closed due to inactivity.
