### ISSUE TITLE
Wrong dimensions in jpdftaureliqmodis and jpdftaureicemodis

### ISSUE THREAD

**Issue by alejandrobodas** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#299]
Somehow, the issue reported in #187 is still there. The dimension **plev7c** needs to be deleted from these variables. The correct dimensions are:

- jpdftaureliqmodis: longitude latitude effectRadLi tau time
- jpdftaureicemodis: longitude latitude effectRadIc tau time

**Comment by martinjuckes** [comment]
Sorry for this -- fixed in 01.00.22

**Comment by alejandrobodas** [comment]
That's great, thank you.
