### ISSUE TITLE
dim:scatratio shouldn't have a 'value'

### ISSUE THREAD

**Issue by senesis** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#301]
This dimension has its attribute value which is the set with the list of requested values. This breaks the rule that only singleton dimensions have a 'value'

**Comment by martinjuckes** [comment]
That makes sense ... is this rule documented somewhere?

**Comment by senesis** [comment]
Yes, it is part of a draft CMIP6 specification by Karl Taylor. Please see this [comment](https://docs.google.com/document/d/1os9rZ11U0ajY7F8FWtgU4B49KcB59aFlBVGfLC4ahXs/edit?disco=AAAABoAcja4)

**Comment by senesis** [comment]
Sorry, the right reference to draft CMIP6 spec stating that only scalar should haev a value is [through this comment](https://docs.google.com/document/d/1os9rZ11U0ajY7F8FWtgU4B49KcB59aFlBVGfLC4ahXs/edit?disco=AAAABqGRTqs)

**Comment by martinjuckes** [comment]
Thanks .. I'll correct it in 01.00.22
