### ISSUE TITLE
Usage summary for group on DR website ?

### ISSUE THREAD

**Issue by MichaelSchulzMETNO** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#302]
Hi, 
I was trying to find out for which experiment a variable group is used. And on the data request website, when eg clicking to 3.1 request variable group [aer6hr] , there is a link appearing
"Usage summary for AerChemMIP 6 hourly data".  

Unfortunately that link seems broken. I tried also a few other groups, same result, no link to a html side.

It would be very useful to check this way whether a variable group is asked for the right experiments,

thanks for looking into this
Michael

**Comment by martinjuckes** [comment]
Thanks for pointing that out .. I've fixed it now.
