### ISSUE TITLE
typec3pft and typecrop cannot have the same altLabel

### ISSUE THREAD

**Issue by senesis** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#303]
Because altLabel must translate in NetCDF dimension name, and because these two grids/dimensions (typec3pft and typecrop) are joint dimensions of e.g. cropFrac3, they cannot have the same altLabel (currently : 'type') 
This also applies to typec4pft
After scrutinizing structures, it appears that changing altLabel value to label value for those two dimensions (typec3pft and typec4pft) would avoid any problem

**Comment by taylor13** [comment]
There are additional, somewhat related issues, raised earlier (see #274 ) that could perhaps be addressed along with the issue raised here.

**Comment by senesis** [comment]
But you wrote in that issue 

> Correction to point 5 above: We can't remove "typecrop" because then the only way to distinguish the two area_fractions would be by reading the long_name (which is not standardized).

So, the current issue is still alive
CNRM-CERFACS and IPSL  will use altLabel=pfttype (which translates in CMOR parlance as :"out_name=pfttype")

**Comment by martinjuckes** [comment]
New composite area types have now been added to the CF area type, so this usage of pairs of area types will be removed in 01.00.24

**Comment by taylor13** [comment]
Just to be clear here (because it could save us an enormous amount of work extending CMOR3 to treat this special case):  Have you found a way to replace the dual singleton dimensions (typec3pft and typecrop) with a single descriptor for the "type"?  That would be excellent from our perspective.

**Comment by martinjuckes** [comment]
Yes, we have a CF area type of `crops_of_c3_plant_functional_types` and a associated new coordinate `typec3crop`, and similarly for c4.

**Comment by taylor13** [comment]
Great! Thanks again.

**Comment by taylor13** [comment]
@doutriaux1  I think this issue can be closed.

**Comment by senesis** [comment]
Even if a DR version does address this issue, some modeling centers had to choose an earlier DR version for starting production; so closing this issue shouldn't lead to a dead-end for them, regarding publishing tools and data. 

Reminder of  our decision, stated above :
> CNRM-CERFACS and IPSL will use altLabel=pfttype (which translates in CMOR parlance as :"out_name=pfttype")

**Comment by taylor13** [comment]
My understanding is that PrePARE doesn't check coordinate information, so you shouldn't be affected.  Please let me know if this isn't the case.
