### ISSUE TITLE
coordinate variable bounds and limits

### ISSUE THREAD

**Issue by taylor13** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#305]
I've noticed the following possible mistakes in the coordinate variables:

1)  alt16:  The first coordinate value is supposed to represent the surface (or a very thin layer at the surface), so I would place bounds at -1 meter and 0 meter.  No reason to allow the surface to be at -99000, the current lower limit.

2) depth2000m:  For consistency with other variables, the valid_max value should probably be 2020 (not 2200).

3) sdepth1:  see https://github.com/PCMDI/cmor/issues/294 ; change valid max to 0.1 

4)  typewetla: since no appropriate area_type label yet exists for wetland, I suggest we remove standard_name = "area_type" from typewetla and provide value = "wetland" or "wetlands".  This will make the file CF-compliant. 

5) scatratio: This includes "value" and "boundsValues", but it shouldn't.  Those are reserved for scalar coordinates and should be left undefined for scatratio.  ["requested" and "boundsRequested" are used to specify the information.]

**Comment by martinjuckes** [comment]
1. This is the `altitude` above the geoid, rather than `height` above the surface, so models could have the surface at a negative altitude (e.g. the Dead Sea has a surface area of 605km<sup>2</sup>, which is enough to be represented in some models, and an `altitude` of -450m.  I agree that -99000m is excessive, but we should allow for realistic negative values. How about *-500m*?

2. OK

3. OK .. also sdepth10 changed to valid max 1.

4. OK 

5. OK

**Comment by taylor13** [comment]
Concerning 1) above, we can't permit the height coordinate (or its bounds) to depend on location (i.e., lat and lon), so a specific nominal value will have to be specified.  I think we should check with the MISR and COSP simulator folks and get some advice.  Shall I contact them or do you want to?

**Comment by martinjuckes** [comment]
Clearly the coordinate value is constant: as I understand, the value of `clmisr` in the lowest layer represents the cloud cover between `altitude=0m` (i.e. the geoid) and the Earth's surface in those regions where the Earth's surface is below the geoid. If they set the lower bound of the layer to be `-1m`, it would exclude all cloud between `-1m` and lower regions of the Earth's surface and I can't see why they would want to do this (I have checked with Mark before about the interpretation of "cloud" here, and I believe it refers to any condensed water vapour, including fog and mist). The satellite measures down to the Earth's surface: surely we should define the lowest layer to extend down far enough to capture the full range of the instrument?

**Comment by taylor13** [comment]
I have written again to the COSP simulator folks for guidance.  I agree we should define the lower bound low enough to include any information provided by the simulator.

**Comment by taylor13** [comment]
from Roj Marchand:

Please find answers to your questions, interspersed below.

> 1) Is it appropriate to include height bounds (i.e., does the simulator
calculate cloud fraction within specific height limits or is it
calculating an integrated quantity like "cloud fraction above each
specified height")?

These are height boundaries for cloud-top.

Meaning, if a region was 50% covered by clouds and half the time MISR would cloud top was exactly 11 km and half the time cloud top was at 1.3 km, then the cloud fraction (summed across all optical depths columns) would equal 25% for the row corresponding to 11000 >= CTH > 13000 m and 25% for row corresponding to 1000 >= CTH > 1500 m.

So, yes, I think it is appropriate.


> 2) Are the heights "elevation above sea level" or "distance above the
earth's surface"?

It is cloud-top-height above mean sea level.

However, the first row ( -1000 to 0 m) is NOT for clouds below sea level.  Rather, in the observational data product it stores the occurrence of failed CTH retrievals; meaning a cloud is present (with the given optical depth) but CTH could not be determined.  The MISR simulator does fully emulate retrieval failures.


> 3) Should cloud fraction be reported as "missing" or should it be set to 0  when a specified height is locally below ground level?

I am not entire sure I understand the question.   The purpose of the MISR simulator is to estimate the CTH that MISR will retrieve given the model profile of visible extinction and to aggregate/output the CTH-OD cloud fractions.  You should not be setting the MISR CTH or the cloud fractions.

4) For the lowest height specified (0 m), does this represent all clouds below sea level?  If so, this would be needed only at a few places. That seems odd to me.

No.   See answer to question 2.

**Comment by taylor13** [comment]
@martinjuckes followed up with:

thanks for explaining that, I had mis-interpreted the specifications.

I have a follow-up question about profiles where the land surface is below sea level. E.g. if there is a layer of mist 100m thick  over the Dead Sea, which would then extend from roughly 400 to 300m below sea level. Would MISR measure this as cloud? If so would you expect it to be recorded in the lowest data value?

The CF metadata currently defines the 2nd data row to cover the range 0 to 500m above sea level, implying that cloud below sea level would be ignored. If it is intended to include cloud down to the surface, we should extend the lower bound to below the lowest point of the Earth's surface.

Karl's comment about missing value relates to profiles where the layers specified by the vertical coordinate are completely below the Earth's surface. E.g. in the Himalayas there is no atmosphere in the layer 0 to 500m above sea level. In CMIP we generally ask providers to set the data array to the "missing value" flag at such points: this is a special data value (usually 1.e20) which is reserved to indicate absent data. If there is, however, a different convention for MISR retrievals (e.g. saying there is zero cloud between 0 and 500m in the Himalayas) and you want to stick with that approach, we can do that. But we do want to signal to users what this approach is.

The inclusion of an error flag in the lowest row creates a technical problem as far as CF metadata goes, but I think we should not worry too much about that now (there was a related discussion back in 2016 about how to reconcile this reasonably common practise with the rules of the CF convention, but we did not reach a conclusion: http://mailman.cgd.ucar.edu/pipermail/cf-metadata/2016/059037.html ). The important thing at this point, I think, is to make the descriptions in the metadata clear.

For the altitude coordinate, I'd like to replace the current phrase "MISR vertical coordinate heights" with "MISR vertical coordinate heights (first row is reserved for the retrieval error flag)"

And for the variable clmisr, replace "MISR cloud area fraction" with "MISR cloud area fraction (including retrieval error flag in first layer)".

People will have to go to the MISR documentation to really understand what is going on, but these comments are intended to point people in the right direction: is the wording appropriate, or could you suggest something clearer?

**Comment by taylor13** [comment]
I think all but item 1) above have been fixed in release 01.00.22.f

**Comment by martinjuckes** [comment]
Yes, all but item 1 fixed in 01.00.22. In 01.00.24 I'm implementing the changes set out in my last comment, i.e. changing the titles and descriptions to draw attention to the fact that the first layer in the profile is an error flag, not a data value. Since the first layer is not a true vertical coordinate, I'll leave the unphysical lower bound. I've made a note of the fact that this is not entirely consistent with the intention of the CF convention here: https://github.com/cmip6dr/cmip7_forward_look/issues/19
