### ISSUE TITLE
Time-slice output CFMIP fields in E3hrPt aren't identified as time-slice

### ISSUE THREAD

**Issue by ceblanton** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#307]
We at GFDL are preparing diagnostics for the amip experiment and we've identified an inconsistancy in how the time-slice fields are identified.

CFMIP requests high-frequency (3-hourly) output for 2008 only, for fields in tables 3hr (e.g. tas) and E3hrPt (e.g. clisccp).

In the former case, the fields are identified as time-slice output within the "Request item" record (http://clipc-services.ceda.ac.uk/dreq/u/049138e4-5032-11e7-a569-5404a60d96b5.html), as the "tslice" attribute. In turn, that points to the timeSlice record that clearly identifies those fields as "single year for high frequency data" for 2008.

In the latter case, the fields are not explicitly identified as time-slice output. The "Request link" record (http://clipc-services.ceda.ac.uk/dreq/u/efc0d062-5629-11e6-9079-ac72891c3257__00.html) identifies these fields as "3-Hourly COSP Inputs and Outputs (2008 only)" within the comment attribute. The "Request item" record (http://clipc-services.ceda.ac.uk/dreq/u/93f5753e-267c-11e7-8933-ac72891c3257.html) correctly identifies the field as having a maximum of 1 year, but doesn't have a "tslice" attribute. As a result, the generated spreadsheets for these fields show "ALL" in the "number of years" column. Moreover, these fields aren't properly identified as timeSlice output within the other cross-referenced pages of the Data Request (http://clipc-services.ceda.ac.uk/dreq/index/timeSlice.html).

Please add the explicit time slice specification to the E3hrPt fields, to be consistent with the other time-slice fields.

**Comment by martinjuckes** [comment]
Thanks for pointing this out, corrected for 01.00.22
