### ISSUE TITLE
cropFracC3 and cropFracC4 structure seems odd

### ISSUE THREAD

**Issue by senesis** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#308]
Their shape shows as :
     Percentage Cover by C3 Crops ... [XY-na] {typec3pft :typecrop} [amnlax-tmn]]
while, because typec3pft is a scalar, it should rather shows as :
     Percentage Cover by C3 Crops ... [XY-na] {:typec3pft typecrop} [amnlax-tmn]]
Maybe it is only an issue with the print method used for the html pages ?

**Comment by martinjuckes** [comment]
This is just a typo -- corrected in 01.00.22
