### ISSUE TITLE
Should a field with 'bgzmean' cellmethod have dimension 'latitude'

### ISSUE THREAD

**Issue by senesis** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#309]
Structure [str-h009](http://clipc-services.ceda.ac.uk/dreq/u/529d9136-1ed7-11e7-9366-ac72891c3257.html) applies to variable mstfmyz . It has cell method 'bgzmean' and one  one of its dimension is 'latitude'; 

Using a latitude dimension which is only approximately true for an average along grid i-direction when the grid is not rectilinear lat-lon

Should this 'latitude' dimension be used anyway ?

**Comment by taylor13** [comment]
@senesis  ... I think so.  If you don't have a spherical coordinate latxlon grid, you are expected to follow a "zig zag path" in calculating these zonally-averaged quantities.  You can then think of the j-coordinate as a nominal latitudinal location.  See https://www.earthsystemcog.org/projects/wip/zonal_means .

**Comment by martinjuckes** [comment]
@senesis is right here ... sorry for the delay in answering. The zig-zag path @taylor13 mentions is for variables with cell-method 'bzzmean'. In the data request, as in CMIP5, having `latitude longitude` specified as dimensions does not mean that these dimensions should necessarily be used: in many cases they need to be replaced by the model coordinates. In CMIP5 this approach was also used for this class of variables, even though they are *only* required when the model has a non-spherical grid. It would make more sense for them to be requested with `grid_latitude` as a coordinate: I'll implement that.
