### ISSUE TITLE
rls standard_name and postive inconsistent

### ISSUE THREAD

**Issue by jkettleb** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#310]
rls has a standards name `surface_net_downward_longwave_flux`, yet positive `up`.  I think this is a typo in the positive attribute.

http://clipc-services.ceda.ac.uk/dreq/u/3e7348adedb540627808da06a211c81c.html
http://clipc-services.ceda.ac.uk/dreq/u/surface_net_downward_longwave_flux.html
http://clipc-services.ceda.ac.uk/dreq/u/8b922368-4a5b-11e6-9cd2-ac72891c3257.html

**Comment by taylor13** [comment]
Not directly relevant, but I note that viacsab seem to request both the net and the downwelling and upwelling components of the SW and LW daily fluxes.  Since net can be computed from the two streams, it could be eliminated.

**Comment by jkettleb** [comment]
I think the initial query has been fixed a 1.00.22?

**Comment by martinjuckes** [comment]
yes, resolved in 01.00.22
