### ISSUE TITLE
Time slices abrupt<xx> have relative start

### ISSUE THREAD

**Issue by senesis** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#311]
Timeslice http://clipc-services.ceda.ac.uk/dreq/u/_slice_abrupt5.html has start=0

This constrast with timeslices for other experiments, which have rather start value as e.g. 1980.
The reason surely is that abrupt is an academic run, with no relationship with actual, real-world, years, which start year can be set to any value (including 0, or 1). But it would be handy (for CMIP7) to have a flag in timeslices stating how to interpret start (relative/absolute)

Also having start=0, end=5 and nyears=5 is not consistent

**Comment by taylor13** [comment]
seems like a good idea for such a flag.
If "5" is interpreted as "5.0", Then nyears = 5.0 is correct, no?

**Comment by martinjuckes** [comment]
OK, but I think we need 3 categories: absolute (a "true" date), relative (relative to some point in the experiment), and perhaps `matching`, as in "Years matching last 20 years of the historical experiment" which is specified for some data from piControl.

Stephane is correct that start 0, end 5 and nyears=5 is inconsistent with usage in other timeslices ... e.g. we have start 121, end 150 and nyears=30 in http://clipc-services.ceda.ac.uk/dreq/u/_slice_abrupt30.html , so I think we should change this. The output should start at the beginning of the experiment, and I would favour labelling that year 1, and hence start=1 (as used in CMIP5).

**Comment by senesis** [comment]
tslice.type=="branchedYears" is also a good criterion for proposed category 'matching'.

**Comment by martinjuckes** [comment]
OK, perhaps we can also use a `tslice.type` value for the relative values. For consistency, http://clipc-services.ceda.ac.uk/dreq/u/_slice_abrupt5.html should be the same as http://clipc-services.ceda.ac.uk/dreq/u/_slice_VolMIP3.html , which has `tslice.type="startRange"` . Would it be OK if I set all 3 to `tslice.type="relativeRange"`, and update the _slice_VolMIP3 record to have a start and end year similar to _slice_abrupt5 ?

**Comment by senesis** [comment]
That's fine. I assume that I can anticipate on this change for letting dr2xml handle this new type.
(And that 'the three' are : abrupt30, abrupt5 and volMIP3)

**Comment by martinjuckes** [comment]
Yes, I'll implement that ... it is a simple modification ... and I don't think there are many people looking at this detail yet.

**Comment by martinjuckes** [comment]
Done
