### ISSUE TITLE
__unset__ long name

### ISSUE THREAD

**Issue by taylor13** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#312]
could you please define the following long names, which currently are set to "__unset__"?

opottempmint (in Emon): Integral with Respect to Depth of Product of Sea Water Density and Potential Temperature

pathetao (in Emon):  Sea Water Additional Potential Temperature

prthetao (in Emon):  Sea Water Redistributed Potential Temperature

opottempmint (in Oyr):  Integral with Respect to Depth of Product of Sea Water Density and Potential Temperature

**Comment by martinjuckes** [comment]
Fixed
