### ISSUE TITLE
01.00.22: Dimension changes in many ocean bgc variables

### ISSUE THREAD

**Issue by matthew-mizielinski** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#314]
In version 01.00.22 of the data request 52 variables had their dimensions changed from `longitude latitude olevel time` to `longitude latitude time depth0m`, for example `Omon/no3`.

I can't see this change signposted in the [release notes](https://www.earthsystemcog.org/projects/wip/drq_release_01_00_22), and there are now a number of variables that look like duplicates, e.g. `Omon/no3` and `Omon/no3os`, `Omon/o2` and `Omon/o2os`. It may be that there is something subtly different between surface values and those in the top ocean layer, but if so it would be good to have something to clearly signpost this.

@martinjuckes, could you confirm that this change is as expected and if so should these variables be merged?

**Comment by martinjuckes** [comment]
I think this has now been fixed.
