### ISSUE TITLE
Wrong vertical coordinate in RFMIP 3D fluxes

### ISSUE THREAD

**Issue by alejandrobodas** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#317]
Many of the RFMIP 3D fluxes have  _alevel_ as vertical coordinate, when they should have _alevhalf_. These are the entries affected, with corrections in bold:

rld{Efx}  **alevhalf** spectband

rlu{Efx}  **alevhalf** spectband

rsd{Efx}  **alevhalf** spectband
rsdcsaf{E3hrPt}  longitude latitude **alevhalf** time1
rsdcsafbnd{E3hrPt}  longitude latitude **alevhalf** spectband time1
rsdcsbnd{E3hrPt}  longitude latitude **alevhalf** spectband time1

rsu{Efx}  **alevhalf** spectband
rsucsaf{E3hrPt} longitude latitude **alevhalf** time1
rsucsafbnd{E3hrPt} longitude latitude **alevhalf** spectband time1
rsucsbnd{E3hrPt}  longitude latitude **alevhalf** spectband time1

**Comment by alejandrobodas** [comment]
@RobertPincus cc Robert so that he's aware of this issue.

**Comment by RobertPincus** [comment]
This refers to requests for RFMIP-IRF-AER, I believe. I will entrain the relevant folks and get back to you.

**Comment by drfeldman2012** [comment]
Thanks for bring this to our attention.  The RFMIP 3D flux fields should indeed have _alevhalf_ as their vertical coordinate, especially to remain consistent with other standard flux fields such as rsucs and rsdcs.

For RFMIP-IRF-AER, benchmark radiative transfer results will be output at the boundaries of the layers, so the outputted fluxes will be on _alevhalf_.

With respect to the RFMIP-IRF-AER investigation, the fields for which it is most critical that we report at  _alevhalf_ are rsucsaf, rsdcsaf, rsucsafbnd. rsdcsafbnd, rsucsbnd, and rsdcsbnd.  Please comment on the feasibility of fixing this for the CMIP6 Data Request.

**Comment by martinjuckes** [comment]
Corrected in 01.00.24 -- thanks for pointing this out.
