### ISSUE TITLE
v01.00.22: Standard names swapped in two variables?

### ISSUE THREAD

**Issue by matthew-mizielinski** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#318]
I've just noted that the standard names assigned to two variables look like they are the wrong way around;

 * `EdayZ/utendvtem`: `u-tendency_by_wstar_advection`, [see here](http://clipc-services.ceda.ac.uk/dreq/u/590e48f4-9e49-11e5-803c-0d0b866b59f3.html)
 * `EdayZ/utendwtem`: `u-tendency_by_vstar_advection`, [see here](http://clipc-services.ceda.ac.uk/dreq/u/590e883c-9e49-11e5-803c-0d0b866b59f3.html)

**Comment by martinjuckes** [comment]
Updated to:

utendvtem: tendency_of_eastward_wind_due_to_advection_by_the_northward_transformed_eulerian_mean_air_velocity
utendwtem: tendency_of_eastward_wind_due_to_advection_by_the_upward_transformed_eulerian_mean_air_velocity

These are provisional names, which will be moving through the approval process soon.
