### ISSUE TITLE
"comment" in cell_methods attribute

### ISSUE THREAD

**Issue by taylor13** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#319]
@wachsylon This issue is being transferred from https://github.com/PCMDI/cmip6-cmor-tables/issues/165.  
```
Hi,
in SImon, variable sithick has:
"cell_methods": "area: time: mean where sea_ice (comment: mask=siconc or siconca)".
The CF conventions 7.3.2. say:
"If there is both standardized and non-standardized information, the non-standardized follows the
standardized information and the keyword comment: . If there is no standardized information, the
keyword comment: should be omitted".
Therefore, the comment for sithick should be omitted, shouldn't it?
Thanks and best regards,
Fabi
```
I think Fabi is correct, and there are many occurrences of this problem.  It doesn't seem that high priority to me unless the CF-checker objects.  Anyone know if it does?  @senesis?

**Comment by martinjuckes** [comment]
The CF checker shouldn't object, as non-standardized information is not standardized ....

**Comment by senesis** [comment]
As far as I remember; it does not object.
