### ISSUE TITLE
Variables fracLut and pastureFrac

### ISSUE THREAD

**Issue by wachsylon** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#321]
Hi,
variable "fracLut" has dimension landUse which requests "pastures". Additionally, "pastureFrac" has dimension "typepasture" which has the value "pastures". Both are requested for monthly mean.

"fracLut" is additionally requested for yearly frequency ("yrPt") with the comment "end of year values". Could "fracLut" be requested in the same way for a frequency "monPt" instead of "mon"? Otherwise, it may be already covered with variable pastureFrac.

Best regards and thanks,
Fabi

**Comment by martinjuckes** [comment]
fracLut also includes `primary_and_secondary_land`, `crops` &  `urban` fractions, so it is not completely covered by `pastureFrac` ... there is a `cropFrac` variable, but no single variable to match the other two. We try to avoid duplication, but it is impossible to avoid it completely ... so I think we will keep this as it is, but I will check with LUMIP.

**Comment by martinjuckes** [comment]
We won't fix this for CMIP6, but will take it into account in the future (the above link marks the connection [in github]).
