### ISSUE TITLE
cell_methods "time: point" and "time1" coordinate

### ISSUE THREAD

**Issue by taylor13** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#322]
It was reported at  https://github.com/PCMDI/cmip6-cmor-tables/issues/167 that it seemed unlikely that the following 4 variables in table SImon should actually be synoptically sampled:  sistresave, sistremax, sidivvel, sishevel.   I think it makes more sense to save time-means. (so the time coordinate should be "time", not "time1", and the cell_methods would need correcting.

We should ask the experts what they want.

Moreover, I noticed that in Table Emon, the variable  ec550aer has a "time1" coordinate but cell_methods="area:time:mean"  These two specifications are inconsistent.

**Comment by martinjuckes** [comment]
ec550aer: corrected.
