### ISSUE TITLE
Inconsistencies between standard name, description, title and units of MIP Variables and CMOR Variables

### ISSUE THREAD

**Issue by ehogan** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#325]
The MIP Variable [baresoilFrac](http://clipc-services.ceda.ac.uk/dreq/u/9cdb8d54d49e98acadd87e2a1139225e.html) has a `description` of "Percentage of entire grid cell that is covered by bare soil." and a `title` of "Bare Soil Percentage Area Coverage", which is consistent with the `units` ("%"). However, the `1.8 CF Standard Names` is [AreaFraction](http://clipc-services.ceda.ac.uk/dreq/u/area_fraction.html), which has `units` of "1". In addition, the CMOR Variable [baresoilFrac {Lmon}](http://clipc-services.ceda.ac.uk/dreq/u/baa84fd4-e5dd-11e5-8482-ac72891c3257.html) has a `description` of "fraction of entire grid cell that is covered by bare soil." and a `title` of "Bare Soil Fraction".

Interestingly, the `description` of the MIP Variable ends up in the [MIP table](https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_Lmon.json#L17) as the `comment`, while the `title` from the CMOR Variable ends up in the [MIP table](https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_Lmon.json#L17) as the `long_name`, providing inconsistent metadata. The same is true for `c3PftFrac`, `c4PftFrac`, `grassFrac`, `shrubFrac`, `residualFrac` and `treeFrac`.

[vegFrac](http://clipc-services.ceda.ac.uk/dreq/u/590e75c2-9e49-11e5-803c-0d0b866b59f3.html) is slightly different in that the `description` and `title` of the MIP Variable refer to fractions, but has `units` of "%". The same is true for `treeFracBdlDcd`.

**Comment by ehogan** [comment]
There may be other `Frac`-related variables that show this behaviour.

**Comment by martinjuckes** [comment]
They should all be %, which is consistent with the CF standard name canonical unit of "1" because it is possible to transform from fractions to percentages.

**Comment by martinjuckes** [comment]
I have updated the wording to be consistent with the units.

**Comment by ehogan** [comment]
@martinjuckes I noticed that [baresoilFrac](http://clipc-services.ceda.ac.uk/dreq/u/9cdb8d54d49e98acadd87e2a1139225e.html) still has `AreaFraction` as the standard name; should this be `AreaPercentage` or equivalent?

**Comment by martinjuckes** [comment]
The standard `area_fraction` has to be used for whether it is archived with as a fraction or a percentage, because changes of units (converting from units of `1` to `%`) don't modify the standard name. 
I've corrected a number of additional descriptions in 01.00.30: grassfrac[c3/c4], sftflf, sftgif, sftgrf, sftlf, sftof, siconc, siconca clcalipso, clmodis, climodis.
This usage of `area_fraction` causes a lot of confusion ... should probably be reconsidered in the future.
