### ISSUE TITLE
Corrections to type-related dimensions

### ISSUE THREAD

**Issue by ehogan** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#326]
[treeFracNdlEvg](http://clipc-services.ceda.ac.uk/dreq/u/59144f06-9e49-11e5-803c-0d0b866b59f3.html) has the `title` "Needleleaf evergreen tree fraction" and dimensions [longitude latitude time typetreene](https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_Emon.json#L5525). However, [typetreene](http://clipc-services.ceda.ac.uk/dreq/u/dim:typetreene.html) has the `title` "Tree area type (Narrowleaf Evergreen)". Would it be possible to change "Narrowleaf" to "Needleleaf", please? The same is true for [typetreend](http://clipc-services.ceda.ac.uk/dreq/u/dim:typetreend.html).

[typeresidual](http://clipc-services.ceda.ac.uk/dreq/u/dim:typeresidual.html) and [typewetla](http://clipc-services.ceda.ac.uk/dreq/u/dim:typewetla.html) are missing a `standardName` of [area_type](http://clipc-services.ceda.ac.uk/dreq/u/area_type.html) to match with other `type` dimensions (see, e.g. the `typetreene` or `typetreend` links above).

**Comment by martinjuckes** [comment]
typetreene, typetreend  titles updated.

I've added "area_type" standard name for typewetland, but not yet for typeresidual, as the latter does not have an appropriate CF area type.
