### ISSUE TITLE
Update description for Leaf Area Index / lai

### ISSUE THREAD

**Issue by ehogan** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#327]
Would it be possible to update the `description` for the standard name [Leaf Area Index](http://clipc-services.ceda.ac.uk/dreq/u/leaf_area_index.html) and the MIP Variable [lai](http://clipc-services.ceda.ac.uk/dreq/u/6c3e8db1b45a6ae7e80ca5a265c0fd50.html) with the `description` of the CMOR Variable [lai {Lmon}](http://clipc-services.ceda.ac.uk/dreq/u/bab0919e-e5dd-11e5-8482-ac72891c3257.html), i.e. use "a ratio obtained by dividing the total upper leaf surface area of vegetation by the (horizontal) surface area of the land on which it grows." rather than ""X_area" means the horizontal area occupied by X within the grid cell."?

**Comment by martinjuckes** [comment]
I could do, but I find this definition slightly ambiguous (is it the upper surface of each leaf, or just the top of the canopy?). How about "The Leaf Area Index is defined as half the total area of green elements of the canopy per unit horizontal ground area" (https://land.copernicus.eu/global/products/LAI )?

**Comment by martinjuckes** [comment]
I've changed the CMOR variable descriptions, and proposed a change to the standard name description.
