### ISSUE TITLE
data on model half-levels

### ISSUE THREAD

**Issue by taylor13** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#329]
Most of the model-level data requested in CMIP6 is on the "full levels".  A few variables, however, are requested on "half levels".  Atmospheric data requested on model half levels have a vertical coordinate "alevhalf" and a "Structure Title" (listed on the spread-sheet version of the data request) that includes the phrase  "on model atmosphere half-levels".  There are a number of variables (which are also a function of "spectband") that have a vertical coordinate "alevhalf", but a "Structure Title" that  includes the phrase  "on model atmosphere levels".  Maybe this doesn't matter too much, but shouldn't it read "on model atmosphere half-levels"?

**Comment by taylor13** [comment]
Also, we need to consider defining olevhalf for at least one ocean variable.

**Comment by taylor13** [comment]
closed by mistake, now reopened.

**Comment by martinjuckes** [comment]
Titles in structures fixed in 01.00.25

**Comment by martinjuckes** [comment]
Should have a olevhalf, with no bounds ......

**Comment by taylor13** [comment]
Hope this can be added for the next release.
thanks.

**Comment by martinjuckes** [comment]
olevhalf added for variable zhalfo
