### ISSUE TITLE
siconc on multiple grids

### ISSUE THREAD

**Issue by martinjuckes** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#33]
Fraction of time of ice in grid cell (a variable which can't be regridded with standard algorithms). Needs to be all grids.  (Atmosphere and ocean).

**Comment by matthew-mizielinski** [comment]
In HadGEM3 & UK-ESM1 variables in the seaIce modelling realm are produced by two different components. The CICE sea-ice model produces the majority of the variables on the tri-polar ORCA grid, but a few (eight at last count) will be generated by the atmosphere (UM) and land surface (JULES) components on a lat-lon grid.

The cmor variable `siconc` acts as a weighting factor for all sea-ice variables\* and it is not possible to re-grid this data between the two grids used in the model. As such to make use of the sea ice variables output on both grids we need to provide `siconc` on both grids. 

At present the sea-ice variables to be generated on the atmosphere lat-lon grid are only required at monthly frequency so adding an entry to the `Amon` mip table for `siconc` with the `modeling_realm` set to `atmos` would be needed to provide this data. Alternatively a new variable with a cmor name such as `siconca` could be included.

This could be a HadGEM3 specific issue, but a generic solution would be useful.

*In the UM we use a similar variable, referred to as the "Heaviside function", for pressure level data, which gives the fraction of the time that the level in question is above ground. This field is used to correct the time averaging of pressure level data.

**Comment by martinjuckes** [comment]
See also https://github.com/cmip6dr/CMIP6_DataRequest_VariableDefinitions/issues/143

**Comment by martinjuckes** [comment]
Variables siconc, siconca defined.
