### ISSUE TITLE
OMIP transects

### ISSUE THREAD

**Issue by juliedeshayes** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#330]
There seems to be an inconsistency in between the Griffies et al. (2016) OMIP paper, listing 16 transects for which to provide mass transports,  and the Data Request for CMIP6, listing only 15 transects (below):

barents_opening bering_strait canadian_archipelago denmark_strait drake_passage english_channel pacific_equatorial_undercurrent faroe_scotland_channel florida_bahamas_strait fram_strait iceland_faroe_channel indonesian_throughflow mozambique_channel taiwan_luzon_straits windward_passage
 
Compared to Griffies et al. (2016) paper (see pdf attached), that list misses Gibraltar. 
[griffies16_sections.pdf](https://github.com/cmip6dr/CMIP6_DataRequest_VariableDefinitions/files/2025755/griffies16_sections.pdf)

**Comment by durack1** [comment]
@martinjuckes the relevant information is contained in table J1 reproduced below
<img width="864" alt="180522_griffiesetal16gmd-tablej1" src="https://user-images.githubusercontent.com/3229632/40356006-c1509e14-5d6c-11e8-850b-43a3310c57f8.png">

For reference the Griffies et al 2016 GMD article can be found at https://doi.org/10.5194/gmd-9-3231-2016

@juliedeshayes @StephenGriffies

**Comment by juliedeshayes** [comment]
Besides a missing section in CMIP6 Data Request, I find it important to highlight that the order in which sections are listed in CMIP6 Data Request is different than the order in which sections are listed in Griffies et al. (2016):
CMIP6 DR lists Griffies et al. (2016) sections number 1 - 2 - 4 - 5 - 6 - 7 - 15 - 8 - 9 - 10 - 12 - 13 - 14 - 16 - 3. 
Writing the name of sections in metadata is crucial !

**Comment by durack1** [comment]
@martinjuckes the entries above are taken from the `dim:oline` definition found [here](http://clipc-services.ceda.ac.uk/dreq/u/dim:oline.html), these do not align well with those documented in Griffies et al 2016 GMD [above](https://github.com/cmip6dr/CMIP6_DataRequest_VariableDefinitions/issues/330#issuecomment-390935855)

| count | dim:oline | Griffies table J1 |
| ------------- | ------------- | ------------- |
| 1 | barents_opening | barents_opening |
| 2 | bering_strait | bering_strait |
| 3 | canadian_archipelago | caribbean_windward_passage |
| 4 | denmark_strait | davis_strait |
| 5 | drake_passage | denmark_strait |
| 6 | english_channel | drake_passage |
| 7 | pacific_equatorial_undercurrent | english_channel |
| 8 | faroe_scotland_channel | faroe_scotland_channel |
| 9 | florida_bahamas_strait | florida_bahamas_strait |
| 10 | fram_strait | fram_strait |
| 11 | iceland_faroe_channel | gibraltar_strait |
| 12 | indonesian_throughflow | iceland_faroe_channel |
| 13 | mozambique_channel | indonesian_throughflow |
| 14 | taiwan_luzon_straits | mozambique_channel |
| 15 | windward_passage | pacific_equatorial_undercurrent |
| 16 | - | taiwan_and_luzon_straits |

@juliedeshayes @StephenGriffies

**Comment by martinjuckes** [comment]
Done for 01.00.25

**Comment by martinjuckes** [comment]
I've added a note about the depth of the integral in the `mfo` variable description. Ideally this information would be encoded in the CF metadata .. but I don't think it is a priority now: https://github.com/cmip6dr/cmip7_forward_look/issues/20 .

The values should be in the CF standard region list, so I have reset `taiwan_and_luzon_straits` and `carribean_windward_passage` to  `taiwan_luzon_straits` and `windward_passage` respectively, as used in CMIP5. Please let me know if there is a problem with this.

The transects `davis_strait` and `gibraltar_strait` are not yet in the CF standard region list, so I have proposed adding them.

**Comment by senesis** [comment]
For those centers which already produced data using DR before 01.00.25, changing the strait names or ordering is acceptable only as long as centers have much flexibility, at the publication QC stage, in using home-made PrePARE tables conformant with the version of DR they use in production

**Comment by martinjuckes** [comment]
Perhaps @taylor13 can comment here ... I'm not sure how PrePARE deals with "requested" values of dimensions. I believe that "requested" does not imply "required", in which case a submission based on the 01.00.24 request and earlier would still be publishable.

**Comment by martinjuckes** [comment]
I have received confirmation elsewhere that this will not be checked by PrePARE: the values are treated as a recommendation: a potential risk to users, but OK if they use the CF attributes as defined.
