### ISSUE TITLE
RequestVariableGroup CFMIP-Omon has no requestLink

### ISSUE THREAD

**Issue by senesis** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#335]
This RequestVariableGroup is at http://clipc-services.ceda.ac.uk/dreq/u/c27e21d8-a276-11e6-bfbb-ac72891c3257.html . Lack of associated RequestLink maybe is an error ?

**Comment by matthew-mizielinski** [comment]
There are a total of 24 `requestVarGroup`s at version 01.00.24 which aren't connected (either to a `requestLink` or `requestVar` object). A quick text search of the [requestVarGroup page](http://clipc-services.ceda.ac.uk/dreq/index/requestVarGroup.html) for " 0 " (note the spaces) is the easiest way to identify these. 

I also note that there are 58  `requestLinks` (all associated with VIACSAB) which do not have a connection to a `requestItem`, e.g. [VIACSAB Arctic.1c](http://clipc-services.ceda.ac.uk/dreq/u/07ea0428-26b9-11e7-9d3d-ac72891c3257.html).

**Comment by martinjuckes** [comment]
The CFMIP Omon group is orphaned .. CFMIP have not asked for data from it.

There were problems with ingestion of the VIACSAB request, these will be cleared up in release 01.00.25
