### ISSUE TITLE
Should but cannot produce both 6hrPlev CMOR variables ua7h and ua at the same time

### ISSUE THREAD

**Issue by senesis** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#336]
Maybe this in not the best place for rinsing that issue, but Data Request content is onepart of the problem, output CMIP6 formating guidelines being the other part

[This requestItem](http://clipc-services.ceda.ac.uk/dreq/u/94031c98-267c-11e7-8933-ac72891c3257.html) requests e.g. variable ua7h.6hrPlevPt for experiment piControl, for a timeslice of 200 years (corresponding to historical + 35 years)

Meanwhile, [that requestItem](http://clipc-services.ceda.ac.uk/dreq/u/93f6e798-267c-11e7-8933-ac72891c3257.html) does request variable ua.6hrPlevPt for piControl for a timeslice of 30 years (corresponding to last 30  years of historical)

As a result, we should produce variables ua for at least 30 common years in two shapes : the one of CMOR var labelled ua, on 3 pressure levels, and the one with CMORvar labelled ua7h, on 7 pressure levels

However, CMIP6 output formating guidelines requests that both variables be labeled 'ua', both in the produced file name and for the NetCDF variable name. Which would lead to files having the same names with different content

The same issue appears for a number of variables and experiments. Among the relevant variables are ua7h, va7h, ta7h, hsifrazil2d. Among the experiments are piControl, esm-piControl, amip, historical (for ua,va,ta and -except for amip- hsifrazil), and  the list below for hsifrazil2d :

1pctCO2,1pctCO2-bgc,abrupt-4xCO2,esm-piControl-spinup,G1, G6solar, G7cirrus,hist-1950HC,hist-bgc,hist-piNTCF,historical,lfmip-pdLC,lfmip-rmLC,omip1,omip1,omip2,piControl, piControl-spinup,ssp370,,ssp370-lowNTCF, ssp585-bgc

**Comment by senesis** [comment]
Of course, the example given above can be easily solved by producing the union of levels of both variables along the union of periods of the requestItems ; but can we expect that the corresponding analysis of conflicts be done once for all rather than at each data producing center ?

**Comment by martinjuckes** [comment]
Thanks for pointing this out. For ua.day we had extensive negotiations to avoid this kind of conflict, but I had not spotted the problems with the variables you mention. I will look into it and try to produce at least an overview.

**Comment by ehogan** [comment]
See also the discussion on https://github.com/PCMDI/cmor/issues/246 :)

**Comment by martinjuckes** [comment]
Hello Stephane, I've been discussing this with Karl: for ua, va, ta we think we should change the variable name for the "7h" version to "ua7h" etc so that we have distinct output variables. For hfsifrazil it is an error in the request if only one is requested at some point: both should be there and you should supply the one which is appropriate to your model (i.e. vertically resolved if can, otherwise 2d). I'll check to see if this problem can be cleared up -- it may just be a minor change to the DAMIP request.

**Comment by senesis** [comment]
Hi,
Regarding the change in out_name for ua7h, va7h, ta7h (namely : adding suffix 7h) a decision should be made. For the time being, we at CNRM use a modified version of DR01.00.21 which alleviate the problem by producing the '7h' version (but without the 7h suffix) for all experiments which have a request for both versions but not for the same period; this allow to use an out_name without 7h suffix. So, we are not really requesting a change, but we will implement it if needed.

**Comment by martinjuckes** [comment]
For hfsifrazil I have amended the request so that the choice is always the same: produce the 3d version if it is available, otherwise the 2d version.

**Comment by martinjuckes** [comment]
This change was not implemented .. modeling groups must make a choice.
