### ISSUE TITLE
lambda550nm should not have bounds

### ISSUE THREAD

**Issue by taylor13** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#337]
The scalar dimension lambda550nm specifies the wavelength at which an optical depth is calculated.  In models, I think this is done at a single wavelength, not integrated over a range of wavelengths.  This coordinate then should *not* have bounds.  Please change the "bounds" directive from "yes" to "" (meaning "no", I presume) in the data request.

This mistake was brought to my attention by @IngoBethke who raised this issue:  https://github.com/PCMDI/cmip6-cmor-tables/issues/203

**Comment by martinjuckes** [comment]
Thanks, corrected.
