### ISSUE TITLE
Long name for latitude and longitude

### ISSUE THREAD

**Issue by ehogan** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#338]
Version 01.00.26 of the data request specifies the `title` (used as the `long_name` in the MIP tables) for latitude and longitude as [latitude](http://clipc-services.ceda.ac.uk/dreq/u/2260e24c-b894-11e6-a189-5404a60d96b5.html) and [Longitude](http://clipc-services.ceda.ac.uk/dreq/u/21ef5e4c-b894-11e6-a189-5404a60d96b5.html), respectively (note the lower case `l` at the start of `latitude`). Would it be possible to update `latitude` to `Latitude` for consistency, please?

**Comment by martinjuckes** [comment]
OK
