### ISSUE TITLE
o3ste (AERmon)

### ISSUE THREAD

**Issue by lwhorowitz** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#339]
Is a definition provided for the o3ste diagnostic? The AERmon table does not contain sufficient information to specify what is being requested.

I previously requested this information (#242), but the issue was closed with no response.

Thanks!
--Larry

**Comment by martinjuckes** [comment]
The definition will be updated to: "Stratospheric ozone tracer set to ozone in the stratosphere, then destroyed in the troposphere using the ozone chemical loss rate. Please specify the tropopause definition used." 

This implies that you can select your preferred tropopause definition, and should record this (e.g. in a comment attribute).
