### ISSUE TITLE
dms (AERmon)

### ISSUE THREAD

**Issue by lwhorowitz** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#341]
Typo in long name for "dms" (AERmon) was introduced in v01.00.27. Now "Di-Methyl Suphide (DMS) Mole Fraction". Should be corrected from "Suphide" to "Sulphide".

(Why was this longname changed from "DMS volume mixing ratio" in v01.00.26? Other tracers in this table have "volume mixing ratio" in longname, not "Mole Fraction".)

**Comment by martinjuckes** [comment]
In 01.00.26 and earlier dms had long name "DMS volume mixing ratio", but the description and standard name implied that it should be a mole fraction. The long name has been changed to make it consistent with the standard name and description.

I'll correct Suphide to Sulphide, and also change "Di-Methyl" to "Dimethyl" for consistency with dmso. "Di-Methyl" is vaild, but rare compared to "Dimethyl"
