### ISSUE TITLE
variables loadbc and loadpoa in Eday but not in Emon  

### ISSUE THREAD

**Issue by IngoBethke** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#343]
It appears that loadbc and loadpoa are missing in table Emon. These variables were requested as monthly in CMIP5 (table aero). So one would expect to find them in CMIP6_Emon together with loadss, loaddust, loadso4 etc

**Comment by martinjuckes** [comment]
I don't think they were requested by any of the MIPs, and hence they are not included. There are daily `loadpoa` and `loadbc` variables requested by AerChemMIP (in Eday).

**Comment by IngoBethke** [comment]
Thanks for checking, Martin. I guess the scientists that will work with this kind of output had their opportunity to provide input to the data request. If they are really interested in the monthly fields then they can derive those from the daily output as you suggest. I kind of expected the CMIP5 request to be a subset of the CMIP6 request but if that is not the case that's ok with me.
