### ISSUE TITLE
incorrrect description of swsffluxaero in 6hrPlevPt

### ISSUE THREAD

**Issue by taylor13** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#346]
The description of swsffluxaero in  table 6hrPlevPt is: "shortwave heating rate due to volcanic aerosols to be diagnosed through double radiation call, zonal average values required", but it appears that this should be a function of both longitude and latitude, so "zonal average required" is incorrect.

**Comment by martinjuckes** [comment]
Thanks, fixed for 01.00.28
