### ISSUE TITLE
thetaot2000, thetaot700, thetaot300 incorrect cell_methods?

### ISSUE THREAD

**Issue by jkettleb** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#347]
thetaot2000 (700, 300) are averages over depth.  Should they have a 'depth:mean' in the cell_methods and include bounds on the depth coordinate?

http://clipc-services.ceda.ac.uk/dreq/u/8b92450a-4a5b-11e6-9cd2-ac72891c3257.html

**Comment by jkettleb** [comment]
Any thoughts on this one?

**Comment by jkettleb** [comment]
thetaot should also be included in this batch of diagnostics.

**Comment by jkettleb** [comment]
Our current thinking is we'll include bounds on the depth coordinate - but it may have incorrect cell_methods.

**Comment by matthew-mizielinski** [comment]
Fixing this would require creating a new cell_methods object to represent `area: time: depth: mean`
and then attaching this to spatial structures `str-d29`, `str-d30`, `str-d32`.  The corresponding dimensions (`depth300m`, `depth2000m`, `depth700m` only ) could also do with appropriate bounds.

@martinjuckes, is this something that can be squeezed into 01.00.28 before release or are we constrained by published data (CNRM have put out these sets from their historical expt)

**Comment by jkettleb** [comment]
@martinjuckes what do you want to do with this ticket?

**Comment by martinjuckes** [comment]
I think we can add something in 01.00.29 .....

**Comment by martinjuckes** [comment]
I've created a new cell methods string for thetaot300,700,2000 and used it to modify the structure records they use; created a new structure record for thetaot, added bounds for depth2000m, depth300m and depth700m, and also changed their valid_min, valid_max and value to reflect the fact that they are layer means.

There is also an issue that these dimensions are layers (like `olayer100m`) not levels (like `depth100m`) and so, ideally, the naming should be changed. I think it is best not to do that now, but perhaps in CMIP7: https://github.com/cmip6dr/cmip7_forward_look/issues/28

**Comment by jkettleb** [comment]
Thanks Martin - leaving the name change to CMIP7 makes sense to me.
