### ISSUE TITLE
cell_methods "where" points to wrong variable

### ISSUE THREAD

**Issue by taylor13** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#348]
There are several cases (in Tables Eyr and Emon) where  ``cell_methods='area: mean where landuse'`` but "landUse" is the name of an index coordinate whereas the cell_methods should point to the auxiliary coordinate variable, which is "sector".  So the correct cell_methods specification should be: ``cell_methods='area:mean where sector'``

The CF-convention is described at http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#statistics-applying-portions.

The CMIP6 specification is given in https://goo.gl/neswPr ; see point 12 under "Requirements for coordinate variables" and point 13c under "Requirements for output variables".

**Comment by martinjuckes** [comment]
OK, I expected the coordinate variable name to be `landuse`   -- corrected.
