### ISSUE TITLE
confusion about cell_methods for vegetation fractions

### ISSUE THREAD

**Issue by taylor13** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#349]
I'm confused about how to interpret cell_methods for vegetation fractions (e.g., "cropFrac").  The cell_methods is "area: mean where land over all_area_types time: mean".  Does this give a different result from "area: mean time: mean"?

Consider a grid cell that is half land (and half sea).  Suppose we have two time samples of cropFrac (over the land-portion of the grid cell): (1/4 and 3/4).  The mean over the land-portion of the grid cell is 1/2, which get reduced to 1/4 when considering the entire grid cell.  

Alternatively, the two time samples for cropFrac for the entire grid cell are: 1/8 and 3/8.  These average to 1/4 and would be the result of a simple "area: mean time: mean".  

In general isn't "area: mean where land over all_area_types time: mean" the same as "area: mean time: mean"?  

Sorry, if I've missed something trivial.

**Comment by martinjuckes** [comment]
If the quantity in question is undefined on the on the non-land portion, you need to use `mean where land over all_area_types` to get a defined answer. The thinking here was that these variables are about vegetation categories, and the vegetation is only defined on land.
