### ISSUE TITLE
HighResMIP variables missing in 01.beta.36

### ISSUE THREAD

**Issue by matthew-mizielinski** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#35]
In making direct comparisons of the changes between the HighResMIP requests for version 01.beta.36 and 01.beta.32 for PRIMAVERA I've noticed several requestVarGroups have orphaned _all_ their variables.

**HighResMIP-3hrExtr**
_prcsh_ has gone from em3hr between version 01.beta.33 and 01.beta.35
_psl_, _ua850_, _va850_ in em3hrpt have gone -- the winds are duplicates of those in ua7h, va7h in the same table (linked to HighResMIP-3hrPlev), but they are a higher priority.

**HighResMIP-AmonConv**
_tntr_, _cl_, _mcu_, _mcd_, _tntr_, _tntc_, _columnmassflux_ gone from emMon 

**HighResMIP-AmonExt**
_uqint_, _vqint_, _ua7h_, _va7h_, _hus7h_ gone from emMon

Speaking to Malcolm Roberts (HighResMIP lead) we don't think these should have vanished.

A wider issue may be the existence of requestVarGroups with no variables, and variables with no assignment to any requestVarGroups. PMIP in particular has 17 groups with no variables.

**Comment by martinjuckes** [comment]
This is due to a mismatch between group names and sheet names in the request template ... and a code change which by-passes a "fix" that was previously in place. Should be fixed in 01.beta.39

**Comment by martinjuckes** [comment]
Fixed.
