### ISSUE TITLE
snow mass change on sea ice cell_methods

### ISSUE THREAD

**Issue by taylor13** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#351]
Not sure about this, but shouldn't the following variables in table SImon have a "cell_methods=area: time: mean where sea_ice over all_area_types":
sndmasssnf
sndmassmelt
sndmasssubl
sndmassdyn
sndmasssi
sndmasswindrif

If not, why not?

**Comment by taylor13** [comment]
Or possibly "cell_methods = area: time: mean where sea_ice"

The point is to exclude snow processes over land.

**Comment by martinjuckes** [comment]
The variable description says "..... divided by grid-cell area", so it should be `
area: time: mean where sea_ice over all_area_types`

**Comment by martinjuckes** [comment]
On 2nd thoughts, these variables should relate to `sisnmass`, which is defined with `area: time: mean where sea_ice` ... so it may be better to adjust the description to be consistent with this. That would also fit better with the earlier discussions which we had with Dirk.

**Comment by martinjuckes** [comment]
These variables are  "to be interpreted as extensive relative to snow area, but intensive relative to sea ice" (from earlier discussion with Dirk). The cell methods have been changed to `cell_methods = area: time: mean where sea_ice`

**Comment by martinjuckes** [comment]
The description of sisnmass needed correction, to be consistent with cell methods and the above variables.
