### ISSUE TITLE
sltnortha in EmonZ

### ISSUE THREAD

**Issue by taylor13** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#352]
In EmonZ, sltnortha has a dimension "basin", which I think was meant to be a scalar auxiliary dimension assigned the value of "atlantic_arctic_ocean".  This cannot be handled by CMOR3 because CMOR expects "basin" (as used elsewhere in the data request) to have 3 values (atlantic, pacific and global).

Can either this variable be removed from the request (in favor of the existing variable sltbasin) or can we remove "basin" from its list of dimensions?

**Comment by martinjuckes** [comment]
We can remove it, as it is redundant. 

The values for basin are, as in CMIP5 `atlantic_arctic_ocean indian_pacific_ocean global_ocean` : neither  `atlantic_arctic_ocean` nor  `indian_pacific_ocean` are in the standard region list. Is the intention here "atlantic plus arctic" and "indian plus pacific"? Should ask to have them added to the CF list?

**Comment by taylor13** [comment]
Yes and yes.

**Comment by martinjuckes** [comment]
@taylor13 : hello Karl, can you support my request for the new regions on the CF list ([http://mailman.cgd.ucar.edu/pipermail/cf-metadata/2018/020666.html ](http://mailman.cgd.ucar.edu/pipermail/cf-metadata/2018/020666.html )) and then I can ask Alison to add them?

**Comment by taylor13** [comment]
Done!
