### ISSUE TITLE
Low priority cell_measures issues

### ISSUE THREAD

**Issue by taylor13** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#356]
I think it would be good at some point to do the following:

In tables IyrAnt and IyrGre:
   for variable lim: cell_methods = area: *sum* time: mean where ice_sheet

In tables lfxAnt and lfxGre:
   for variables hfgeoubed, topg, lithk: 
        cell_methods = area: mean *where ice_sheet (or is it “land_ice”?)*
(in the lyrAnt and lyrGre tables it has "where ice_sheet")

In tables Eday and Emon:
   for variables tasmaxCrop, tasminCrop, hursminCrop, prCrop: 
        for the area cell method,  area: mean *where crops* 

In tables Emon, Eyr, and Lmon:
    for all variables representing a fraction, replace in cell_methods "area: mean where land over all_area_types" with "area: mean".

**Comment by martinjuckes** [comment]
(1) cell methods for lim:  It needs changing, but I think it should be `cell_methods = area: sum where ice_sheet time: mean` : the first operation is a global mean over all locations with area type ice_sheet, followed by a time mean. This also applies to variables tendacabf, tendlibmassbf, tendlicalvf. 

(2) hfgeoubed and topg should be `where grounded_ice_sheet` as the variables are not defined where the ice sheet is floating --- this also applies to these two variables in IyrAnt and IyrGre. lithk has `where ice_sheet` in IyrAnt and IyrGre, so I think the same applies to the fixed versions.

(3) ... where crops: yes, I'll make these changes.

(4) fractions: I can see your point, but the longer form is consistent with CMIP5 usage in Lmon .. so I'd prefer to leave it now and perhaps discuss further in the future.

**Comment by martinjuckes** [comment]
These changes where implemented in 01.00.28
