### ISSUE TITLE
orog & orogis 

### ISSUE THREAD

**Issue by taylor13** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#357]
orogis (surface_altitude) in table LImon has cell_methods "mean where ice_sheet".
orog in tables fx and Emon has cell_methods "mean",but orog in tables lmonAnt, lmonGrn, lyrAnt and lyrGre. has "mean where ice_sheet".  

The least disruptive fix for the discrepancy, I think, is to change the cell_methods in tables lmonAnt, lmonGrn, lyrAnt and lyrGre to read "mean" (not "mean where ice_sheet").  The only difference will be at the margins of the ice sheets.

**Comment by martinjuckes** [comment]
This is an intentional distinction. The mean orographic height over the ice sheet is what is wanted.

**Comment by taylor13** [comment]
But if we keep "mean where ice_sheet", shouldn't the variable name be "orogis" to be consistent with Table LImon and to distinguish it from orog as defined in tables fx and Emon?  

I think it should, but we probably shouldn't be changing variable names at this point. That is why I suggested changing the the cell_methods, which I don't think anyone would mind much.

**Comment by martinjuckes** [comment]
Perhaps it should be "orogIs", but this would also apply to other variables in ImonAnt etc. 

There is a wider discussion to be had about variable names, which is already tagged for discussion under cmip7_forward_look issues: https://github.com/cmip6dr/cmip7_forward_look/issues/5 .

If we change the cell methods the variables will be wrong around the edge of the ice sheet -- I think this is too big a change to introduce at this stage. 

We don't have a form rule on consistency of variable names ... we could try and introduce one for the future.

**Comment by taylor13** [comment]
I agree that not enough oversight of proposed variable names for CMIP6 has meant there are inconsistencies across tables that we can only wish we had corrected and that puts us in a predicament.  

The particular and more serious concern here is that most users will assume that orogIs in LImon and orog in lmonAnt, lmonGrn, lyrAnt and lyrGre must represent a different field.  Similarly, most users will assume that orog in fx and Emon and orog in lmonAnt, lmonGrn, lyrAnt and lyrGre represent the same quantity.  They would be wrong in both cases.

Maybe we can't do anything at this point.
