### ISSUE TITLE
inconsitency between LImon and ImonAnt and ImonGre

### ISSUE THREAD

**Issue by taylor13** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#358]
In tables lmonAnt and lmonGre, the variables tas, ts, prsn, prra, hfls, hfss, rsds, rsus, rlds, and rlus are means "where ice_sheet", but the realm is set to "atmos".  

In Table LImon, the same variables appear with an "Is" suffix (e.g., tasIs, tsIs, prsnIs, etc.) and the realm is set to "landIce land"

In all 3 tables the cell_methods has "mean where ice_sheet".

To partially correct the inconsistency in the least disruptive way, I suggest changing the realm in ImonAnt and ImonGre from "atmos" to "landIce land".

**Comment by martinjuckes** [comment]
OK, in the interest of least disruption. `tas` is obviously in realm "atmos" in other tables ... but perhaps best not to worry about that here.

I've also made some changes from "atmos" to "landIce" for variables in IyrGre, IyrAnt
