### ISSUE TITLE
ua @ Eday has an incorrect "comment"

### ISSUE THREAD

**Issue by jypeter** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#359]
The current _comment_ for **ua @ Eday** is `resolution: 17 standard level.`. This is not correct, because ua is defined on 19 pressure levels (`plev19`). I think the comment should just be left blank

Note: the _comment_ for **va @ Eday** is just a copy of the _description_ field. There are many variables in the same case in Eday, where _comment_ is a copy of _description_ and could possibly be removed. This is not really an issue, so I'm not opening a github issue for this

**Comment by martinjuckes** [comment]
OK, fixed now (for 01.00.29), thanks
