### ISSUE TITLE
Incomplete change of melt pond thickness variable simpmass in 01.00.28

### ISSUE THREAD

**Issue by matthew-mizielinski** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#360]
In the final release of 01.00.28 there is a change to the variable `simpmass` in `SImon`, not indicated in the release notes that I can see, which changes its units from `kg m-2` to `m` accompanied by some changes to the description and comment fields (`Meltpond mass per area of sea ice.` -> `Meltpond Depth`) and the long name (`Meltpond Mass per Unit Area` -> `Meltpond Mass per Unit Area (as Depth)`), but the corresponding CMORvar object in the data request [here](http://clipc-services.ceda.ac.uk/dreq/u/7117858a-faa7-11e6-bfb7-ac72891c3257.html) has not changed.

As a result the [entry in the SImon MIP table](https://github.com/PCMDI/cmip6-cmor-tables/blob/01.00.28/Tables/CMIP6_SImon.json#L971) is a little confused with a number of conflicting fields.

@martinjuckes, Could you add something to the release notes to flag up this change and correct it in the next release?

**Comment by taylor13** [comment]
A similar issue was raised at https://github.com/PCMDI/cmor/issues/406#issuecomment-425923217 regarding variable o3ste.  

My input there is copied here:
```
@martinjuckes I note that now o3ste has the correct long_name in release 01.00.28. Thanks.
Have you checked whether in the rest of the archive a change in the "var" record has been
 changed but not in the CMORvar record? Could you check the consistency of all "var" and
 "CMORvar" records to eliminate in general errors of this kind? Thanks.
```

**Comment by martinjuckes** [comment]
Sorry about this ... the change happened in release 01.00.27 : now noted in updated release notes: [01.00.27](https://earthsystemcog.org/projects/wip/drq_release_01_00_27).

The CMORvar will be updated in 01.00.29
