### ISSUE TITLE
Use of "where sea" in ocean cell methods?

### ISSUE THREAD

**Issue by adcroft** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#362]
I need help understanding the use of "area: mean where sea" for ocean variables. There are examples in the tables of "area: mean" and "area: mean where sea" where both have cell_measure: "area: areacello". `areacello` is [defined](http://clipc-services.ceda.ac.uk/dreq/u/baa3ee94-e5dd-11e5-8482-ac72891c3257.html) to be the area required to make exact integrals (i.e. is the actual surface area of ocean in a cell). So if a variable is averaged over `areacello` then there is no need for the "where sea"; the statistics are not being applied to a [portion of the cell](http://cfconventions.org/cf-conventions/cf-conventions.html#statistics-applying-portions) which is what (I think) the "where ..." indicates.

In the commits leading up to #361 I was (maybe incorrectly) removing "where sea" from the variables I had looked at. The mix of usage might be something to fix and make uniform in the O* tables.

**Comment by taylor13** [comment]
"mean where sea" means: consider the portion of the cell that is "sea" and compute the mean there.  This is the value that is a characteristic of the grid cell that has an area of areacello.  To determine the area of the portion of the cell that is "sea", you would have to multiple areacello by the sea-fraction of the grid cell.

The difference between "mean" and "mean where sea" for, say, surface air temperature is the "mean" is computed over both the land and sea portions of the cell, whereas  the temperature "mean where sea" is computed over only the sea portion of the grid cell.  Both grid cells have the area stored in areacello.
