### ISSUE TITLE
Unable to access variables via web page

### ISSUE THREAD

**Issue by ehogan** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#365]
Hi @martinjuckes, I'm not sure if this is the best place to post this issue, but I've just tried to access a variable via http://clipc-services.ceda.ac.uk/dreq/mipVars.html, but the search box isn't loading. So I tried to access the variable via http://clipc-services.ceda.ac.uk/dreq/index/var.html, but when I click on any link I get taken to a page that says:

```
Forbidden

You don't have permission to access /dreq/u/<uid>.html on this server.
```

**Comment by martinjuckes** [comment]
This break in the services was caused by some rearrangement of disks during a data centre upgrade here. Now resolved. Apologies  for the interruption.

**Comment by valeriupredoi** [comment]
hi @martinjuckes unfortunately I am running into the same issue as Emma, now, one year later :grin: http://clipc-services.ceda.ac.uk/dreq/mipVars.html is not responding at all (not loading anything)l in fact the root http://clipc-services.ceda.ac.uk is not loading either :beer:

**Comment by martinjuckes** [comment]
Hi @valeriupredoi , I believe the site is working now: can you access it?

I'll get some monitoring set up to see how serious the service interruptions are.

**Comment by valeriupredoi** [comment]
Hi Martin, cheers much! not at the moment (off my Android phone, sorry am
traveling but will try again on Wed morning when back and let you know).
Cheers :beer:

Dr Valeriu Predoi.
Computational scientist
NCAS-CMS
University of Reading
Department of Meteorology
Reading RG6 6BB
United Kingdom

**Comment by matthew-mizielinski** [comment]
@martinjuckes, FYI: the server behind these webpages has been going down and up almost every day last week -- I've been in contact with CEDA support over this a couple of times. At the time of writing I cannot get a response from http://clipc-services.ceda.ac.uk/
