### ISSUE TITLE
Should a lambda440nm dimension exist?

### ISSUE THREAD

**Issue by ehogan** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#366]
`od550aer` has a `lambda550nm` dimension, see http://clipc-services.ceda.ac.uk/dreq/u/8f2fb9e812c26ee6cb8d9673e09d2644.html and http://clipc-services.ceda.ac.uk/dreq/u/dabd02ac-16f4-11e8-b44a-a44cc8186c64.html. However, `od440aer` doesn't have an equivalent `lambda440nm` dimension, see http://clipc-services.ceda.ac.uk/dreq/u/c5331238e635e9c913da1eb247859206.html. Is this correct?

**Comment by martinjuckes** [comment]
Deferred to CMIP7.
