### ISSUE TITLE
Inconsistencies in clt metadata

### ISSUE THREAD

**Issue by ehogan** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#367]
`clt` (see http://clipc-services.ceda.ac.uk/dreq/u/7c2249d424dde72f8616d42870a9d425.html) has a `description` including `Total cloud area fraction`, a `title` of `Total Cloud Cover Percentage`, a standard name of `CloudAreaFraction` and `units` of `%`. Would it be possible for the descriptions, titles, standard names and units to be made consistent? See also #325.

**Comment by martinjuckes** [comment]
Adjusted in 01.00.30
