### ISSUE TITLE
Meridional heat and salt fluxes .... zig-zag path?

### ISSUE THREAD

**Issue by martinjuckes** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#371]
There are some Omon meridional mass streamfunction variables, such as msftmzmpa, there is an instruction that, when the model grid is not aligned with longitude, the zonal mean should be evaluated using a zig-zag path. Matthew has pointed out that it might make sense to use the same algorithm for zonal mean fluxes, i.e hfbasin, hfbasinpmadv, hfbasinpsmadv (heat fluxes requested by OMIP) and sltbasin (salt flux requested by DCPP).

**Comment by StephenGriffies** [comment]
I see no problem with this proposal.

**Comment by martinjuckes** [comment]
Hello @StephenGriffies : thanks, I'll make the guidance for the heat and salt fluxes the same as for the mass flux. 

There is a follow up question: I've just noticed that guidance for the mass fluxes says "this transport should be approximated as the transport **along** zig-zag paths corresponding to latitudes with spacing between latitudes appropriate to the model's resolution" (copied from CMIP5). Shouldn't it say " .. transport **across** zig-zag paths ....", since the zig-zag path described is running west to east and we want the south to north transport?

**Comment by StephenGriffies** [comment]
Good catch.   You are correct: it should say "across" not "along".

**Comment by senesis** [comment]
It is my pleasure to remind that a number of centers producing simulations have already published quite a lot of data, which agree with specifications of DR version 01.00.21 (released end of last year), and will not be able to change data content (except without re-running the simulations, which is not seriously considered)

**Comment by matthew-mizielinski** [comment]
@senesis, I thoroughly envy your achievement and hope to catch up shortly :-)

FWIW, it is highly unlikely that this change will be reflected in the UKESM1 DECK submission from us, as I fully expect to go with data request version 28.

**Comment by martinjuckes** [comment]
@senesis : I suppose you are referring to the algorithm for heat fluxes etc, rather than the correction in the wording from "along" to "across". For the former, we should perhaps word it as a recommendation or suggestion, rather than a requirement. As it was not suggested in CMIP5, it is presumably not a critical issue whether these diagnostics are computed in this way or not.

> For models which do not have a Cartesian lat-long grid, this transport can be approximated as the
> transport across zig-zag paths corresponding to latitudes with spacing between latitudes appropriate to
> the model's resolution, as is done for the ocean meridional overturning mass streamfunction.

**Comment by martinjuckes** [comment]
Closed with the above text, which is a suggestion rather than an instruction, recognising that some data were generated before this suggestion arose.
