### ISSUE TITLE
Climatology timeSlice information

### ISSUE THREAD

**Issue by sol1105** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#376]
Hello,
only 4 requestItems for Oclim variables have a timeSlice attribute, the CMIP-historical requestItems and the HighResMIP-piControl requestItems (eg. http://clipc-services.ceda.ac.uk/dreq/u/93f659a4-267c-11e7-8933-ac72891c3257.html).
For the other requestItems for Oclim variables, where can the timeSlice information be found, or do the requested climatologies really extend over the complete experiment timeframe?
Regards,
Martin

**Comment by sol1105** [comment]
A small inconsistency I noticed:
The MIPtable Oclim has the attribute frequency set to "monClim" (http://clipc-services.ceda.ac.uk/dreq/u/MIPtable::Oclim.html), whereas the Oclim (and Amon climatological) variables have the attribute frequency set to "monC".

**Comment by martinjuckes** [comment]
Since the `frequency` controlled vocabulary was changed mid-way through the process, the definition of the `frequency` attribute in the MIP table records is not consistent with the definition is the vocabularies. This needs to be cleared up.

The lack of timeSlice specifications looks like an error, but I'll have to go back to the MIP co-chairs to see what the time slices should be. There are request for this data from historical-ext and esm-hist-ext which may be an error: I 'm not sure that it makes sense to calculate climatologies for these short extension experiments.

**Comment by martinjuckes** [comment]
Fixed for historical and piControl, but there is an open question on the HIghResMIP piControl request (because other variables are requested for 200 years). 
Need to check that piControl time slice is correct.

**Comment by martinjuckes** [comment]
(1) Should all requests for Oclim data from historical and esm-hist be made consistent with the core request in using the last 20 years for the climatology?

**Yes, confirmed ... all set to the [_slice_clim20](http://clipc-services.ceda.ac.uk/dreq/u/_slice_clim20.html) slice.**

(2) For piControl, should we ask for the 20 years which correspond to the last 20 years of the historical experiment? For HighResMIP, monthly piControl data is requested for 200 years: would it be better to have the climatology over that period?

**All set to a 20 year climatology aligned with the last 20 years of historical ([piControl020](http://clipc-services.ceda.ac.uk/dreq/u/_slice_piControl020.html))**

(3) For abrupt4XCO2 and 1pctCO2 (FAFMIP & RFMIP), does in make sense to ask for 20 years corresponding to last 20 years of historical simulation?

Yes, set to last 20 years.

(4) LUMIP, HighResMIP and RFMIP have requests for Oclim data from historical-ext and esm-hist-ext: does it make sense to ask for climatological data from these short experiments? Can I delete these requests?

Extension request all removed.

(5) ScenarioMIP experiments (LUMIP): should it be the last 20 years of 21st century, i.e. 2081-2100, to have consistent length.
**Request for climatologies from ScenarioMIP and related experiments from LUMIP and GeoMIP set to 2081-2100 (a new `scenario20` time slice record).**

(6) MIP experiments: where you are requesting climatologies from your own experiments, is there any preferred time range? Would it be enough to just specify that it should be a 20 year period?

**All set to final 20 years of experiment when there is not a clear match to historical or scenario experiments. The only exception is the [GeoMIP-4](http://clipc-services.ceda.ac.uk/dreq/u/f16e4352-dd9e-11e6-b89b-ac72891c3257.html) experiment group which contains experiments of 10 years duration: for these the climatology should cover the full simulation and no explicit time slice is given.**

Additionally, durations and start times of GeoMIP experiments corrected.
