### ISSUE TITLE
Some requestItems using a timeslice should have an additional nenmax attribute

### ISSUE THREAD

**Issue by senesis** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#378]
Some RequestItems such as [this one](http://clipc-services.ceda.ac.uk/dreq/u/93f7319e-267c-11e7-8933-ac72891c3257.html) have a timeslice which period refers to another experiment than the one which holds the request, as e.g. [_slice_piControl030](http://clipc-services.ceda.ac.uk/dreq/u/_slice_piControl030.html) which applies to piControl and refers to experiment historical. In that case, the nenmax attribute (max rank of the member on which the requestItem applies) refers to piControl; however, it could be useful , especially when simulating large historical ensembles, to also indicate a max rank for historical members considered. this is especially important for those centers which workflow produces only the requested data, as early as the simulation run.

**Comment by martinjuckes** [comment]
I agree that there is a real issue here, but I don't think we can do anything at this stage. 

Would it help to have a link to the child experiment from the timeslice record? At the moment the timeslice record just records the child experiment name. 

You need, I think, the maximum value of `nenmax` for all requestItems associated with `historical` which are included in your subset of the data request ouptut, so this is not a single number that could be added. In the schema 2.0 I intend to add some defined methods to various classes. This could perhaps be one of them: timeSlice.maxChildEnsemble().

**Comment by senesis** [comment]
I think that the maxChildEnsemble should rather be a property of the RequestItem (and is a single number for each RequestItem). The logic when producing diagnostics for one member of piControl would then be :

1. find requestItems which apply to this member of piControl (vs nenmax) and also have a timeslice which has a child experiment
2. for each child experiment member which rank is less than requestItem.maxChildEnsemble, consider its starting date and check if the timeslice definition matches the current simulated year of piControl; if yes, the requestItem applies

But, for my producing center, this will anyway not be managed for CMIP6. My comment's only aim is to have a near-perfect setup for CMIP7, if any ;-)

**Comment by martinjuckes** [comment]
OK ... the way I'm working at the moment it will probably be on multiple objects. For instance, I've just added a `getRequestingMIPs()` method: on a `var` object it calls the `getRequestingMIPs()` method on each linked `CMORvar` object and aggregates the results. On the `CMORvar` object it calls the same method name on each `requestVar` object, and aggregates the results. `requestVar.getRequestingMIPs()` actually does some work. 

I haven't worked it all out for the `maxChildEnsemble()` case, but a similar approach will mean that it occurs on several classes of object, most of them doing fairly simple aggregations.

**Comment by martinjuckes** [comment]
Moved to forward look.
