### ISSUE TITLE
Long name of rlut in different tables

### ISSUE THREAD

**Issue by matthew-mizielinski** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#38]
In the HighResMIP tables (downloaded as excel files) the variable rlut has the Long name 'TOA Outgoing Longwave Radiation 4XCO2 Atmosphere'. As HighResMIP is not running any 4XCO2 experiments this is a little confusing.

Comparing the information from the rlut entries in http://clipc-services.ceda.ac.uk/dreq/index/CMORvar.html with the cmvmm_TOTAL_HighResMIP_3_3.xlsx spreadsheet it looks like there is a conflict over what the long name is for various instances of this variable;

In aermonthly:  "toa outgoing longwave radiation"
In cfDay, Amon, day:  "TOA Outgoing Longwave Radiation"
In em1hrclimmon, em1hr, em3hr, emSubhr: "TOA Outgoing Longwave Radiation 4XCO2 Atmosphere"

I'd suggest that the latter set are altered to use the variable "rslut4co2".

Note that dreqPy appears to contain the correct information.

**Comment by martinjuckes** [comment]
Could you say more precisely where the inocrrect definition (with 4XCO2) is found?

**Comment by matthew-mizielinski** [comment]
cmvmm_TOTAL_HighResMIP_3_3.xlsx as downloaded a moment ago:
- Amon: B31
- aermonthly: B65
- cfDay: B18
- day: B30
- em1hr: B16
- em3hr: B2
- emSubhr: B12

Along side this there are two requestVarGroups that contain variables that cannot be generated;
- HighResMIP-cfMon-2dmod 
- HighResMIP-cfMon-3dmod 
  The HighResMIP runs, as I understand them, won't reach the 4 x CO2 threshold even if extended to 2100.

**Comment by martinjuckes** [comment]
I think this is fixed now
