### ISSUE TITLE
Deflate_level

### ISSUE THREAD

**Issue by wachsylon** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#383]
Hi,
there are about 700 variables which have an attribute `deflate_level : 0` in the DReq, for example `sivol` in `SImon`. The MIP-Tables do not include this attribute. Additionally, we already found a file (e.g. `hus_Emon_IPSL-CM6A-LR_historical_r8i1p1f1_gr_185001-200912.nc`) in ESGF which is not compliant with the attribute `deflate_level : 0` requested by the DReq . Is there any reason that these variables should be uncompressed? If not, I suggest to remove the attribute from the DReq.
Best regards, Fabi

**Comment by taylor13** [comment]
FYI @martinjuckes .  This information (deflate_level) in the DReq is not seen by CMOR, so modifying it won't affect us.

**Comment by martinjuckes** [comment]
Hi @wachsylon .. these values are inherited from a CMIP5 spreadsheet, but, as Karl has indicated, they are not used. I have promised not to change the Data Request schema ... so I cannot remove the attributes at this stage, but I will set them to blank. The description of the "deflate_level" and "deflate" attributes has been updated (in 01.00.30beta1) to "Obsolete, not used in CMIP6.".
