### ISSUE TITLE
olayer100m dimension correction to bounds

### ISSUE THREAD

**Issue by taylor13** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#385]
On https://github.com/PCMDI/cmip6-cmor-tables/issues/233#issuecomment-466380779 @sol1105 notes that dimension "olayer100m" should have the bounds (0., 100.), as correctly recorded in the boundsValues descriptor in the DREQ, but the "bounds" descriptor should be set to "yes", not "no"

**Comment by martinjuckes** [comment]
OK, done
