### ISSUE TITLE
possibly incorrect cell_methods and time coordinate

### ISSUE THREAD

**Issue by taylor13** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#386]
@martinjuckes  I noticed that in the CMOR table 6hrLev the only variable with frequency = "6hr" and time coordinate = "time" is bs550aer.  All other variables in that table have frequency = "6hrPt" and time coordinate = "time1".  

I suspect that different variables reported on model levels need to have the same time coordinate (and frequency attribute) if CMOR is to successfully write them.  Could you check with those requesting this variable and see if we can request bs550aer at frequency "6hrPt".  (I would think they would want all variables in this table be sampled in the same way.)  Otherwise we might have to put bs550aer in its own separate table: "6hrLevPt".

**Comment by martinjuckes** [comment]
OK .. I'll fix that (change bs550aer to 6hrPt and time-point).

**Comment by sylvaine** [comment]
It seems that the associated structure of variable `bs550aer` (which has uid `8fecd6da-267c-11e7-8933-ac72891c3257`) still has a wrong `title` attribute:
```
In [1]: dq = dreq.loadDreq()

In [2]: bs550aer = dq.inx.uid['8fecd6da-267c-11e7-8933-ac72891c3257']

In [2]: dq.inx.uid[bs550aer.stid].title
Out[2]: 'Temporal mean, Global field (single level) [XY-na] {:lambda550nm scatter180} [am-tm]'
```
while its `tmid` is correct:
```
In [3]: dq.inx.uid[dq.inx.uid[bs550aer.stid].tmid].title
Out[3]: 'Instantaneous value (i.e. synoptic or time-step value)'
```
