### ISSUE TITLE
unnecessary "type" dimension

### ISSUE THREAD

**Issue by taylor13** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#388]
The variable sftof has a "typesea" coordinate (that gets renamed "type" when written out) and it is a "label" assigned the  single value "sea".  
Similarly sftlf has a "scalar" coordinate set to "land".  
In both cases I think this is unnecessary and could be confusing.  The variable sftof is the sea_area_fraction" so the coordinate "label" doesn't qualify that in any way.  Similarly for sftlf.
Would it be o.k. to remove "typesea" and "typeland" from the data request?

**Comment by martinjuckes** [comment]
I don't see how this could be confusing .... but I'll take it out for now. The intention was to have a common structure for area fractions, which I though would make it less confusing. I'll remove it for now, and raise it as something for future discussion.
`sftof`: this will be changed to have a `structure` record as `orog`, which has `cell_methods=area: mean` and `cell_measures=areacello`. 
`sftlf`:  this will be changed to have the same `structure` record as `orog`, which has `cell_methods=area: mean` and `cell_measures=areacella`.

For completeness, I've made the change to `sftgrf` (grounded ice sheet), `sftflf` (floating ice shelf), `sftgif` (land ice). These are all `areacella`, so fixed fields will be the same structure as `sftlf`, monthly will be like `pr` (with `area: time: mean`), for Greenland and Antarctic grids they will be as for `modelCellAreai`: `areacellg`, `area: time: mean`.

**Comment by taylor13** [comment]
The potentially confusing aspect is that if the variable is associated specifically with type "sea" only and the variable measures, for example, "ocean fraction", it might seem that the fraction should always be 100% (of the sea is covered by ocean).

I note that siconca and siconc also have a "typesi" scalar coordinate, which is unnecessary and perhaps confusing.  I think only variables that have the generic "area_fraction" standard name should have a coordinate identifying the surface type.  [Note further that sidconcdyn and sidconcth do *not* have scalar dimensions, which I think is good.]
