### ISSUE TITLE
SImon_sidmasstranx/sidmasstrany unit

### ISSUE THREAD

**Issue by tsemmler05** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#389]
The unit in table SImon parameters sidmasstranx / sidmasstrany is kg/s. Should it not be kg/(m*s)?

**Comment by martinjuckes** [comment]
These variables are linked to standard names `sea_ice_x_transport`,  `sea_ice_y_transport`, which are defined with canonical units `kg s-1`. In CF, terms with units `kg m-1 s-1` are of the form `...transport_across_unit_distance`. I believe this  should be the mass transport across the grid cell boundary.

**Comment by martinjuckes** [comment]
Confirmed by Dirk (though they might, in retrospect, have preferred a transport across unit distance).
