### ISSUE TITLE
Missing "bounds" specification for some coordinates

### ISSUE THREAD

**Issue by taylor13** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#390]
For the following dimension variables, "bounds" is set to "".

    lambda550nm
    xant
    xgre
    yant
    ygre

    effectRadIc
    effectRadLi

CMOR interprets this as must_have_bounds="no", which is the correct interpretation for the first 5, but not the last two.  I think we should make the data request explicit by setting bounds to "no" for the first 5 and setting "bounds" to "yes" for the last two.

**Comment by martinjuckes** [comment]
OK.

I will also added standard names for `effectRadIc` and `effectRadLi`.
