### ISSUE TITLE
duplicate surface_air_pressure variables

### ISSUE THREAD

**Issue by taylor13** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#391]
monthly surface_air_pressure is found in the following CMOR tables: Amon, CFmon, Emon, and AERmon.  Some groups are outputting this field (stand alone) multiple times for a given simulation.  There is no need for this.  

Similarly surface_air_pressure is found in the following CMOR tables:  3hr, CF3hr, and E3hrPt.

 There is a comment associated with ps in some of these tables that ps is needed to calculate the 3-D pressure field from hybrid coordinates.  This is true, but at least in the CMOR tables, we want it to only appear once (for each of the two cases above).  For consistency with CMIP5 I would keep ps in Amon and in  3hr.  It should be removed from the other tables listed above.

[Note that ps appears in several forms in the CMOR "formula_terms" table, which is why it isn't generally needed in the variable tables.]

**Comment by balaji-gfdl** [comment]
I'm ok with this approach, and GFDL is acting upon it. But I wonder if others have seen this, and will there be consequences we haven't thought about? I will post it on the WIP Slack, and if there are no comments by April 30, we can close this issue.

**Comment by matthew-mizielinski** [comment]
Sounds sensible to me.

One additional observation; not all of the above listed variables are linked up to experiments in the data request. At v01.00.29 the entries in `CFmon`, `CF3hr` and `E3hrPt` do not appear to link up to any other objects as such wouldn't appear in our processing. 

This lack of links can be seen by going to the corresponding page for the CMOR variable in the html interface to the data request at http://clipc-services.ceda.ac.uk/dreq/index.html ; If you look at [CF3hr/ps](http://clipc-services.ceda.ac.uk/dreq/u/1d3e9509489c555a5027e894ae9eda80b2ff7e6f.html) you'll see no links to a "request variable", where as for [3hr/ps](http://clipc-services.ceda.ac.uk/dreq/u/bab47354-e5dd-11e5-8482-ac72891c3257.html) you will.

@martinjuckes, could you double check that I've interpreted the above correctly?

**Comment by taylor13** [comment]
I have a vague recollection that at one time CMOR might have needed to have the ps variable appear in tables where variables are a function of model level.  That might be an explanation for its appearance in the tables even though it is not explicitly requested by any CMIP6 MIP.  

In CMOR3, the "parametric" variables supporting the vertical coordinate all appear in the "formula_terms" table, so for the purpose of hybrid sigma coordinates, CMOR gets its information about the ps parametric variable from the formula_terms table.  

ps could also appear in regular variable tables if some analysis requires ps even when 3-d variables are *not* needed or for models with, for example, atmospheric z-coordinate (rather than hybrid sigma coordinate) to approximately calculate the lowest layer pressure thickness.

**Comment by martinjuckes** [comment]
This was added to support CMOR ... the variable is defined in the tables so that CMOR can use in as an ancillary variable in coordinate definitions, but it is not requested.

**Comment by taylor13** [comment]
O.K.  That's what I suspected.  I'm pretty sure that CMOR no longer needs this for defining its formula_terms;  It gets ps from a special table generated outside of the data request, which handles **all** formula_terms (not just the ones that are a function of longitude and latitude).  There's no harm I suppose in having ps appear in tables where it isn't actually requested, although some groups will probably mistakenly save it.
