### ISSUE TITLE
grassFrac*, vegFrac -  inconsitencies in the description

### ISSUE THREAD

**Issue by sol1105** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#392]
[vegFrac](http://clipc-services.ceda.ac.uk/dreq/u/6f6a57d0-9acb-11e6-b7ee-ac72891c3257.html) description:
Percentage of grid cell that is covered by vegetation.This SHOULD be the sum of tree, **grass**, crop and shrub fractions. 

[grassFrac](http://clipc-services.ceda.ac.uk/dreq/u/fb01755a-be37-11e6-bac1-5404a60d96b5.html) description:
Percentage of entire grid cell that is covered by **natural grass**. 

[grassFracC4](http://clipc-services.ceda.ac.uk/dreq/u/8b814cc8-4a5b-11e6-9cd2-ac72891c3257.html) description:
Percentage of entire grid cell covered by **C4 grass**. | Percentage of entire grid cell that is covered by **C3** **natural grass**. 

grassFrac is defined as fracture of grid cell covered by natural grass. That would exclude pasture.
For vegFrac however, pasture would be included in the grass fraction?

(Notice also the typo in the CMOR variable description of grassFracC4 and the differences between the CMOR variable description and the MIP variable description.)

**Comment by martinjuckes** [comment]
vegFrac should include pasture (see the [C4MIP GMD paper](https://www.geosci-model-dev.net/9/2853/2016/), p. 2872). I'll update the request and correct the other errors. Thanks for pointing it out.
