### ISSUE TITLE
Clarification on the use of grid_latitude in meridional sections

### ISSUE THREAD

**Issue by zklaus** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#397]
The meridional stream function variables `msft*` via the spatial [GYB-O](http://clipc-services.ceda.ac.uk/dreq/u/4b5dfb22-43c0-11e8-be0a-1c4d70487308.html) and [GYB-R](http://clipc-services.ceda.ac.uk/dreq/u/4b5dfb23-43c0-11e8-be0a-1c4d70487308.html) make use of the dimension [grid_latitude](http://clipc-services.ceda.ac.uk/dreq/u/dim:grid_latitude.html). 

However, `grid_latitude` is reserved for rotated grids, which is generally not the case for most models and doesn't seem to be the intuitive approach to such a meridional quantity.

What is the rationale for using rotated grids here?

**Comment by martinjuckes** [comment]
Hi @zklaus , sorry for the long overdue response: the `msftyz` etc variables that use GYB-O and GYB-R should only be provided for models which have a zonal-meridional grid. I changed this from `latitude`. At the time I was under the impression that `grid_latitude` was applicable to a wider range of grids than just the rotated pole grid. The CF Standard Name is ambiguous on this, bu the CF Convention does imply that it should only be used for rotated pole systems.

In the end, this is a directive to CMOR, it should not end up in data files. CMOR implements one of the CF approved grids, as specified by the model grid information it has been given. I'll mark it as something to clear up in CMIP7.

**Comment by zklaus** [comment]
Hi @martinjuckes, no worries. Thanks for picking this up. I think it is a good idea to clarify for CMIP7 and possibly even in CF itself. Perhaps by the time of CMIP7 CF will have evolved wrt WKS etc. anyways.
