### ISSUE TITLE
correction of time axis specification for tasmax and tasmin in Amon

### ISSUE THREAD

**Issue by taylor13** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#400]
@larsbarring noted in https://github.com/cf-convention/discuss/issues/371  that in the Amon table, the monthly mean daily max and daily min temperatures (``tasmax`` and ``tasmin``) should have a "climatology"  axis rather than a regular axis.  I'm not sure whether changing this for CMIP6 will mess up those in the middle of writing output (I don't *think* it would), but we should definitely correct this for CMIP7.   

The difference in a "climatology" time axis and a regular one is that the  name of the "bounds" variable is stored in the ``climatology`` attribute, not in the ``bounds`` attribute.   I'm not sure if ``tasmax`` and ``tasmin``  in Amon should be functions of time3, time4, or some newly defined time axis.

Note that for these variables the actual values that should be stored in the variable pointed to by the ``climatology`` attribute would be identical to the values currently written to the variable pointed to by the ``bounds`` attribute.

**Comment by martinjuckes** [comment]
I agree that we should wait for CMIP7. This is a feature inherited from CMIP5, so users will not be supplied. I agree that it is likely that data producers would cope, but it would be confusing to data users if we end up with two different implementations for this variable.

**Comment by martinjuckes** [comment]
New time axis added for monthly fields.

**Comment by taylor13** [comment]
What is the name?  We need to make sure CMOR can handle this.
