### ISSUE TITLE
Misleading description in grids-entry "siline" and connected variables

### ISSUE THREAD

**Issue by sol1105** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#401]
The grids-entry "[siline](http://clipc-services.ceda.ac.uk/dreq/u/dim:siline.html)" lists the 4 requested straits giving them numbers from1 to 4: 
description: 1. Fram Strait = (11.5W,81.3N) to (10.5E,79.6N); 2. Canadian Archipelego = (128.2W,70.6N) to (59.3W,82.1N); 3. Barents opening = (16.8E,76.5N) to (19.2E,70.2N); 4. Bering Strait = (171W,66.2N) to (166W,65N);

This is also used as part of the description for the connected MIP variables:
[siareaacrossline](http://clipc-services.ceda.ac.uk/dreq/u/73097b4c-7a68-11e6-8db2-ac72891c3257.html)
[simassacrossline](http://clipc-services.ceda.ac.uk/dreq/u/7109b964-faa7-11e6-bfb7-ac72891c3257.html)
[snmassacrossline](http://clipc-services.ceda.ac.uk/dreq/u/7309b2ce-7a68-11e6-8db2-ac72891c3257.html)
eg.:
description[i]: net (sum of transport in all directions) sea ice area transport through the following four passages, positive into the Arctic Ocean 1. Fram Strait = (11.5W,81.3N to (10.5E,79.6N) 2. Canadian Archipelago = (128.2W,70.6N) to (59.3W,82.1N) 3. Barents opening = (16.8E,76.5N) to (19.2E,70.2N) 4. Bering Strait = (171W,66.2N) to (166W,65N)

In the end this description will end up in the MIP table (and therefore in the file's metadata) as "comment"-variable-attribute.
As the actual order of this 4 entries in the character axis is arbitrary (neither CMOR nor PREPARE enforce the order given in this description/comment, this is misleading.

This problem might be there for other variables with a character axis as well, as the order of the axis entries written to the file is not necessarily the one specified in the "requested"-attribute of the data request grids-entry.

**Comment by martinjuckes** [comment]
Karl, (@taylor13) do you have a view on the ordering of terms in a character axis such as `siline`? 

[CMIP6 Model Output Requirements](https://docs.google.com/document/d/1os9rZ11U0ajY7F8FWtgU4B49KcB59aFlBVGfLC4ahXs/edit), paragraph 12, states that:
> The values and order of the labels stored in these auxiliary variables should be consistent with the lists specified by “requested” in the data request’s grids section and in the CMIP6_coordinate.json file.

This implies that the order was intended to matter, even if CMOR and PREPARE don't insist. However, if people have been publishing data with arbitrary orders, the least disruptive option may be to advise users to check the (rather than assume a specific order) and review for CMIP7.

**Comment by taylor13** [comment]
Yes,  for the convenience of users, I think it would be better if everyone ordered their "regions" along the "label" axis identically, but reviewing CMOR and PrePARE, this indeed is not enforced.  (If all the requested "regions" are present, that's sufficient, no matter what order.).

I therefore agree entirely with your last paragraph [above](https://github.com/cmip6dr/CMIP6_DataRequest_VariableDefinitions/issues/401#issuecomment-535980094) .

**Comment by senesis** [comment]
I kind of remember that, either for `siline` or another list of straits, there has been a change in the number of entries in the list, for one DR version. So, Martin's recommendation for advising users certainly makes full sense

**Comment by martinjuckes** [comment]
Closed and recorded for attention cmip7_forward_look.
