### ISSUE TITLE
Inconsistent positive attribute for Omon variables "hflso" and "hfsso"

### ISSUE THREAD

**Issue by surakawa** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#403]
The "standard_name"s for "hflso" and "hfsso" are "surface_downward_latent_heat_flux" and "surface_downward_sensible_heat_flux", respectively.
However, their "positive" attributes are "up".
I think their "positive" attributes should be changed to "down".

http://clipc-services.ceda.ac.uk/dreq/u/ada94e1e-b17f-11e6-8975-5404a60d96b5.html
http://clipc-services.ceda.ac.uk/dreq/u/ada95ca6-b17f-11e6-8975-5404a60d96b5.html

**Comment by martinjuckes** [comment]
Hello @surakawa , thanks for pointing this out. I'll correct it in the next release.

**Comment by martinjuckes** [comment]
Included in 01.00.32
