### ISSUE TITLE
Emon tntrl27 / tntrs27 CMORvar description interchanged

### ISSUE THREAD

**Issue by sol1105** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#408]
The CMORvar items with the labels tntrl27 and tntrs27 have their descriptions mixed up:

tntrl27:  Heating rate due to shortwave radiative flux
tntrs27: Heating rate due to longwave radiative flux

**Comment by martinjuckes** [comment]
Corrected in 01.00.33
