### ISSUE TITLE
MIP variables with multiple definitions

### ISSUE THREAD

**Issue by matthew-mizielinski** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#42]
There are a few variables within the data request which have a different physical meaning depending on which mip table they are in.

The most significant is [pr](http://clipc-services.ceda.ac.uk/dreq/u/62f26742cf240c1b5169a5cd511196b6.html); in Amon, day, 3hr, em1hr, emSubhr this is `Precipitation`, where as in Omon it is `Rainfall flux where Ice Free Ocean over Sea` and in two of the land ice tables it is `Precipitation over Land Ice`. 

Another is [zfull](http://clipc-services.ceda.ac.uk/dreq/u/44471dd9799293cef70ac63fcdd2476e.html); in cf3hr this is `Altitude of Model Full-Levels` while in Oclim, Omon and emYr it is `Depth Below Geoid of Ocean Layer`.

Is it sensible to have multiple meanings for a single cmor variable?

**Comment by martinjuckes** [comment]
"pr" is a CMOR variable label. In CMIP3 and 5 (and possibly earlier) it was common for CMOR variable labels to be re-used in different tables with different, but related descriptions. E.g. with different masking or different time processing. However, the use of `pr` for precipitation in one table and rainfall in another is an error. I will check with Omon whether they want `pr` for precipitation or `prra`for rainfall. 

In CMIP5 there were also a small number of cases for which the same variable label was used with different standard names in different tables, such as `zfull`: I had intended to change away from this, so the ocean version should be `zfullo`.  I'll verify this after checking with OMIP.

**Comment by martinjuckes** [comment]
Now have zfull for atmosphere, zfullo for ocean; prra for rainfall, prsn for snowfall.
