### ISSUE TITLE
cell_methods missing from the data request

### ISSUE THREAD

**Issue by ehogan** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#44]
Hi Martin,

I was able to get a list of variables missing `cell_methods` using the version of the `dreqPy` I checked out this morning:
```
H2wv emMon
O17wv emMon
O18sw emMon
O18wv emMon
areacella fx
areacellg LIfxant
areacellg LIfxgre
areacello Ofx
concdust emMon
dissi13c emMon
hcont300 emMon
hus850 emDay
masscello Ofx
md emMon
pfull emMon
phalf emMon
pmlev 6hrLev
psl 6hrPlev
ta 6hrPlev
ta850 emDay
toffset cf3hr
tso 3hr
ua 6hrPlev
ua850 6hrPlev
ua850 emDay
va 6hrPlev
va850 6hrPlev
va850 emDay
volcello fx
wo emMon
```

However, this has incorrectly included:
```
areacellg LIfxant
areacellg LIfxgre
```
and is missing
```
siareaacrossline SImon
simassacrossline SImon
snmassacrossline SImon
```
I believe this is due to the fact that there are two structures named `str-b155` (see http://clipc-services.ceda.ac.uk/dreq/index/structure.html)

**Comment by martinjuckes** [comment]
Work in progress .. I think this is mainly resolved, but will check again later this week.

**Comment by martinjuckes** [comment]
Now fixed
