### ISSUE TITLE
Units missing from the data request

### ISSUE THREAD

**Issue by ehogan** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#45]
Hi Martin,

I was able to get a list of variables missing `units` using the version of the dreqPy I checked out this morning:
```
O18sw emMon
O17wv emMon
O18wv emMon
H2wv emMon
cnc emDay
O17s emMon
H2s emMon
H2p emMon
O18s emMon
O18p emMon
qsat emMon
O17p emMon
```
In addition, the following units look suspect:
```
siareas SImon 1e6 km2
siarean SImon 1e6 km2
siextentn SImon 1e6 km2
siextents SImon 1e6 km2
tropoz aermonthly DU
intuadse emMon 1.e6 J m-1 s-1
intvadse emMon 1.e6 J m-1 s-1
cfc113global Amon 1e-12
cfc12global Amon 1e-12
cfc11global Amon 1e-12
hcfc22global Amon 1e-12
sivols SImon 1e3 km3
sivoln SImon 1e3 km3
utendwtem emDayZ m s-1 d-1
utendvtem emDayZ m s-1 d-1
prrsn emDay -
prsnsn emDay -
burntFractionAll emMon fraction
fracLut emYr fraction
fracOutLut emYr fraction
fracInLut emYr fraction
nwdFracLut emMon fraction
so Omon 0.001
soga Omon 0.001
sob Omon 0.001
sos Omon 0.001
sos Oday 0.001
sisali SImon 0.001
tob Omon C
co2s emMon 1e-06
psitem emDayZ kg s^-1
tro3Clim Amon 1e-09
tro3 Amon 1e-09
aod550volso4 emDay 1e-09
ch4global Amon 1e-09
n2oglobal Amon 1e-09
tro3 em3hr 1e-09
ch4globalClim Amon 1e-09
n2oglobalClim Amon 1e-09
somint Omon 1e-3 kg m-2
tomint Omon 1e-3 kg m-2
hcont300 emMon m K
fgcfc11 Omon mol sec-1 m-2
fgsf6 Omon mol sec-1 m-2
fgcfc12 Omon mol sec-1 m-2
```
Should `fraction` --> `1`, `C` --> `degC`, `kg s^-1` --> `kg s-1` and `mol sec-1 m-2` --> `mol s-1 m-2`?

**Comment by martinjuckes** [comment]
fraction, "C", kg s^-1, mol sec-1 m-2 fixed.  

Why do you think the numerical values, 0.001 and 1.e-9 are suspect? This is how CF encodes "parts-per-thousand" and "parts-per-billion".

**Comment by ehogan** [comment]
> fraction, "C", kg s^-1, mol sec-1 m-2 fixed.

Great, thank you! What should `DU`, `m s-1 d-1`, `-` and `m K` be?

> This is how CF encodes "parts-per-thousand" and "parts-per-billion".

You learn something new every day! :) Would it be worth making the values consistent? So instead of the different variations, e.g. `0.001`, `1e3`, `1.e6`, `1e-09`, use `1e3`, `1e6`, `1e-9`, etc.

**Comment by martinjuckes** [comment]
Fixed .. all units used are shown in http://clipc-services.ceda.ac.uk/dreq/index/units.html
