### ISSUE TITLE
HighResMIP and the picontrol run

### ISSUE THREAD

**Issue by matthew-mizielinski** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#48]
From [the data request web pages](http://clipc-services.ceda.ac.uk/dreq/u/_slice_piControl200.html) it appears that HighResMIP is requesting 200 years of high frequency data from the pre-industrial control run. I'm reasonably confident that this was not the intention of the HighResMIP leads (Malcolm Roberts & Rein Haarsma). 

I will confirm with them what the requirement is and update this issue asap.

**Comment by martinjuckes** [comment]
It is what they asked for in the template they submitted ... but let me know what they say, it is sertainly worth checking.

**Comment by matthew-mizielinski** [comment]
Having checked with Malcolm, it turns out that I was quite wrong, those 200 years were requested from the piControl run. 

Malcolm's take on these data is that this data is genuinely useful for HighResMIP, but he is expecting all priority 3 variables to be ignored by most/all groups and individual groups will need to make their own call on whether the high cost variables are practical. Our experience from PRIMAVERA is that anything more frequent than 6 hourly will be ignored by most groups, other than short windows (up to 10 years).

**Comment by martinjuckes** [comment]
OK,  thanks for checking. It is also my impression that the supply of priority 3 variables is going to be quite limited.
