### ISSUE TITLE
change cell-method for 8bae6a3c-4a5b-11e6-9cd2-ac72891c3257

### ISSUE THREAD

**Issue by robertsmalcolm** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#61]
For the variable web_bulb_potential_temperature (UID 8bae6a3c-4a5b-11e6-9cd2-ac72891c3257), it is more informative to be instantaneous (time:point) rather than mean, so please change this in the data request.

Thanks,
Malcolm Roberts (HighResMIP)

**Comment by martinjuckes** [comment]
Fixed in 1.00.03
