### ISSUE TITLE
"area: mean where sea_ice" missing from cell_methods

### ISSUE THREAD

**Issue by ehogan** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#65]
A number of variables with `cell_methods` that used to contain `area: mean where sea_ice`, e.g. `siconc`, `sndmasssi`, now only contain [time: mean](http://clipc-services.ceda.ac.uk/dreq/u/f7dcac96-562c-11e6-a2a4-ac72891c3257.html). Was this intentional?

**Comment by martinjuckes** [comment]
For `siconc` : yes: this is meant to provide the amount of sea-ice in the grid cell as a whole. This does leave some ambiguity about `sndmasssi` , which I need to clear up: at the moment the `cell_methods` implies that snow to ice conversion on land ice would be included, but this is not intended.

**Comment by martinjuckes** [comment]
`sndmasssi` now has a modified standard name which makes this clear: it is the conversion from snow to sea-ice, averaged over the whole grid area.
