### ISSUE TITLE
cell_methods for ua, va "day" variables

### ISSUE THREAD

**Issue by taylor13** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#66]
Some text at https://www.earthsystemcog.org/projects/wip/drq_interp_cell_center says:

"The variables ua, va in the day table where specified with no cell_measures, but in CMIP6 they will be requested on grid centres. In the CMIP5 archive these variables have been archived by all groups on the cell centres."

I don't understand why this change has been made.  I think it should be up to the modeling groups to decide what grid to report ua, va, uas, and vas.  I suspect whoever said ua and va should be reported at grid cell centers didn't understand that there was an option to allow groups to decide which grid was most appropriate.  Do you know why the change was made?

I am also curious about how the grid specifications are communicated to the user.  Do they infer that grid-centered data is required whenever cell_measures="areacella"?  I think the cell_measures metadata should not be used for the purpose of specifying a grid; it should be reserved simply to tell CMOR whether a cell_measures attribute is required or not and if required what the value should be.  Do you agree?

**Comment by martinjuckes** [comment]
Hello Karl,

"areacella" is a variable which is stored on cell centres, and the CF convention requires that any variable using the cell_measures construct should have the same coordinates, hence I believe that it is the case that cell_measures="areacella" can only be set when the data is on cell centres. 

We had an email discussion some months ago about the daily ua, va data. As I recall Balaji was in favour of having the data on grid centres unless there is a specific reason specify otherwise or allow more variabilty.  The discussion was about making a change with respect to CMIP5, so I think it was clear that we were talking about reducing the degree of flexibility and making the request more specific.

**Comment by taylor13** [comment]
I'm o.k. with having daily ua and va be recorded at cell centers if there is general agreement about that.  I also agree that "areacella" can only be set when the data is on cell centers.  

So, if areacella is set, then this implies you need to report the data at grid centers.  However, I don't think that data reported at grid cell centers should in all cases require that areacella be set.  The main use of areacella is to enable users to accurately calculate area means.  In the case of a ua or va field that has been interpolated to grid cell centers, the "true" spatial mean cannot be guaranteed, and I would argue that it would be misleading to include areacella as metadata for these variables.  

Thus, I don't think we necessarily should follow the rule:  "When data is requested at the cell center it will have a cell_measures attribute value specified."  I would like *not* to include the cell_measures attribute on ua and va (for example), because they are *not* originally carried on grid cell centers, and the area associated with these fields (on their original nets) may either be undefined or different from areacella.

If we relax the statement that "when data is requested at the cell center it will have a cell_measures attribute value specified," would that muck up anything? 

[This is why I commented:  "I am also curious about how the grid specifications are communicated to the user. Do they infer that grid-centered data is required whenever cell_measures="areacella"? I think the cell_measures metadata should not be used for the purpose of specifying a grid; it should be reserved simply to tell CMOR whether a cell_measures attribute is required or not and if required what the value should be."]

**Comment by jkettleb** [comment]
As you probably remember from CMIP5 providing ua/va on pressure levels at 'cell centres' from our model requires post processing regridding.   As we have a lot on we are not confident we can deliver regridded data early on.  Is it possible to relax the request for ua/va on pressure levels to be on cell centres (and remove the cell_measures) but then recommend native grid ua/va are supplemented with regridded fields (with ua/va on the same grid as ta, zg etc) at some stage?

This would mean those data users who can use 'staggered' data will be able to use our ua/va on pressure levels in analysis from early on.

**Comment by martinjuckes** [comment]
Hello Karl,

The idea of the statement "when data is requested at the cell center it will have a cell_measures attribute value specified" was to be clear about what is requested. Maybe it is ambiguous ... what I meant to say was "when data is requested at the cell center it will have a cell_measures attribute value specified **in the data request**". I.e. we will indicate that a variable is wanted at the cell centre be setting a cell_measures value. This is not quite as requiring that it be set in the data files. 

I'll send an email to the WIP list about the policy on ua/va,

Martin

**Comment by martinjuckes** [comment]
Discussion closed.
