### ISSUE TITLE
cell_methods for zonal means missing longitude: mean

### ISSUE THREAD

**Issue by ehogan** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#67]
Some [zonal means in the data request](http://clipc-services.ceda.ac.uk/dreq/u/f7df8fce-562c-11e6-a2a4-ac72891c3257.html) have `cell_methods` that contain `longitude: mean`, whereas [others](http://clipc-services.ceda.ac.uk/dreq/u/f7e94ce4-562c-11e6-a2a4-ac72891c3257.html) don't. Shouldn't all zonal means have `cell_methods` that contain `longitude: mean`?

**Comment by martinjuckes** [comment]
Yes, they should all have cell_methods longitude: mean.

I'll run a check on AERmonZ, E6hrZ, EdayZ, EmonZ.

**Comment by jkettleb** [comment]
Hello Martin,

Could you watch out for the TEM diagnostics - EP fluxes etc.  I don't think these should have the cell_methods longitude mean set.  They are zonal mean diagnostics, but they don't have full longitudinally varying counterparts - so they aren't really 'longitude:mean' of anything.

Jamie

**Comment by martinjuckes** [comment]
Hi Jamie,

I think that the TEM diagnostics would count as "longitude: mean" in the sense of the CF convention. I don't think the convention is precise enough to distinguish between a simple mean and the TEM usage: you have to rely on the standard name for that.

**Comment by martinjuckes** [comment]
A fix has been applied, for release in version 01.00.01, subject to any changes which might apply if Jamie wants to push his point. E.g. there may be a case for adding a comment in the cell_methods string for non-standard zonal means. I've already done this for ocean basin zonal means: "longitude: mean (basin)".

**Comment by jkettleb** [comment]
Hello Marin,

thanks for considering the TEM diagnostics.  I'm not going to push the point... its a subtle one that I don't think we have got time to get distracted with.  You point about using the standard_name as the guide is a good one.

Thanks for fixing the wider problem.

Jamie
