### ISSUE TITLE
lwsnl shloud have a 3D structure (according to its label : Liquid Water Content of Snow Layer)

### ISSUE THREAD

**Issue by senesis** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#70]

**Comment by senesis** [comment]
I got the answer that snow mantle variable ultimately are not requested per snow layer. In this context, the label above remains only slightly misleading (it must be understood as ... content of the whole snow mantle, or .. content of the -single- snow layer)

**Comment by martinjuckes** [comment]
Variable description clarified.
