### ISSUE TITLE
DR 1.0 is missing a variable for profile of snow layer depth (or snow density)

### ISSUE THREAD

**Issue by senesis** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#71]
DR includes profiles of snow amount (snw)  and snow water amount (lwsnl), but you need to know the layer depths to get the profile of snow density (or the density profile itself)

**Comment by martinjuckes** [comment]
snw and lwsnl are currently defined as surface snow amount and liquid water amount in the surface snow. As in CMIP5, they are vertical integrals, not profiles. Earlier versions of the CMIP6 data request referred to vertical profiles, but an email from Hyungjun Kim on 21st December changed the specification of "snow water equivalent" and "snow temperature" to vertically integrated quantities.
