### ISSUE TITLE
DCPP issues

### ISSUE THREAD

**Issue by DougSmithMO** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#72]
(1) The following are missing:
6 hourly: tas, uas, sfcWind, psl and pr
monthly: cLand and netAtmosLandCO2Flux, and hfnorth

(2) The priority is too low for zossq, vsf, expc and epsi100 (all monthly)

(3) zfull should be time dependent, but is listed in Ofx as fixed

**Comment by martinjuckes** [comment]
(1) I've added*:
6 hourly: tas, uas, sfcWind, psl and pr
monthly: cLand and netAtmosLandCO2Flux
OMIP have replaced hfnorth with hfbasin. hfnorth was a CMIP5 variable, but the dimensions specified were not consistent with the description of the variable, hence the clarification and name change. Is hfbasin what you need?

(2) 
vsf is already requested by DCPP at priority 1 (see http://clipc-services.ceda.ac.uk/dreq/u/baa65a76-e5dd-11e5-8482-ac72891c3257.html ) ... let me know if you see it listed at a lower priority somewhere.  HighResMIP and OMIP are specifying it at a lower priority.
 zossq,  expc and epsi100: I've increased these to priority 1*

(3) I dont see zfull in Ofx ... where do you see this?

*: subject to final checks and release 01.00.01

**Comment by martinjuckes** [comment]
All checked
