### ISSUE TITLE
ocean variables requested from the amip experiment

### ISSUE THREAD

**Issue by matthew-mizielinski** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#73]
The following requestItems are linking the atmosphere-only, amip experiment with ocean variables;

 * [CfmipCfmipOmon3d](http://clipc-services.ceda.ac.uk/dreq/u/e5cfa5e2-c7bc-11e6-8239-ac72891c3257.html)
 * [HighresmipHighresmipOmonOth](http://clipc-services.ceda.ac.uk/dreq/u/e5ea12a6-c7bc-11e6-8239-ac72891c3257.html)
 * [Ismip6Ismip6Omon](http://clipc-services.ceda.ac.uk/dreq/u/e5f22a7c-c7bc-11e6-8239-ac72891c3257.html)
 * [Ismip6Ismip6Omonnew](http://clipc-services.ceda.ac.uk/dreq/u/e5f2f3c6-c7bc-11e6-8239-ac72891c3257.html)

While it is fairly straightforward to ignore these variables in this experiment it would be cleaner to remove the connection if possible.

**Comment by matthew-mizielinski** [comment]
Still present in v01.00.01

**Comment by martinjuckes** [comment]
I'm removing these now. Does it make sense to request sea-ice variables for AMIP (http://localhost/f/u/94003f96-267c-11e7-8933-ac72891c3257.html )?

**Comment by martinjuckes** [comment]
Resolved.
