### ISSUE TITLE
HighResMIP missing ocean variables

### ISSUE THREAD

**Issue by jonseddon** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#75]
Hi,

Several variables have been removed from the Omon table in HighResMIP that we weren't expecting to go. The difference happened somewhere between beta 37 and1.0. @matthew-mizielinski suggested these might be due to other tables not being linked in. The variables in question are:

pr *
somint **
tomint
tosga **
bigthetao **
bigthetaoga **

* we thought that this was being replaced by prls
** these are all requested in the OMIP GMD paper

Thanks,

Jon

**Comment by jonseddon** [comment]
We think that we know where these variables have gone. If the statement below is correct then this is no longer an issue

> In DR v01, there's a new MIP defined : 'CMIP'. Sounds to be the 'floor' request across all MIPs. When querying DR v01 for 'HighResMIP'+'CMIP', bigthetao, bigthetaoga, somint and tosga are back again.


Thanks,

Jon

**Comment by martinjuckes** [comment]
Fixed: they should also be visible without adding CMIP, in the next version.
