### ISSUE TITLE
Incorrect model realm?

### ISSUE THREAD

**Issue by matthew-mizielinski** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#77]
I've noticed that the following variables have an unexpected model_realm of `aerosol` where I would expect `atmos`:

Relative vorticity at 850 hPa [6hrPlev/rv850](http://clipc-services.ceda.ac.uk/dreq/u/8b920d10-4a5b-11e6-9cd2-ac72891c3257.html)
Geopotential height at 1000 hPa [6hrPlev/zg1000](http://clipc-services.ceda.ac.uk/dreq/u/8b920734-4a5b-11e6-9cd2-ac72891c3257.html)

Both had realm `atmos` at version 01.beta.38 of the request.

**Comment by martinjuckes** [comment]
fixed
