### ISSUE TITLE
Pressure level variable requested on model levels

### ISSUE THREAD

**Issue by matthew-mizielinski** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#78]
The entry for "Relative vorticity at 850 hPa" in 6hrLev ([6hrLev/rv850](http://clipc-services.ceda.ac.uk/dreq/u/d454a620-c78d-11e6-9b25-5404a60d96b5.html)) requests output on model levels in conflict with the variable long name/title.

**Comment by martinjuckes** [comment]
Fixed in 01.00.02
