### ISSUE TITLE
Should exchange 'rivo' and 'rivi' description

### ISSUE THREAD

**Issue by senesis** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#84]
These variables read :
  - rivi , , water_flux_to_downstream [[River Discharge] ]((m3 s-1) )
  - rivo , , water_flux_from_upstream [[River Inflow] ]((m3 s-1) )
which looks wrong

**Comment by martinjuckes** [comment]
Corrected (rivi is inflow, rivo is outflow)
