### ISSUE TITLE
Should add variables 'areacellr', and 'sftrf'

### ISSUE THREAD

**Issue by senesis** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#85]
For AOGCM models which have a river model running on its own grid, there is no way to describe it, both for grid mesh areas and for fraction of the area occupied by rivers
This hinders intercomparison of river models

**Comment by senesis** [comment]
Please forget about adding sftrf

**Comment by martinjuckes** [comment]
The fraction of area occupied by rivers should be reported in `landCoverFrac`, if river is one of the modeled area types. `landCoverFrac` will also cover lake areas. Hyungjun has raised the issue of river flow directions: the request includes river inflow (`rivi`) and outflow (`rivo`), but does not have flow direction information.  Not included in latest LS3MIP request, so perhaps we can do without.

**Comment by senesis** [comment]
OK for landCoverFrac (albeit it does not match the design of our Surface Model, which knows about Land, Lakes, Town and Sea)
But again :  "For AOGCM models which have a river model running on its own grid, there is no way to describe [...] grid mesh areas ". 
We are running CTRIP river model as a separate, coupled model/process, and we provide related diagnostics (dgw, drivw, fcLandToOcean, qgwr, rivi, rivo, waterDpth, wtd) on its grid

**Comment by martinjuckes** [comment]
OK, I'll add areacellr, and I will also need to add an option for dgw, drivw, fcLandToOcean, qgwr, rivi, rivo, waterDpth, wtd to be provided with areacellr rather than areacella (to stop an error be flagged by metadata checkers). I'll post an issue on the CMOR track to see if they have any other concerns.

**Comment by martinjuckes** [comment]
I think waterDpth and wtd are the same .. I'll merge these two variables.

**Comment by senesis** [comment]
Yes. The former was defined by C4MIP, the latter was already defined in CMIP5

**Comment by senesis** [comment]
Shuld this statement : `I will also need to add an option for dgw, drivw, fcLandToOcean, qgwr, rivi, rivo, waterDpth, wtd to be provided with areacellr rather than areacella ` be visible in DR 01.00.15

**Comment by martinjuckes** [comment]
We decided to have these with areacellr, with the advice that the areacellr data file should contain areacella data values if the model does not have a distinct river grid.
