### ISSUE TITLE
missing cell_methods: time: mean or time point?

### ISSUE THREAD

**Issue by jkettleb** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#86]
I think that a few variables have missing cell_methods.

6hrLev pmlev
6hrPlev ta
6hrPlev ua
6hrPlev va
6hrPlev ua100m
6hrPlev va100m
6hrPlev wsgmax100m
Emon H2wv
Emon hcont300
Emon md
Emon O17wv
Emon O18wv
Emon pfull
Emon phalf
Emon tntlw
Emon wo
Emon concdust
SImon sidmasstranx
SImon sidmasstrany

Should these be time:point or time:mean?

**Comment by martinjuckes** [comment]
Fixed on 1.00.02:
SImon sidmasstranx: time: mean
SImon sidmasstrany: time: mean
Emon fields: all set to "time: mean"

**Comment by jkettleb** [comment]
Thanks Martin,
Can we take the others as time:point or do you want to make this explicit?
Jamie

**Comment by martinjuckes** [comment]
These should all now have explicit time specification in the cell methods
