### ISSUE TITLE
wrong spatial shape for msftyrho and msftyrhompa (?) : shouldn't quote latitude

### ISSUE THREAD

**Issue by senesis** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#88]
These two variables are variants of msftmrho and msftmrhompa, but with a Y (model dependant) axis instead of a latitude axis. So, in  my understanding, they should not quote 'latitude' in their spatial shape, but some other dimension.

**Comment by martinjuckes** [comment]
The definition is as for CMIP5: it is an average along a zig-zag path "corresponding to" the latitude. Hence, I believe the use of the latitude coordinate is, as in CMIP5, intended. It is not an average at fixed "Y".
