### ISSUE TITLE
E1hrClimMon table has cell_methods 'days'

### ISSUE THREAD

**Issue by jkettleb** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#89]
I think the cell_methods are incorrect in the E1hrClimMon table - they say 'days'.

**Comment by martinjuckes** [comment]
The table is meant to contain monthly mean diurnal cycles. As with climatologies of the annual cycle ( `time: mean within years time: mean over years` ), the cell methods string gives the period of the cycle that is being represented. The number of divisions within the cycle (hours for E1hrClimMon) and the number of cycles being averaged (a month) is given by the climatological bounds variable.

**Comment by jkettleb** [comment]
Sorry - my fault I didn't investigate the spreadsheets view of the data request as much as I should have.  The cells under cell_methods only said 'day' - but if I go into any cell and click on it then I can see the full text 'time: mean within days time: mean over days' appears in the current cell 'window'.
