### ISSUE TITLE
Units of uqint, vqint

### ISSUE THREAD

**Issue by martinjuckes** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#9]
New variables defined by HighResMIP ... units should be kg m-1 s-1 rather than m2 s-1?

**Comment by martinjuckes** [comment]
Standard name is under review ... this issue should be fixed there ...

**Comment by matthew-mizielinski** [comment]
If this hasn't already been dealt with then note that uqint and vqint are defined as 

"Column integrated eastward wind times specific humidity"

and as specific humidity is a dimensionless ratio the units `m2 s-1` are correct (`m s-1` from the velocity and `m` from the vertical integration).

**Comment by martinjuckes** [comment]
OK, units confirmed as "m2 s-1"
