### ISSUE TITLE
Duplicate CMORvar: 6hrPlev/psl

### ISSUE THREAD

**Issue by matthew-mizielinski** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#91]
There are two cmor variables named psl in the 6hrPlev table with the following uids

bab48ab0-e5dd-11e5-8482-ac72891c3257
d6b7cfba-def2-11e6-90c9-ac72891c3257

The first is an instantaneous value with prov field "6hrPlev ((isd.003))", and the second is a time mean with prov field "DCPP [DCPP-6hr]".

Note that the first of the above is a duplicate of the same variable in 6hrPlevPt (uid 8bb06e2c-4a5b-11e6-9cd2-ac72891c3257).

I recommend:
a) deleting bab48ab0-e5dd-11e5-8482-ac72891c3257 from the data request
b) ensuring that the [web page listing the CMOR variables](http://clipc-services.ceda.ac.uk/dreq/index/CMORvar.html) is sorted by CMOR variable (this used to be the case) making this issue easy to spot

This is the only duplicate miptable/cmorvar combination in the data request (I've checked)

**Comment by martinjuckes** [comment]
fixed
