### ISSUE TITLE
Esubhr dimension order inconsistent with CFsubhr

### ISSUE THREAD

**Issue by jkettleb** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#92]
Variables in CFsubhr are dimensioned 'alevel site time1'
Variables in Esubhr are dimensioned 'alevel time1 site'

Should these be consistent? If the diagnostics from Esubhr and CFsubhr are used in the same analysis then I think it is easier for the analyst if they are consistent.

**Comment by jkettleb** [comment]
Sorry, after opening this issue I just realised: shouldn't 'timeX' always be the last dimension - then it can be the record dimension in the NetCDF file?  That's how it would be in NetCDF3 - so I think the same carries over the NetCDF4 classic?

There are many diagnostics (not just those in Esubhr) where 'timeX' isn't the last dimension.

I think a possible exception is if the last dimension is scalar  - but I don't think 'site' is.

**Comment by martinjuckes** [comment]
Thanks .. the "dimensions" column in the spreadsheet should be of the form:
[spatial dimensions] [other dimensions] [time dimension] [coordinates]. 

The time dimensions and "other dimensions" had been switched ... fixed now (1.00.03)
