### ISSUE TITLE
Could zfull be added to miptable fx?

### ISSUE THREAD

**Issue by matthew-mizielinski** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#94]
At version 1.00.02 the mip variable `zfull`, Altitude of Model Full-Levels, is requested in mip tables Eyr, E3hr, CF3hr (see [here](http://clipc-services.ceda.ac.uk/dreq/u/216ab26c-b89b-11e6-a189-5404a60d96b5.html))

In HadGEM3 & UKESM models the model levels in the atmosphere are configured through a hybrid height scheme which is time invariant.  We could omit this variable or duplicate the same data to match the requested frequency, but it would be preferable to have a suitable entry in a fixed table.

**Comment by martinjuckes** [comment]
Will add in 1.00.07

**Comment by martinjuckes** [comment]
Done
