### ISSUE TITLE
COSP Curtains in CF3hr table (site profiles OK)

### ISSUE THREAD

**Issue by matthew-mizielinski** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#95]
The variables listed below are requested on ~~site profiles or~~ COSP curtains in the CF3hr table and global fields in the E3hrPt table. As I understand it the global fields were requested by CFMIP and the ~~profiles/~~curtains are inherited from CMIP5. Should the entries in CF3hr be removed, given the CFMIP requests in E3hrPt?

~~Site profile in CF3hr and Global field in E3hrPt:~~
- ~~cfadDbze94~~
- ~~cfadLidarsr532~~
- ~~clcalipso~~
- ~~clcalipso2~~

COSP curtain in CF3hr and global field in E3hrPt:
- clhcalipso
- cllcalipso
- clmcalipso
- cltcalipso
- parasolRefl

If the above curtain variables are removed from CF3hr, then the following variables can also go:
- latitude
- longitude
- toffset

For HadGEM3/UKESM1 our current plans are to produce the global fields and omit the ~~site profiles and~~ COSP curtains.

_Update following review of this issue by Alejandro Bodas-Salcedo (errors were my fault)_

**Comment by martinjuckes** [comment]
Curtain fields removed
