### ISSUE TITLE
all "fixed" variables should be independent of time

### ISSUE THREAD

**Issue by taylor13** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#96]
@martinjuckes: Since "fx" stands for "fixed" (meaning independent of time), the variables in tables AERfx, Efx, IfxAnt, IfxGre, Ofx, and fx have been correctly assigned frequency="fx".  Many variables in these tables, however, show "time" as a dimension and some include a cell_methods "time: mean".  These variables should be transferred to another table if they are functions of time, or the time dimension and corresponding cell_method should be removed.

**Comment by martinjuckes** [comment]
Done

**Comment by jypeter** [comment]
I'm looking at CMIP6_MIP_tables.xlsx version 01.00.06 and I was going to raise a similar issue: there are fluxes in Efx that depend on time. Same thing for variables in IfxAnt and IfxGre

**Comment by jypeter** [comment]
@martinjuckes I have just downloaded _01.00.07_ and **there are still _fx_ variables with a time axis** in Efx, IfxAnt and IfxGre
