### ISSUE TITLE
V01.00.02 : esid is unset for OmipB Request Items: "specifying the number of years for an experiment"

### ISSUE THREAD

**Issue by senesis** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#98]
This happens for tables Odat, Oyr,Ofx, Odec
See e.g. http://clipc-services.ceda.ac.uk/dreq/u/c02bd968-ec84-11e6-999a-5404a60d96b5.html

**Comment by martinjuckes** [comment]
Fixed for 01.00.13
