### ISSUE TITLE
In V.01.00.02 : cell methods is undefined for 6 'structure' records

### ISSUE THREAD

**Issue by senesis** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#99]
Namely, for the list below :

Issue with cell_method for str-a006
Issue with cell_method for str-a057
Issue with cell_method for str-a453
Issue with cell_method for str-110
Issue with cell_method for str-a017
Issue with cell_method for str-a022

**Comment by martinjuckes** [comment]
fixed
